const en = {
  language: 'en-US',
  'kline.time_Line': 'Time',
  'kline.time_1m': '1m',
  'kline.time_3m': '3m',
  'kline.time_5m': '5m',
  'kline.time_15m': '15m',
  'kline.time_30m': '30m',
  'kline.time_1H': '1H',
  'kline.time_2H': '2H',
  'kline.time_4H': '4H',
  'kline.time_6H': '6H',
  'kline.time_1D': '1D',
  'kline.time_1W': '1W',
  'kline.time_1M': '1M',
  'kline.tab_line': 'Chart',
  'kline.tab_depth': 'Depth',
  'kline.chartType_Bars': 'Bars',
  'kline.chartType_Candles': 'Candles',
  'kline.chartType_Hollow_Candles': 'Hollow Candles',
  'kline.chartType_Line': 'Line',
  'kline.chartType_Area': 'Area',
  'kline.chartType_Heikin_Ashi': 'Heikin Ashi',
  degate_account: 'DeGate Account',
  Trade: 'Trade',
  Order: 'Order',
  Grid: 'Grid Strategy',
  Campaign: 'Campaign',
  DCA: 'DCA',
  Advanced: 'Advanced',
  Add: 'Add',
  Add_Funds: 'Add Funds',
  eth_added_1: '1 ETH Added',
  eth_sent_1: '1 ETH Sent',
  Send: 'Send',
  Internal_Transfer: 'Internal Transfer',
  Miscellaneous: 'Miscellaneous',
  Bridge: 'Bridge',
  Mining: 'Mining',
  Liquidity_Mining: 'Liquidity Mining',
  Analytics: 'Analytics',
  Support: 'Support',
  Help: 'Help',
  Tips: 'Tip',
  Statistics: 'Statistics',
  Coming_soon: 'Coming Soon',
  Faucet: 'Faucet',
  more: 'More',
  hide: 'Hide',
  change: 'Change',
  'Wrong Network': 'Wrong Network',
  avbl: 'Avbl:',
  chain_1: 'Mainnet',
  chain_3: 'Ropsten',
  chain_4: 'Rinkeby',
  chain_5: 'Goerli',
  chain_42: 'Kovan',
  chain_42161: 'Arbitrum',
  chain_10: 'Optimism',
  insufficient_balance_AAA:
    'There is not enough AAA in your wallet. Please check and try again.',
  insufficient_balance: 'Insufficient balance',
  wallet_denied_sign: 'Message signature was rejected.',
  common_err: 'Something went wrong. Please try again later.',
  common_err_ledger_version:
    'An error has occurred. Please ensure that your Ledger Ethereum app is up to date(1.9.10 or later), or you may try again later.',
  network_1: 'Ethereum mainnet',
  network_err: 'Network error. Please try again later.',
  rate_limit_err: 'Access frequency is too high, please retry in one minute.',
  error_InsufficientGasFunds: 'Insufficient Gas in wallet',
  notification_transaction_send: 'Transaction sent',
  view_on_etherscan: 'View on Blockchain Explorer',
  view_on_explorer: 'View Address',
  switch_network: 'Switch Network',
  switch_to_Arbitrum: 'Switch to Arbitrum to continue.',
  switch_to_MAINNET_in_metamask: 'Please switch to MAINNET in MetaMask',
  switch_to_MAINNET: 'Please switch to MAINNET',
  switch_network_in_walletconnect:
    'Go to your wallet and switch network with WalletConnect',
  Retry: 'Retry',
  wallet_tips: 'Please approve in browser wallet',
  wallet_ledger_tips: 'Please approve in Ledger hardware',
  wallet_metamask_tips: 'Please approve in MetaMask',
  wallet_walletconnect_tips:
    'Please go to your wallet to approve with WalletConnect',
  wallet_cancelled_tips: 'You have canceled the signature',
  Close: 'Close',
  copied: 'Copied',
  Details: 'Details',
  view_details: 'View Details',
  Share: 'Share',
  view_graph: 'View in Chart',
  Dismiss: 'Dismiss',
  Cancel: 'Cancel',
  End: 'End',
  End_grid: 'End',
  Confirm: 'Confirm',
  Cancel_all: 'Cancel All',
  cancel_all_tips: 'Cancel all open orders',
  Submit: 'Submit',
  no_data: 'No data',
  all_data_displayed: 'All data displayed',
  no_data_within_90_days: 'No data within 90 days',
  only_display_90_days: 'Only displaying data from past 90 days',
  displayed_90_days: 'Displaying data from past 90 days',
  only_data_beyond_90_days_trade:
    'To access data beyond 90 days, please select "View All"  followed by the "Export Data" function',
  only_data_beyond_90_days_grid_detail:
    'The historical query of data beyond the recent 90 days is currently not supported',
  only_data_beyond_90_days_spot_history:
    'To access data beyond 90 days, please use the "Export Data" function',
  View: 'View',
  service_unavailable_for_region_REGION:
    'This service is unavailable in REGION.',
  service_unavailable: 'Service is not available',
  service_error: 'Please try again later',
  service_maintenance: 'This service is undergoing maintenance.',
  connect_wallet: 'Connect Wallet',
  switch_address: 'Switch Address',
  wallet_wc: 'Connected with WalletConnect',
  wallet_ledger: 'Connected with Ledger',
  register_dexAccount: 'Register',
  deposit_ETH: 'Add ETH',
  initialize: 'Initialize',
  initialization: 'Initialization',
  invalid_signature: 'Invalid Signature',
  possible_cause: 'Possible cause:',
  locale_time_error: 'Your local device time is inaccurate.',
  authorization_mode: 'Auth. Mode',
  authorization_mode_standard: 'Signature-free',
  authorization_mode_single_use: 'Always Sign',
  turn_on: 'Turn on',
  turn_on_signature_free_mode: 'Turn on Signature-free mode',
  signatre_free_mode: 'Signature-free Mode',
  turn_on_signature_free_mode_tips:
    'In this mode, you can place orders without signing. To switch mode, navigate to "Settings" located below the Trade Button.',
  turn_on_signature_free_mode_tips_grid:
    'In this mode, you can create grid strategies without signing. To switch mode, navigate to "Settings" located below the Trade Button.',
  turn_on_signature_free_mode_tips_dca:
    'In this mode, you can create DCA plans without signing. To switch mode, navigate to "Settings" located below the Trade Button.',
  yes: 'Yes',
  no: 'No',
  free_mode_on: 'Signature-free Mode On',
  view_balance: 'View Balance',
  delete_asset_key: 'Delete Asset Key',
  delete_asset_key_desc:
    'The Signature-free mode will be turned off once the Asset Key is deleted from your browser.',
  no_asset_key_tips: 'No Asset Key found in your browser',
  turn_off_standard_mode: 'And turn off Signature-free mode',
  reset_asset_key: 'Reset Asset Key',
  view_asset_key: 'View Asset Key',
  lock_success: 'Asset Key Deleted',
  reset: 'Reset Asset Key',
  delete: 'Delete',
  withdraw_ETH: 'Send ETH',
  transfer_ETH: 'Internal transfer ETH',
  history: 'History',
  view_history: 'View in History',
  internal_transfer: 'Transfer',
  assets_record_link: 'History',
  other: 'Other',
  login_success: 'Connect Success',
  Account: 'Account',
  Address: 'Address',
  Disconnect: 'Disconnect',
  copy_address: 'Copy Address',
  copy_grid: 'Copy Strategy',
  Copy: 'Copy',
  btn_search: 'Search',
  btn_reset: 'Reset',
  btn_confirm: 'Close',
  btn_max: 'Max',
  btn_ok: 'Ok',
  spot_trade: 'SPOT',
  grid_trade: 'GRID',
  err_balance_title: 'Failed to Place Order',
  err_balance_content:
    'Insufficient available balance. Please verify and try again.',
  order_failed: 'Order Failed',
  insufficient_order_value: 'Insufficient Order Value',
  grid_failed: 'Creation Failed',
  err_eth_gas: 'Ethereum network severely congested',
  err_insufficient_balance_TOKEN1: 'Insufficient TOKEN1 balance',
  err_insufficient_balance_TOKEN1_TOKEN2:
    'Insufficient TOKEN1 and TOKEN2 balances',
  please_add_funds_before_ordering:
    'Please add funds to your DeGate Balance before ordering.',
  err_balance_content_spot:
    'Failed to place order due to insufficient balance.',
  err_balance_content_grid:
    'Failed to create grid strategy due to insufficient balance.',
  trade_min_volume_tips_XXX: 'Min XXX',
  grid_min_volume_tips:
    'The Quantity per Order does not meet the minimum amount. Please try again.',
  trade_risk_orders_tips:
    'Unable to place order as you have too many open orders',
  gas_token_tips: 'Select gas fee token',
  add_favorite_tooltip: 'Add to favorites',
  remove_favorite_tooltip: 'Remove from favorites',
  expire_tips_X: 'This order will expire on X.',
  today: 'Now',
  now: 'Now',
  time_D_day: 'Dd',
  time_D_day_H_hour: 'Dd Hh',
  time_H_hour_M_minute: 'Hh Mm',
  time_M_minute_S_second: 'Mm Ss',
  time_S_second: 'Ss',
  around: '～ ',
  time_now: 'now',
  time_before: ' ',
  time_before_ago: ' ago',
  time_1_minute: '1 minute',
  time_1_hour: '1 hour',
  time_1_day: '1 day',
  time_1_year: '1 year',
  time_M_minutes: 'M minutes',
  time_M_m: 'Mm',
  time_H_hours: 'H hours',
  time_H_h: 'Hh',
  time_D_days: 'D days',
  time_Y_years: 'Y years',
  time_Y_y: 'Yy',
  fee_change_tips: 'Price Updated',
  no_pairs: 'Trading Pair Not Found',
  register_new_pair: 'Add New Pair',
  register_pair: 'Add Trading Pair',
  add_pair: 'Add Pair',
  tips_hide_forever: 'Don’t show again',
  token: 'Token',
  action: 'Action',
  more_actions: 'More',
  gas_fee: 'Gas Fee',
  'orders.detail_gas': 'Actual Gas Fee',
  trade_fee: 'Trading Fee',
  about_degate: 'About DeGate',
  metrics: 'Metrics',
  fees: 'Fees',
  document: 'Docs',
  join_us: 'Join Us',
  feedback: 'Feedback',
  email_optional: 'Your Email address (Optional)',
  Upload: 'Upload',
  feedback_upload_tip: 'Please share your feedback. Drag files to attach.',
  feedback_upload_tip_mobile: 'Please share your feedback. ',
  image_upload_tip: 'Release to Add',
  feedback_success: 'We hear you loud and clear!',
  feedback_success_2: 'Thank you',
  feedback_failed: 'Submission failed. Please try again later.',
  image_upload_rule_1: 'Support PNG, JPG, JPEG only.',
  image_upload_rule_2: 'Max size is 20MB per file.',
  image_upload_rule_2_3: 'Max size is 20MB per file. Up to 5 files.',
  no_pair: 'Token Pair Not Found',
  no_token: 'Token Not Found',
  choose_base_token: 'Select Base Token',
  choose_quote_token: 'Select Quote Token',
  get_test_token: 'Get Testnet Token',
  faucet: 'Faucet',
  expire_in: 'Expire in',
  expire_in_empty_err: 'Please enter a number',
  go_back: 'Go Back',
  max_XXX: 'Max XXX',
  min_XXX: 'Min XXX',
  fill_in: 'Fill in',
  my_balance: 'My Balance',
  deGate_insufficient_fees: 'Insufficient DeGate Balance to pay for Gas Fee',
  wallet_balance: 'Wallet Balance',
  your_wallet_balance: 'Your Wallet Balance',
  degate_balance: 'DeGate Balance',
  wallet_insufficient_fees: 'Insufficient balance in wallet',
  wallet_insufficient_balance: 'Insufficient balance',
  insuffficient_wallet_balance: 'Insufficient Wallet Balance',
  degate_insufficient_balance: 'Insufficient available balance',
  open_discord: 'Go to Discord Community',
  err_valid_until: 'Please adjust local time to standard time on your device',
  tips_gas:
    'The gas fee for executing this on-chain transaction will be deducted directly from your DeGate balance.',
  maker_free: 'Maker Free',
  trading_fee_rate: 'Trading Fee Rate',
  Free: 'Free',
  stop_service_1: 'Site is under maintenance',
  stop_service_2: 'Estimated Recovery Time',
  stop_upgrade:
    'The new version of the testnet is currently undergoing migration.',
  stop_trading_1: 'System Upgrade',
  stop_trading_2: 'Trading is suspended temporarily',
  sell: 'sell',
  buy: 'buy',
  SELL: 'SELL',
  BUY: 'BUY',
  Sell: 'Sell',
  Buy: 'Buy',
  sell_order: 'Sell Order',
  buy_order: 'Buy Order',
  edit: 'Edit',
  status_processing: 'Processing',
  status_processed: 'Pending',
  status_pending: 'Pending',
  status_confirming: 'Confirming',
  status_success: 'Success',
  status_completed: 'Finalized',
  status_failed: 'Failure',
  status_speeding_up: 'Speeding Up',
  status_canceling: 'Canceling',
  status_canceled: 'Canceled',
  in_progress: 'In Progress',
  limit_order: 'Limit',
  market_order: 'Market',
  stop_limit_order: 'Stop Limit',
  balance: 'Balance',
  empty_connect: 'Please connect wallet first',
  empty_register: 'Please initialize first',
  empty_months3: 'No data for the last 3 months',
  show_months3: 'Only showing data within the last 3 months',
  view_all: 'View All',
  D1: '1D',
  D5: '5D',
  M1: '1M',
  M3: '3M',
  M6: '6M',
  YTD: 'YTD',
  Y1: '1Y',
  all: 'All',
  view_more: 'More',
  paste: 'Paste',
  clear: 'Clear',
  total: 'Total',
  amount: 'Amount',
  order_amount: 'Order Amount',
  price: 'Price',
  order_total: 'Total',
  filledAmount: 'Amount',
  tradeFilledTotal: 'Value',
  orderFilledTotal: 'Total',
  filledAmount_amount: 'Filled/Amount',
  profit: 'Profit',
  incompatible_token:
    'Technical specifications of this token are not compatible with DeGate protocol.',
  next: 'Next',
  token_not_verified: 'Not Verified',
  token_not_verified_tips:
    'Contract address, Icon, and Symbol are unverified. Please check the contract address with official sources to avoid scams.',
  token_verified: 'Verified',
  token_verified_tips: 'Contract address, Icon, and Symbol match.',
  arrival_time: 'Arrive in',
  deposit_tips_region:
    'Please note that you are accessing DeGate in REGION. The trading and internal transfer features are unavailable after fund addition.',
  complete_time: 'Complete in',
  unable_to_initialize: 'Unable to initialize',
  filter_base: 'Base',
  filter_quote: 'Quote',
  filter_type: 'Type',
  filter_role: 'Role',
  option_maker: 'Maker',
  option_taker: 'Taker',
  start_data: 'Start Date',
  end_data: 'End Date',
  added_to_favorites: 'Added to favorites',
  removed_to_favorites: 'Removed from favorites',
  show_recents_50: 'The latest 50 data have been displayed.',
  terms_of_service: 'Terms of Service',
  tips_small_unfilled:
    'Based on degrees of precision specified in the system design, a small unfilled portion of the order has been returned to your DeGate Balance.',
  notification: 'Notification',
  server_message_SystemRecovery:
    'Please be informed that there are changes to your order statuses after system recovery.',
  learn_more: 'Learn More',
  connect_ledger: 'Connect Ledger',
  ledger_disconnect:
    "Failed to execute 'transferOut' on 'USBDevice': The device was disconnected.",
  gas_fee_expired: 'Gas fee has expired. Please submit again.',
  scroll_down_to_refresh: 'Scroll down to refresh',
  release_to_refresh_immediately: 'Release to refresh',
  no_more: 'No more data',
  loading: 'Loading...',
  force_withdrawing_token_tips:
    'The current operation cannot be performed as your force withdrawal request is being processed.',
  speed_up: 'Speed Up',
  transaction_submitted: 'Transaction Submitted',
  tx_speed_up: 'Speed Up Transaction',
  tx_cancel: 'Cancel Transaction',
  none: 'None',
  Language: 'Language',
  page: '/Page',
  go_to: 'Go to',
  icon_indicators: 'Indicators',
  icon_back: 'Back',
  icon_forward: 'Forward',
  icon_full_screen: 'Fullscreen',
  icon_exit_full_screen: 'Exit fullscreen',
  icon_buy_sell_orders: 'Buy and Sell Orders',
  icon_buy_orders: 'Buy Orders',
  icon_sell_orders: 'Sell Orders',
  icon_enable: 'Click to enable',
  icon_disable: 'Click to disable',
  icon_copy: 'Copy address',
  icon_view_explorer: 'View on Block Explorer',
  icon_display_by_profit: 'Display by profit',
  icon_display_by_time: 'Display by time',
  icon_switch: 'Switch',
  eth_code_tips: 'Native token of Ethereum. No token contract address.',
  TBD: 'TBD',
  go_to_discord: 'Or Join Discord to Create Ticket',
  release: 'Release: ',
  security: 'Security',
  colon: ': ',
  zero_balance: 'Zero Balance',
  ledger_app_version_tips:
    "Update your Ledger's Ethereum app to version 1.9.19 or higher to preview the message before signing.",
  ledger_contract_data_tips:
    'Please enable Blind signing or Contract data in the Ethereum app Settings',
  input_auto_corrected_tooltips:
    'Auto corrected your input after exceeding the maximum number of digits',
  maximum_decimal_reached: 'Maximum decimal places reached',
  verify_ownership: 'Verify Ownership',
  enable_trading: 'Enable Trading',
  learn_more_about_signatures_link: 'Learn more about signatures >',
  learn_more_about_signatures: 'Learn more about signatures',
  sign: 'Sign',
  sign_step1: 'Complete in Your Wallet',
  sign_step2: 'Complete 2nd Signature',
  not_now: 'Not Now',
  view_on_block_explorer: 'View on Blockchain Explorer',
  view_in_history: 'View in History',
  continue_to_place_order: 'Continue to Place Order',
  Save: 'Save',
  sign_to_view: 'Sign to view',
  available_degate_balance: 'Available DeGate Balance',
  Back: 'Back',
  token_has_not_listed: 'This token has not been listed on DeGate.',
  list_now: 'List Now',
  spread_15: 'Spread > 15%',
  connected: 'Connected',
  self_list_token: 'Instant Listing',
  claim_REBASE: 'Claim REBASE',
  time: 'Time',
  time_updated: 'Time Updated',
  show_in_X_m: 'Show in ~Xm',
  max_gas: 'Max Gas Fee',
  total_required: 'Total required',
  Required: 'Required',
  available_balance: 'Available Balance',
  please_add_funds: 'Please add funds to your DeGate Balance.',
  Side: 'Side',
  pending: 'Pending',
  active: 'Active',
  ended: 'Ended',
  name: 'Name',
  yield: 'Yield',
  time_created: 'Time Created',
  time_ended: 'Time Ended',
  frequency: 'Frequency',
  chain_cancel: 'Cancel On-Chain',
  status: 'Status',
  status_chainCancelProgressing: 'On-chain Cancelling',
  status_chainCancelCompleted: 'On-chain Canceled',
  filled_total: 'Filled/Total',
  start_time: 'Start Time',
  end_time: 'End Time',
  Summary: 'Summary',
  Orders: 'Orders',
  Tutorial: 'Tutorial',
  Earn: 'Earn',
  top_winner_24h: '24h Top Ranked',
  ID: 'ID',
  Select: 'Select',
  Create: 'Create',
  Review: 'Review',
  Airdrop: 'Airdrop',
  Countdown: 'Countdown',
  Day: 'Day',
  Hour: 'Hour',
  Minute: 'Minute',
  Second: 'Second',
  Days: 'Days',
  Hours: 'Hours',
  Minutes: 'Minutes',
  Seconds: 'Seconds',
  Claim: 'Claim',
  Expired: 'Expired',
  Claimed: 'Claimed',
  Welcome: 'Welcome',
  gas_tips_for_amount_exceed_6_digits:
    'Additional charges applied because the digits for the amount exceed the nominal limit of six digits.',
  input_auto_corrected_minStep_tips:
    'Auto-corrected your input to meet the minimum precision',
  order_max_limit: 'Maximum limit exceeded',
  order_min_limit: 'Minimum limit not reached',
  order_faild_min_limit: 'Order placement failed: Minimum limit not reached.',
  order_faild_max_limit: 'Order placement failed: Maximum limit exceeded.',
  disconnect_m: 'Disconnect',
  'account.account_manage': 'Security',
  'account.account_manage_more': 'About Authorization Mode and Asset Key >',
  'account.what_is_asset_key': 'About Authorization Mode and Asset Key',
  'account.total_value': 'Total Value',
  'account.hide_small_balances': 'Hide Small Balances',
  'account.add_to_metamask': 'Add token to Wallet',
  'account.assets_balance_total': 'Total',
  'account.assets_balance_available': 'Available',
  'account.assets_market': 'Value',
  'account.transfer_to_degate_balance': 'Add to DeGate Balance',
  'account.search_tokens': 'Search token',
  'account.deposit_title':
    'Assets will be deposited into your decentralized DeGate account. You have full custody of these assets.',
  'account.deposit_tips': 'You retain full custody of these funds.',
  'account.deposit_confirm_btn': 'Add',
  'account.deposit_approved_btn': 'Approved',
  'account.deposit_1_ETH': 'Add 1 ETH to your DeGate Balance',
  'account.deposit_status_pending': 'Pending',
  'account.deposit_status_pay_pending': 'Payment Due',
  'account.deposit_status_pay_waiting': 'Payment Broadcasted',
  'account.deposit_status_pay_confirming': 'Confirming Payment',
  'account.deposit_tips_block': 'Transaction awaiting block inclusion',
  'account.deposit_status_pay_btn': 'Pay',
  'account.pay_deposit_warning': 'Adding funds may incur additional gas fee',
  'account.pay_deposit_warning_tips':
    "Users might be required to bear the cost for adding funds as DeGate's subsidies have been completely used.",
  'account.deposit_pending_tips':
    'Speed up transaction in your wallet if pending over 5 minutes.',
  'account.deposit_pending_tips_ledger':
    'Speed up transaction if pending over 5 minutes.',
  'account.deposit_contract_tips_over_AMOUNT':
    'Fund additions over AMOUNT USD require the Advanced method.',
  'account.deposit_contract_tips_only_all':
    'Only the Advanced method of fund addition is supported',
  'account.suggest_100': '≥$100 suggested',
  'account.suggest_100_tips':
    'To place a limit order, amount over $100 is suggested.',
  'account.deposit_failed': 'Failed',
  'account.deposit_failed_tips':
    'The on-chain transaction for adding funds has failed.',
  'account.payment_due': 'Payment Due',
  'account.payment_due_tips':
    'Additional payment is required in order to credit the funds into your DeGate Balance.',
  'account.register_token_code_placeholder': 'Enter contract address',
  'account.register_token_code': 'Contract Address',
  'account.register_token_symbol': 'Symbol',
  'account.register_token_check': 'Check Listing Progress',
  'account.register_token_code_err_added': 'This token is being listed',
  'account.register_token_next_step': 'Next',
  'account.register_token_tips1':
    'Permission not needed for on-chain token listing. Please go ahead to list your token right away.',
  'account.register_token_btn': 'List Token',
  'account.list_token': 'List Token',
  'account.withdraw_warning_XXX':
    'Due to increased demand, sending funds currently takes ~ XXX.',
  'account.withdraw_status_pending': 'Processing',
  'account.tansferred_1_ETH': '1 ETH Transferred',
  'account.transfer_status_sent': 'Sent',
  'account.transfer_status_received': 'Received',
  'account.th_me': 'Me',
  'account.th_tx_hash': 'Transaction Hash',
  'account.th_time': 'Time',
  'account.locked_order': 'Limit Order',
  Sending: 'Sending',
  'account.locked_claimable': 'Claimable',
  'account.locked_grid': 'Grid Strategy',
  'account.personal_sign_reason': 'Possible Reasons',
  'account.personal_sign_reason1':
    '1. MetaMask is connected to hardware wallet',
  'account.personal_sign_reason2': '2. MetaMask version is outdated',
  'account.personal_sign_reason3': '3. Others',
  'account.personal_sign_btn': 'Sign Again',
  'account.deposit_arrive_in_30s': 'Arrive in ~30 seconds',
  'account.deposit_arrive_in_30s_s': 'Arrive in ~ 30 seconds',
  'account.account_completed_time_XXX': 'Complete in  ~XXX',
  'account.search_result_no_token': 'Token cannot be found',
  'account.search_result_invalid_code': 'Invalid contract address',
  'account.search_result_not_listed': 'Token is currently not listed on DeGate',
  'account.search_result_tips_register':
    'You can enter the contract address in order to complete token listing',
  'account.search_result_not_find': 'Still unable to find?',
  'account.search_pair_tips3': 'No trading pair for the asset',
  'account.search_pair_tips3_add': 'Please add pair',
  'account.register_token': 'Permissionless Token Listing',
  'account.search_again': 'Search Again',
  'account.deposit_type': 'Method',
  'account.deposit_type_standard': 'Standard',
  'account.switch_account_tips': 'Switched to',
  'account.switch_account_tips_register': 'Please initialize first.',
  'account.initialize_success': 'Initialization Successful',
  'account.approve': 'Approve',
  'account.reset_USDT': 'Reset USDT Approval',
  'account.reset_USDT_tips':
    'USDT requires resetting approval when spending limits are too low.',
  'account.next_step': 'Next',
  'account.profit_total': 'Total Profit',
  'account.profit_history': 'Profit History',
  'account.tab_mining_rewards': 'Mining Rewards',
  'account.yield_total': 'Total Yield',
  'account.yield_24h': '24h Yield',
  'account.claimable': 'Claimable',
  'account.yield_history': 'Yield History',
  'account.total_grid_profit': 'Total Grid Profit',
  'account.grid_strategies': 'Grid Strategies',
  'account.total_rewards': 'Total Rewards',
  'account.rewards_24h': '24h Rewards',
  'account.rewards': 'Rewards',
  'menu.register_err':
    'Your address does not have any blockchain transaction record. Please complete an on-chain transaction and try again. For instance, perform a token transfer to your wallet.',
  'menu.reset_post_success_withOrders':
    'Reset for Asset Key initiated. All of your open orders and grid strategies have been canceled.',
  'menu.reset_post_success': 'Reset for Asset Key initiated.',
  'menu.reset_processing_title': 'Asset Key reset in progress',
  'menu.reset_processing_desc': 'Please wait for completion',
  'trade.choose_token': 'Choose Token',
  'trade.token_info': 'Token Info',
  'trade.token_address': 'Token Address',
  'trade.price_range_24h': '24h Price Range',
  'trade.vol_24h': '24h Volume',
  'trade.item_price_TOKEN': 'Price (TOKEN)',
  'trade.item_amount_TOKEN': 'Amount (TOKEN)',
  'trade.order_book_title': 'Order Book',
  'trade.order_book_total': 'Total',
  'trade.trade_history_title': 'Latest Trades',
  'trade.trade_history_time': 'Time',
  'trade.market_placeholder_price': 'Market Price',
  'trade.what_is_stop_limit': "What's Stop Limit",
  'trade.what_is_stop_limit_link': "What's Stop Limit >",
  'trade.placeholder_total': 'Total',
  'trade.more_settings': 'Settings',
  'trade.expire_in_tips':
    'The order will be automatically canceled after expiration.',
  'trade.period_day_s': 'd',
  'trade.period_hour_s': 'h',
  'trade.period_minute_s': 'm',
  'trade.period_err_input_tips': 'Please enter a valid number',
  'trade.post_only_label': 'Maker-Only',
  'trade.post_only_tips':
    'The Maker-Only mode ensures that only Maker orders enter the order book. If any part of the order can be filled as a taker order, then entire order will be returned. Orders in the Maker-Only mode do not incur any gas fee or trading fee.',
  'trade.post_only_fail_title': 'Unable to Create Order',
  'trade.post_only_fail_desc':
    'Please adjust the price or disable "Maker-Only" mode.',
  'trade.max_gas_fee_tips':
    'Max Gas Fee covers on-chain costs for trade settlements, paid by Takers and free for Makers. Excess fees are refunded.',
  'trade.auto': 'Auto',
  'trade.custom': 'Custom',
  'trade.enough_for_XX_trades': 'Enough for XX trades',
  'trade.gas_fee_per_trade': 'Gas fee per trade',
  'trade.gas_fee_per_trade_tips':
    "Takers incur gas fees per trade to facilitate on-chain settlement, with costs fluctuating based on the Ethereum network's conditions.",
  'trade.max_number_of_trades': 'Max number of trades',
  'trade.btn_buy_ETH': 'Buy ETH',
  'trade.btn_sell_ETH': 'Sell ETH',
  'trade.max_buy_fee_deducted_NUM': 'Gas fee deducted. Max is NUM.',
  'trade.notification_limit_order_title': 'Limit Order Placed',
  'trade.notification_stop_limit_order_title': 'Stop Limit Order Placed',
  'trade.err_price': 'Please enter price',
  'trade.err_amount_total': 'Please enter amount or total',
  'trade.err_amount': 'Please enter an amount',
  'trade.err_insufficientFee_title': 'Insufficient Gas Fee',
  'trade.err_insufficientFee_desc':
    'Please check your Max Gas Fee setting and your DeGate Balance.',
  'trade.cancel_order_success': 'Order Canceled',
  'trade.pair_favorite': 'Favorite',
  'trade.pair_search': 'Search token, contract address',
  'trade.pair_last_price': 'Price',
  'trade.pair_change': 'Change',
  'trade.url_parse_err_title': 'This pair does not exist.',
  'trade.risk_tips': 'Risk Warning',
  'trade.base_is_not_default_token_tips':
    'Verify the token contract address through official sources to avoid scams before trading.',
  'trade.chain_cancel': 'Cancel Order On-Chain',
  'trade.chain_cancel_no_need_tips':
    'This order does not need on-chain cancellation.',
  'trade.chain_cancel_success': 'Request sent',
  'trade.depth_empty': 'No orders yet',
  'trade.depth_empty_asks': 'No sell orders',
  'trade.depth_empty_bids': 'No buy orders',
  'trade.depth_empty_tips':
    'Market order failed due to insufficient open orders in order book',
  'trade.history_empty': 'No trades yet',
  'trade.err_price_stable': 'Price has been invalid. Please try again.',
  'trade.price_warning':
    'The price you entered has deviated from market price, please confirm before placing the order',
  'trade.order_value_tips':
    'Minimum order value is <b>QUOTE_A</b> or <b>BASE_A</b>, which is equivalent to MINUSD USD. Use market order to bypass this restriction.',
  'trade.order_value_tips_quote':
    'Minimum order value is <b>QUOTE_A</b>, which is equivalent to MINUSD USD. Use market order to bypass this restriction.',
  'trade.order_value_tips_stable_quote':
    'Minimum order value is <b>QUOTE_A</b>. Use market order to bypass this restriction.',
  'trade.system_limit': 'System limit exceeded',
  'trade.stop_limit_untriggered_tips':
    'Order has not been submitted to the orderbook, as stop price has not been reached.',
  'trade.stop_limit_triggered_tips_TIME':
    'Order has been submitted to the orderbook at TIME',
  'trade.flow_of_funds': 'flow of funds',
  'trade.flow_of_funds_tip2':
    'Your order has been placed. Order funds will go to your DeGate Balance, instead of your wallet balance.',
  'orders.show_current_pair_orders': 'Hide Other Pairs',
  'orders.orderHistory': 'Order History',
  'orders.th_time': 'Time',
  'orders.th_average_price': 'Avg Price',
  'orders.th_stop_price': 'Stop Price',
  'orders.th_limit_price': 'Limit Price',
  'orders.th_filled_price': 'Price',
  'orders.th_filled_amount': 'Filled',
  'orders.th_filled_total': 'Total',
  'orders.th_trade_reconciliation': 'Reconciliation',
  'orders.th_trade_reconciliation_tips':
    'Please note that because of the different calculation models used for matching on DeGate and settlement on-chain, there may be slight differences in the two calculation results. If and when this happens, the system will use the value on-chain as the standard and make up for any shortfalls in the DeGate Balance.',
  'orders.hide_cancelled_expired_orders': 'Hide canceled/expired',
  'orders.status_open': 'Open',
  'orders.status_pending': 'Pending',
  'orders.status_completed': 'Filled',
  'orders.status_completed_part': 'Partially Filled',
  'orders.status_expired': '\tExpired',
  'orders.detail_price': 'Average/Price',
  'orders.average_price': 'Average Price',
  'orders.detail_type': 'Order Type',
  'orders.detail_trade_fee': 'Trading Fee: ',
  'orders.gas_preAuth': 'Max Gas Fee: ',
  'orders.fee_reconciliation': 'Reconciliation: ',
  'orders.gas_paid': 'Paid Gas Fee: ',
  'orders.gas': 'Gas Fee: ',
  'orders.trades_N': 'Trades(N)',
  'orders.detail_filled_total': 'Total',
  'orders.detail_filled_detail': 'Trade Details',
  'orders.detail_filled_time': 'Time',
  'orders.order_maker_free': 'Maker fees free',
  'orders.openOrders_empty': 'No open orders',
  'orders.export_orders_1_year': 'Export order data of recent 1 year.',
  'orders.export_trades_1_year': 'Export trade data of recent 1 year.',
  'orders.export_data': 'Export Data',
  'orders.export': 'Export',
  'orders.export_processing': 'Processing, Please wait.',
  'orders.export_tips_100_percent':
    'File will be downloaded once progress reaches 100%',
  'orders.sign_to_view_balance': 'Sign to view balance',
  'orders.sign_to_view_history': 'Sign to view history',
  'orders.sign_to_view_security_options': 'Sign to view security options',
  'gridTrade.automatic_strategy': 'Auto',
  'gridTrade.manual_strategy': 'Manual',
  'gridTrade.placeholder_amount': 'Enter an amount',
  'gridTrade.low_price': 'Lower Limit',
  'gridTrade.high_price': 'Upper Limit',
  'gridTrade.initial_investment': 'Investment',
  'gridTrade.grid_levels_tips':
    'Used to determine the number of open orders within the price range.',
  'gridTrade.profit_per_grid': 'Profit per Grid',
  'gridTrade.profit_per_grid_tips':
    'An important parameter for the profitability of Grid Strategy. Profit per Grid = (Higher Price - Lower Price) / Lower Price. The higher and lower prices refer to the prices of two adjacent grid lines within the grid strategy.',
  'gridTrade.min_grid_volume_XXX_ETH': 'Amount Per Grid: Min is XXX ETH',
  'gridTrade.min_grid_volume_err':
    'Please increase investment or reduce number of grids',
  'gridTrade.grid_no_depth_tips_BASE_QUOTE':
    'The grid strategy cannot be created for this pair as there are insufficient orders in the order book.',
  'gridTrade.grid_to_spot_trade': 'Go to Spot',
  'gridTrade.grid_level_over_err': 'Please reduce the number of grids',
  'gridTrade.grid_prices_err': 'Please expand the price range',
  'gridTrade.grid_create_err': 'Please adjust the parameters and try again.',
  'gridTrade.tips_grid_profit':
    'Profits are directly credited into your DeGate Balance and are immediately available.',
  'gridTrade.tips_grid_balance_0_BASE':
    'The rise in market price has resulted in all orders under this grid strategy becoming buy orders. Hence, the current balance of BASE is now 0.',
  'gridTrade.tips_grid_balance_0_BASE_2':
    'The rise in market price has resulted in all orders under this grid strategy becoming buy orders. Further, some of these orders are partially filled. Hence, the current balance of BASE is >0.',
  'gridTrade.tips_grid_balance_0_QUOTE':
    'The decline in market price has resulted in all orders under this grid strategy becoming sell orders. Hence, the current balance of QUOTE is now 0.',
  'gridTrade.tips_grid_balance_0_QUOTE_2':
    'The decline in market price has resulted in all orders under this grid strategy becoming sell orders. Further, some of these orders are partially filled. Hence, the current balance of QUOTE is >0.',
  'gridTrade.grid_param_err': 'Please enter the grid strategy parameters',
  'gridTrade.tv_buy': 'Buy',
  'gridTrade.tv_sell': 'Sell',
  'gridTrade.tv_waiting': 'waiting',
  'gridTrade.chain_cancel_no_need_tips':
    'This grid strategy does not need on-chain cancellation.',
  'gridTrade.grid_over_max_number_err':
    'Maximum number of running grid strategies reached, unable to create new grid.',
  'gridTrade.preview_orders_in_graph': 'Show Orders',
  'gridTrade.greate_news': 'Great news:',
  'gridTrade.min_amount_required_XXX': 'Minimum XXX required',
  'gridTrade.highest_grid_apy': 'Highest Grid APY',
  'gridTrade.for_the_last_7_days': 'For the last 7 days',
  'gridTrade.min_investment': 'Min. Investment',
  'gridTrade.grid_need_XXX': '$XXX for grid',
  'gridTrade.mining_need_XXX': '$XXX for mining',
  'gridTrade.recommended_params_cannot_be_applied':
    'Recommended parameters cannot be applied due to insufficient investment. You can adjust them in the manual mode.',
  'gridTrade.copy_params_to_manual': 'Copy Parameters to Manual',
  'gridOrders.grid_recents': 'My Latest Trades',
  'gridOrders.th_created_time': 'Time Created',
  'gridOrders.grid_profit': 'Grid Profit',
  'gridOrders.grid_cancel': 'End',
  open_orders: 'Open Orders',
  'gridOrders.tab_history_orders': 'Filled Orders',
  'gridOrders.tab_trade_history': 'Trade History',
  'gridOrders.detail_current_balance': 'Current Balance',
  'gridOrders.detail_ending_balance': 'End Balance',
  'gridOrders.detail_ending_balance_tips':
    'The asset balance when the grid strategy is closed.',
  'gridOrders.detail_in_order_funds': 'In-Order Funds:',
  'gridOrders.detail_on_hold_funds':
    'On Hold Funds (from partially filled orders):',
  'gridOrders.detail_transactions': 'Number of Filled Orders',
  'gridOrders.detail_investment': 'Initial Investment',
  'gridOrders.detail_running_time': 'Duration',
  'gridOrders.detail_prices': 'Price Range',
  number_of_grids: 'Number of Grids',
  'gridOrders.detail_expire_time': 'Expire in',
  'gridOrders.detail_expire_time_tooltip':
    'Orders within this grid strategy will be canceled upon its expiration.',
  'gridOrders.detail_valid_period': 'Expiration Setting',
  'gridOrders.open_orders_sell': 'SELL',
  'gridOrders.open_orders_buy': 'BUY',
  'gridOrders.open_orders_index': '#',
  'gridOrders.open_orders_total': 'Total',
  'gridOrders.history_orders_filled': 'Filled:',
  'gridOrders.history_orders_price': 'Price:',
  'gridOrders.history_orders_time': 'Time',
  'gridOrders.history_orders_filled_price': 'Avg Price',
  'gridOrders.history_orders_filled_amount': 'Filled',
  'gridOrders.history_orders_filled_total': 'Total',
  'gridOrders.history_orders_profit_tips':
    'The profit comes from the price difference after a cycle of buying low and selling high. For example, after a grid order for buying 1 ETH at a price of 4000 USDC is filled, if the grid spacing is 50 USDC, the system will automatically place a new order at a price of 4050 USDC to sell 1 ETH. A 50 USDC profit will be gained when this order is also filled.',
  'gridOrders.history_orders_buy_flip_order_tips_PRICE':
    'Profit will be displayed after the buy order at PRICE is filled.',
  'gridOrders.history_orders_sell_flip_order_tips_PRICE':
    'Profit will be displayed after the sell order of PRICE is filled.',
  'gridOrders.m_history_orders_flip_order_tips_PRICE':
    'The order at PRICE will appear here when filled',
  'gridOrders.grid_cancel_title': 'End Grid Strategy',
  'gridOrders.grid_cancel_content':
    'All orders in this grid strategy will be canceled immediately.',
  'gridOrders.grid_cancel_content2':
    'You are currently mining with this Grid Strategy. If you end this Grid Strategy, you will forfeit all mining rewards and all associated grid orders will be canceled immediately.',
  'gridOrders.copy_grid_title':
    'The following grid strategy parameters will be copied',
  'gridOrders.copy_grid_btn': 'Copy to Panel',
  'gridOrders.copy_grid_success': 'Grid Strategy Copied',
  'gridOrders.grid_init_funds_XXX': 'Value of initial investment: $XXX',
  'gridOrders.grid_init_funds_tips':
    'APYs are computed based on the value of initial allocation at the time of the creation of the grid strategy.',
  'gridOrders.tab_m_trade': 'Trade',
  grid_apy: 'Grid APY',
  grid_apy_tips:
    'The annualized profit rate by grid trading only. Float profit excluded.',
  'gridOrders.tab_mining_profit': 'Mining APY',
  'gridOrders.tab_mining_profit_tips':
    'Annualized mining profits are calculated from the initial value and duration of the Grid Strategy.',
  'gridOrders.mining_rewards': 'Rewards:',
  'gridOrders.open_orders_empty_tips': 'Please wait while data is loading',
  'gridOrders.market_value': 'Market Value:',
  'gridOrders.market_value_details': 'Details',
  'gridOrders.fund_details': 'Fund Details',
  'gridOrders.m_in_order_funds': 'In-Order Funds',
  'gridOrders.m_in_order_funds_tips':
    'Total funds in all open orders under this grid strategy.',
  'gridOrders.m_on_hold_funds': 'On Hold Funds',
  'gridOrders.m_on_hold_funds_tips': 'Result of partially filled orders.',
  'gridOrders.initial_value': 'Initial Value',
  'mining.my_title': 'My Pools',
  'mining.index_desc':
    'Create Grid Strategy. Boost your grid profits with liquidity mining rewards.',
  'mining.apply': 'New Pool Application',
  'mining.claimable_rewards_box': 'Claimable Rewards',
  'mining.rewards_more': 'and more',
  'mining.tab_pools': 'Mining Pools',
  'mining.tab_my': 'My Mining Stats',
  'mining.pools_tab_live': 'Live',
  'mining.pools_tab_upcoming': 'Upcoming',
  'mining.pools_funds': 'Total TVL',
  'mining.pools_funds_tips':
    'Total value of grid orders that meet the minimum order value of $120.',
  'mining.pools_mining_funds': 'Mining TVL',
  'mining.mining_apr': 'APY',
  'mining.mining_apr_tips':
    'Annualized rate of return estimated from mining rewards and mining TVL.',
  'mining.view_rule_link': 'Mining Rules',
  'mining.pools_info_to_confirm': 'To Be Determined',
  'mining.pools_no_wait': 'No mining pools available',
  'mining.my_mining_funds': 'My Mining Funds',
  'mining.my_mining_rewards': 'My Mining Rewards',
  'mining.my_th_profit_token_price': 'Latest Price',
  'mining.my_th_total_rewards': 'All-Time Rewards',
  'mining.my_th_24h_rewards': '24h Rewards',
  'mining.my_grids': 'My Mining',
  'mining.only_show_mining_grids': 'Active Only',
  'mining.my_th_mining_status': 'Mining Status',
  'mining.status_framing': 'Active',
  'mining.status_over_price': 'Out of Price Range',
  'mining.status_over_price_tips':
    'This grid strategy is outside of the order book reward price range (highest buy price * 0.99 - lowest sell price *1.01)',
  'mining.status_over_price_tips_stable':
    'This grid strategy is outside of the order book reward price range (highest buy price - lowest sell price)',
  'mining.status_mining_over': 'Mining Ended',
  'mining.status_grid_closed': 'Strategy Ended',
  'mining.status_grid_expired': 'Strategy Expired',
  'mining.empty_no_faring_grids': 'No mineable grid strategy currently',
  'mining.go_mining_pool': 'Go to Mining Pool',
  'mining.go_mining': 'Start Mining',
  'mining.go_to_grid': 'To Grid Strategy',
  'mining.mining_help': 'Mining Guide',
  'mining.mining_available': 'Eligible',
  'mining.mining_available_tips': 'Order value criteria fulfilled',
  'mining.mining_unavailable': 'Ineligible',
  'mining.mining_partially_available': 'Partially Eligible',
  'mining.mining_unavailable_tips': 'Order value criteria not fulfilled',
  'mining.mining_criteria':
    'Grid orders that meet both the following criteria can receive mining rewards.',
  'mining.funding_criteria': 'Order Value Criteria',
  'mining.price_criteria': 'Order Price Criteria',
  'mining.price_criteria_tips':
    'Grid order price must fall within the reward price range, defined as (highest order book buy price * 0.99 - lowest order book sell price *1.01).',
  'mining.price_criteria_tips_stable':
    'Grid order price must fall within the reward price range (highest order book buy price - lowest order book sell price) for the running grid strategy.',
  'mining.mining_preview': 'Mining Preview',
  'mining.mining_tips_BV_BASE_QV_QUOTE':
    'Grid orders must be greater than BV BASE or QV QUOTE at time of strategy creation.',
  'mining.mining_tips_QV_QUOTE':
    'Grid orders must be greater than QV QUOTE at time of strategy creation.',
  'mining.mining_total_profit': 'Mining Rewards',
  'mining.mining_24h_profit': '24h Mining Rewards',
  'mining.profit_unable_display': 'N/A',
  'mining.mining_funds': 'Mining Funds',
  'mining.mining_funds_tips':
    'The total value of orders from all grid strategies that fulfill the mining order value criteria for this trading pair.',
  'mining.tab_mining_profit_details': 'Reward Details',
  'mining.tab_mining_orders': 'Mining Orders',
  'mining.th_rewards': 'Reward',
  'mining.th_rewards_origin': 'Reward Source',
  'mining.th_rewards_origin_tips':
    'Mining reward is received as the grid order price is within the reward price range of the order book (highest buy price * 0.99 ~ lowest sell price *1.01).',
  'mining.th_rewards_origin_tips_stable':
    'Mining reward is received as the grid order price is within the reward price range of the order book (highest buy price ~ lowest sell price).',
  'mining.th_rewards_price_range': 'Reward Price Range',
  'mining.th_rewards_price_range_tips_stable':
    'Grid Orders that fulfil the mining criteria during order placement will receive mining rewards if they fall within the reward price range (highest buy price ~ lowest sell price).',
  'mining.th_rewards_price_range_tips':
    'Grid Orders that fulfil the mining criteria during order placement will receive mining rewards if they fall within the reward price range (highest buy price * 0.99 ~ lowest sell price *1.01).',
  'mining.th_time': 'Time',
  'mining.plan_title': 'ETH/USDC Pool Details',
  'mining.phase_cur': 'Current Phase',
  'mining.phase_range_N_XX': 'Phase N (XX)',
  'mining.phase_index_N': 'Phase N',
  'mining.phase_reward': 'Daily Rewards',
  'mining.phase_to_release': 'To be announced',
  'mining.my_rewards': 'My Rewards',
  'mining.claimable_rewards': 'Available',
  'mining.locked_rewards': 'Locked',
  'mining.locker_rewards_tips':
    'Mining rewards can only be claimed after the Grid Strategy has been active for 12 hours.',
  'mining.claimed_success': 'Claim Successful',
  'mining.claimed_tips': 'Will be sent to you shortly via internal transfer',
  'mining.view_history': 'View Internal Transfer History',
  'mining.claimed_view_btn': 'Go Check',
  'mining.mining_plan': 'Mining Schedule',
  'mining.phase_unpublished': 'To be announced',
  'mining.all_pools': 'All Pools',
  'notification.limit_desc_SELL_BASE_QUOTE_AMOUNT_PRICE':
    'Sell AMOUNT BASE @ PRICE QUOTE',
  'notification.limit_desc_BUY_BASE_QUOTE_AMOUNT_PRICE':
    'Buy AMOUNT BASE @ PRICE QUOTE',
  'notification.stop_limit_desc_SELL_BASE_AMOUNT': 'Sell AMOUNT BASE',
  'notification.stop_limit_desc_BUY_BASE_AMOUNT': 'Buy AMOUNT BASE',
  'notification.cancel_grid_desc_PAIR_PRICES': 'PAIR: PRICES',
  'notification.cancel_market_desc_SELL_BASE_QUOTE_AMOUNT':
    'Sell AMOUNT BASE for QUOTE',
  'notification.cancel_market_desc_SELL_BASE_QUOTE_TOTAL':
    'Sell BASE for TOTAL QUOTE',
  'notification.cancel_market_desc_BUY_BASE_QUOTE_AMOUNT':
    'Buy AMOUNT BASE with QUOTE',
  'notification.cancel_market_desc_BUY_BASE_QUOTE_TOTAL':
    'Buy BASE with TOTAL QUOTE',
  'notification.cancel_limit': 'Limit order canceled',
  'notification.cancel_stop_limit': 'Stop limit order canceled',
  'notification.cancel_market': 'Market order canceled',
  'notification.cancel_grid': 'Grid strategy ended',
  'notification.cancel_limit_expired': 'Limit order expired',
  'notification.cancel_stop_limit_expired': 'Stop limit order expired',
  'notification.cancel_grid_expired': 'Grid strategy expired',
  'notification.cancel_limit_order_for_gas_desc':
    'Your order has run out of gas fee. It was partially filled with the remainder canceled.',
  'notification.cancel_limit_order_for_gas_filled_amount': 'Filled',
  'notification.cancel_limit_order_for_gas_amount': 'Amount',
  'notification.view_history_orders': 'View Order History',
  'notification.cancel_market_for_depth_title':
    'Order Partially Filled and Canceled',
  'notification.price_slippage_protection': 'Price Slippage Protection',
  'notification.price_slippage_protection_desc':
    'DeGate market orders auto-include 10% price slippage protection to limit losses during high volatility and low liquidity. Use limit orders to bypass this protection.',
  'notification.cancel_market_for_depth_warning':
    'DeGate market order introduces a price protection mechanism, enabling users to reduce losses in market situation with high price volatility and low liquidity. If you do not want to trigger the price protection mechanism, please use the limit order mode.',
  'notification.dca_plan_ended': 'DCA plan ended',
  'notification.cancel_dca_desc_PAIR': 'PAIR',
  'notification.trade_limit_partially': 'Limit order partially filled',
  'notification.trade_limit_filled': 'Limit order filled',
  'notification.trade_market_partially': 'Market order partially filled',
  'notification.trade_market_filled': 'Market order filled',
  'notification.trade_stop_limit_partially':
    'Stop limit order partially filled',
  'notification.trade_stop_limit_filled': 'Stop limit order filled',
  'notification.mobile_trade_filled_AMOUNT_TOKEN':
    'Order filled. AMOUNT TOKEN received.',
  'notification.mobile_trade_partially_AMOUNT_TOKEN':
    'Order partially filled. AMOUNT TOKEN received.',
  'info.overview': 'Overview',
  'info.accounts': 'Total Users',
  'info.pairs': 'Trading Pairs',
  'info.turnover': 'All Time Volume',
  'info.turnover_24': '24h Volume',
  'info.dg_supply': 'DG Circulating Supply',
  'info.top_movers_no_increased': 'No token increased in price within 24 hours',
  'info.top_movers_no_decreased': 'No token decreased in price within 24 hours',
  'info.top_pairs': 'Top Pairs',
  Pair: 'Pair',
  'info.th_change': '24h Change',
  'info.th_l_up_2': '+2% Depth',
  'info.th_l_down_2': '-2% Depth',
  'info.th_turnover_24': '24h Volume',
  'info.tvl': 'Total Value Locked',
  'm.home': 'Home',
  'm.grid': 'Grid',
  'm.browser_wallet': 'Browser Wallet',
  'm.choose_pair': 'Choose Pair',
  'm.orderBook_default': 'Default',
  'm.orderBook_bids': 'Buy Orders',
  'm.orderBook_asks': 'Sell Orders',
  'm.decimals': 'Decimal',
  'm.lowest_price_24h': '24h Low',
  'm.highest_price_24h': '24h High',
  'm.vol_24h': '24h Vol',
  'm.orderbook_buy': 'Buy',
  'm.orderbook_sell': 'Sell',
  'm.go_to_trade': 'Go to Trade',
  'm.choose_token': 'Choose a Token',
  'm.from_address': 'Sender Address',
  'm.to_address': 'Recipient Address',
  'm.transfer_send': 'Send',
  'm.transfer_receive': 'Receive',
  'm.my_grid': 'My Grid Strategy',
  'm.grid_profit_24': '24h Profit',
  'm.grid_item_trades_24': '24h Trades',
  'm.grid_profit_total': 'Total Profit',
  'm.grid_over_prices': 'Out of Price Range',
  'm.create_grid': 'Create Grid Strategy',
  'm.grid_history': 'History',
  'm.grid_empty': 'No active grid strategy',
  'm.grid_tutorial': 'Grid Tutorial',
  'm.grid_params_to_manual': 'Copy parameters to Manual',
  'm.balance_err': 'Insufficient balance. Available:',
  'm.preview_grid': 'Preview Orders',
  last_price: 'Last Price',
  'm.grid_desc':
    'Grid trading is a trading strategy that automates buying and selling within a defined range.',
  'm.view_tutorial': 'View Tutorial',
  'm.grid_profit_tips_sell':
    'Will be calculated when this sell order is fully filled.',
  'm.grid_profit_tips_buy':
    'Will be calculated when this buy order is fully filled.',
  'm.hot': 'Hot',
  'm.all': 'View All',
  'm.vol_24': '24h Vol',
  'm.transfer_t1': 'Internal',
  'm.transfer_t2': 'Transfer',
  'activity.th_date': 'Time',
  'activity.th_type': 'Type',
  'activity.th_fee': 'Fee',
  'activity.th_content': 'Content',
  'activity.type_register_token': 'Token Listing',
  'activity.type_register_pair': 'Adding Pair',
  'activity.type_pay_deposit': 'Deposit Settlement',
  'activity.type_reset_account': 'Reset Asset Key',
  on_chain_order_cancellation: 'On-Chain Order Cancellation',
  'activity.count_N': 'Count: N',
  'activity.order_desc_SELL_AMOUNT_BASE_PRICE_QUOTE':
    'SELL AMOUNT BASE @PRICE QUOTE',
  'activity.order_market_desc_SELL_AMOUNT_BASE': 'SELL AMOUNT BASE',
  'activity.reset_status_restting': 'Resetting',
  'activity.to_trade': 'Trade',
  'dca.dca_plan': 'DCA Plan',
  'dca.dca_explain': 'Dollar-cost Averaging',
  'dca.daily': 'Daily',
  'dca.weekly': 'Weekly',
  'dca.custom': 'Custom',
  'dca.every': 'Every ',
  'dca.amount_per_order': 'Amount per Order',
  'dca.price_limit': 'Price Limit',
  'dca.maximum_price': 'Maximum Price',
  'dca.minimum_price': 'Minimum Price',
  'dca.number_of_orders': 'Number of Orders',
  'dca.create_dca_plan': 'Create DCA Plan',
  'dca.max_gas_fee_per_order': 'Max Gas Fee per Order',
  'dca.maximum_plan_order_limit_reached':
    'The maximum number of plan orders has been reached.',
  'dca.end_time_should_be_set_after_the_current_time':
    'End Time should be set after the current time',
  'dca.please_enter_amount_per_order': 'Please enter Amount per Order',
  'dca.please_enter_maximum_price': 'Please enter Maximum Price',
  'dca.please_enter_minimum_price': 'Please enter Minimum Price',
  'dca.order_placement_failed_open_order_limit_exceeded':
    'Order placement failed: open order limit exceeded.',
  'dca.total': 'Total',
  'dca.filled': 'Filled',
  'dca.received': 'Received',
  'dca.time_to_end': 'Time to End',
  'dca.cancel_on_chain': 'Cancel On-chain',
  'dca.filled_amount': 'Filled/Amount',
  'dca.status_executed': 'Executed',
  'dca.status_scheduled': 'Scheduled',
  'dca.status_failed': 'Failed',
  'dca.order_cancled_by_user':
    'Order canceled because user ended the DCA plan.',
  'dca.order_cancled_by_access':
    'Order canceled because your access to DeGate is restricted.',
  'dca.order_cancled_by_gas':
    'Order placement failed due to insufficient gas fee.',
  'dca.order_cancled_by_order_book':
    'Order placement failed due to the absence of a matching order in the order book.',
  'dca.order_cancled_by_balance':
    'Order placement failed due to insufficient DeGate Balance.',
  'dca.order_cancled_by_min_value':
    'Order placement failed because minimum order value of $100 is not met.',
  'dca.order_cancled_by_system_error':
    'Order placement failed due to a system error.',
  'dca.chain_cancel_no_need_tips':
    'This DCA plan does not need on-chain cancellation.',
  'dca.end_dca_plan': 'End DCA Plan',
  'dca.all_orders_in_this_dca_plan_will_be_canceled_immediately':
    'All orders in this DCA plan will be canceled immediately.',
  'dca.no_active_dca_plan': 'No active DCA Plan',
  'dca.time_scheduled': 'Time Scheduled',
  'campaign.event_period': 'Event Period: ',
  'campaign.grid2401_time':
    'January 22, 2024, 20:00:00 - January 29, 2024, 20:00:00 (UTC+8)',
  'campaign.event_has_ended': 'The event has ended.',
  'campaign.current_apy': 'Current Annual Percentage Yield (APY)',
  'campaign.grid_strategy_income': 'Grid Strategy Income + Share of Prize Pool',
  'campaign.tvl_participating': 'TVL Participating',
  'campaign.share_of_tvl': 'Share of TVL',
  'campaign.my_profit': 'My Profit',
  'campaign.grid_strategy_profit': 'Grid Strategy Profit',
  'campaign.share_of_prize_pool': 'Share of Prize Pool',
  'campaign.grid_strategy_profit_has_been_added_to_your_available_balance':
    'Grid strategy profit has been added to your available balance.',
  'campaign.shared_income_from_usdc_prize_pool':
    'Shared income from USDC Prize Pool',
  'campaign.is_black_tips': 'You are not eligible to share in the prize pool.',
  'campaign.calculating': 'Calculating',
  'campaign.claim_after_end': 'Prize can be claimed at the end of event',
  'campaign.how_to_participate': 'How to Participate',
  'campaign.rule':
    'Create grid strategy and share In the prize pool proportionately.',
  'campaign.step1': 'Step 1',
  'campaign.step2': 'Step 2',
  'campaign.step3': 'Step 3',
  'campaign.grid2401_step1':
    'Get ready your ETH and USDC by adding funds or trading',
  'campaign.grid2401_step2_PAIR': 'Set up a grid strategy for PAIR as below',
  'campaign.grid2401_step2_desc1_pre': 'Price range: To be announced',
  'campaign.grid2401_step2_desc2_pre': 'Number of grids: To be announced',
  'campaign.copy_strategy': 'Copy strategy',
  'campaign.grid2401_step3':
    'After the end of event, you can claim your earnings on this event page. Please claim within 30 days of the end of event.',
  'campaign.what_is_grid': 'What is Grid Strategy',
  'campaign.notes': 'Please note before joining',
  'campaign.notes_1_title': 'Eligibility:',
  'campaign.notes_1_desc':
    'The grid strategy is eligible only if the price range and number of grids is exactly the same as required during the time of creation.',
  'campaign.notes_2_title': 'Limit:',
  'campaign.notes_3_title': 'Claim:',
  'campaign.notes_3_desc':
    'Prize claim will be available at the end of event and valid for claim within 30 days of event end.',
  'campaign.faq': 'FAQ',
  'campaign.grid2401_faq_1': '1. How are rewards calculated?',
  'campaign.grid2401_faq_2':
    '2. Where can I get help with questions on this event?',
  'campaign.grid2401_faq_3': '3. I hold USDT, how can I obtain ETH and USDC?',
  'campaign.grid2401_faq_4':
    '4. Do I need to pay a fee for transactions completed through the grid strategy?',
  'campaign.grid2401_faq_4_res':
    'In DeGate, all Maker orders are free. Orders generated by the grid strategy are all Maker orders, so setting up a grid strategy in DeGate is completely free.',
  'campaign.grid2401_faq_5':
    '5. Will my grid strategy still generate income after the event ends?',
  'campaign.grid2401_faq_5_res':
    'Yes, after the event ends, as long as the price is still within your grid strategy range, the strategy will continue to generate income. After the event, you can also adjust the parameters of your grid strategy to create a strategy more suited to your own preferences and continue to earn income.',
  'campaign.grid2401_faq_others': 'Other event details',
  'campaign.grid2401_faq_others_1':
    "1. Only a single wallet per user. If malicious sybil reward farming is detected, DeGate reserves the right to cancel a participant's rewards.",
  'campaign.grid2401_faq_others_2':
    '2. During the event, grids that are out of range will also be counted as part of the weightage calculation.',
  'campaign.grid2401_faq_others_3':
    '3. DeGate reserves the right to end the event early in extreme circumstances, e.g. market volatility.',
  'campaign.grid2401_faq_others_4':
    '4. Rewards not claimed within 30 days after the event ends will be forfeited.',
  'campaign.invest_max_5000': 'Invest Maximum of $5000',
  'campaign.invest_mininum': 'Invest Minimum',
  'airdrop.create_airdrop': 'Create Airdrop',
  'airdrop.important_note':
    'Important: Anyone can create airdrops without permission',
  'airdrop.my_airdrop': 'My Airdrops',
  'airdrop.time_limited': 'Time limited',
  'airdrop.no_airdrop': 'No airdrop yet',
  'airdrop.claim_airdrop': 'Claim Airdrop',
  'airdrop.recipients_number': 'No. of Recipients',
  'airdrop.total_amount': 'Total Amount',
  'airdrop.retrieve': 'Retrieve',
  'airdrop.unclaimed': 'Unclaimed',
  'airdrop.retrieve_successful': 'Retrieve Successful',
  'airdrop.claim_successful': 'Claim Successful',
  'airdrop.retrieve_unclaimed_airdrop': 'Retrieve Unclaimed Airdrop',
  'airdrop.airdrop_token': 'Airdrop Token',
  'airdrop.token_not_meet_criteria':
    'This token does not meet airdrop criteria',
  'airdrop.airdrop_list': 'Airdrop List',
  'airdrop.download_template': 'Download Template',
  'airdrop.click_or_drag_upload_list': 'Click or drag to upload list',
  'airdrop.validation_passed': 'Validated',
  'airdrop.must_earlier_than_end_time': 'Must be before end time',
  'airdrop.cannot_more_than_2_years_from_now':
    'Cannot be more than 2 years from now',
  'airdrop.cannot_parse_file':
    'Cannot parse the file. Please use the template.',
  'airdrop.format_requirement_not_met': 'Format requirement not met',
  'airdrop.view_error_repost': 'View Error Report',
  'airdrop.error_report': 'Error Report',
  'airdrop.line': 'Line',
  'airdrop.reason': 'Reason',
  'airdrop.duplicated_address': 'Duplicated address',
  incorrect_address_format: 'Incorrect address format',
  'airdrop.incorrect_amount_format': 'Incorrect amount format',
  'airdrop.airdrop_plan_created': 'Airdrop plan created',
  'airdrop.max_50000': 'Max 50000 addresses',
  'airdrop.upload_file_rule': 'Support CSV only.',
  'airdrop.to_check_airdrop_eligibility':
    'Complete initialization to view airdrops',
  'airdrop.complete_initialization_to_claim_airdrops':
    'Complete initialization to claim airdrops',
  'airdrop.complete_initialization_to_view_airdrops':
    'Complete initialization to view airdrops',
  'airdrop.you_are_eligible_for': 'You are eligible for:',
  'airdrop.and_more': 'and more',
  'airdrop.congratulations': 'Congratulations!',
  'airdrop.airdrop_fee': 'Airdrop Fee',
  'countdown.countdown_plan': 'Countdown Plan',
  'countdown.create_countdown_plan': 'Create Countdown',
  'countdown.my_countdown_plan': 'My Creations',
  'countdown.countdown_trading_pair': 'Countdown Trading Pair',
  'countdown.countdown_display': 'Countdown Display',
  'countdown.token_not_meet_criteria':
    'This token doesn’t meet the countdown criteria',
  'countdown.countdown_tips':
    'Countdown will display on the trading page for the selected trading pairs',
  'countdown.max_30_days': 'Cannot be more than 30 days from now',
  'countdown.review_countdown_plan': 'Review Countdown Plan',
  'countdown.countdown_fee': 'Countdown Fee',
  'countdown.countdown_plan_created': 'Countdown plan created',
  'countdown.trading_will_start_in': 'Trading will start in',
  'countdown.trading_will_start_at_YYYY': 'Trading will start at YYYY',
  'countdown.cannot_earlier_than_current_time': 'Cannot be before current time',
  'dca.price_limit_buy_tips':
    'Once enabled, your buy orders will only be executed at prices equal to or below the maximum price. This functionality is compatible with the Zero Fee feature.',
  'dca.price_limit_sell_tips':
    'Once enabled, your sell orders will only be executed at prices equal to or above the minimum price. This functionality is compatible with the Zero Fee feature.',
  'dca.zero_fee': 'Zero Fee',
  'dca.zero_fee_buy_tips':
    'With Zero Fee enabled, DCA orders will be processed as Maker-Only limit orders. Each buy price will be set at the highest bid price in the order book after placement. Be aware that your orders may not be filled immediately or potentially not at all.',
  'dca.zero_fee_sell_tips':
    'With Zero Fee enabled, DCA orders will be processed as Maker-Only limit orders. Each sell price will be set at the lowest ask price in the order book after placement. Be aware that your orders may not be filled immediately or potentially not at all.',
  'dca.order_canceled_post_only_buy_failed':
    "Order placement failed as the order book lacks buy orders, stopping the establishment of your order's buy price.",
  'dca.order_canceled_post_only_sell_failed':
    "Order placement failed as the order book lacks sell orders, stopping the establishment of your order's sell price.",
  start_time_cannot_before_current_time:
    'Start time cannot be before current time',
  start_time_must_before_end_time: 'Start time must be before end time',
  list_token: 'List Token',
  contract_address_does_not_exist: 'Contract address does not exist',
  token_listed: 'This token has been listed',
  XXX_is_listed: 'XXX is being listed',
  view_progress: 'View progress',
  pair_create_tips:
    'Trading pairs can be instantly added on DeGate without approval from any party.',
  base_token: 'Base Token',
  quote_token: 'Quote Token',
  existing_pair: 'Existing pair',
  trade_now: 'Trade Now',
  pair_XXX_added_successfully: 'XXX added successfully',
  qty_per_grid: 'Qty per Grid',
  grid_minimum_not_reached: 'Minimum not reached',
  total_profit: 'Total Profit',
  total_apy: 'Total APY',
  float_profit: 'Float Profit',
  grid_profit_24h: '24h Grid Profit',
  pnl: 'PnL',
  eligibility: 'Eligibility',
  rewards: 'Rewards',
  view_mining_statistics: 'View Mining Statistics',
  your_entry: 'Your entry',
  refunded: 'Refunded',
  large_price_spread: 'Large Price Spread',
  large_price_spread_tips:
    'The order book shows a large spread between the lowest sell and the highest buy prices, posing a risk of loss. Investing with Dual Asset mode is recommended.',
  continue_anyway: 'Continue Anyway',
  insufficient_order_book_liquidity_decrease_investment:
    'Insufficient order book liquidity. Decrease investment.',
  initial_buy: 'Initial Buy',
  closing_sell: 'Closing Sell',
  No: 'No',
  DCA_TRIGGER_FAIL_TIPS_PRICE_XXX:
    'DCA orders will fail if the price of <b>$XXX falls below $PRICE</b> at the time of execution.',
  zero_fee: 'Zero Fee',
  minimum_order_value_is_VALUE: 'Minimum order value is <b>$VALUE</b>.',
  Note: 'Note',
  Continue: 'Continue',
  estimated_apy: 'Estimated APY',
  based_on_data_from_last_7_days: 'Based on data from last 7 days',
  top_gainers_24h: '24h Top Gainers',
  top_losers_24h: '24h Top Losers',
  listed_tokens: 'Listed Tokens',
  vol: 'Vol',
};

export default en;
