const zhCN = {
  language: 'zh-CN',
  'kline.time_Line': '分时',
  'kline.time_1m': '1分钟',
  'kline.time_3m': '3分钟',
  'kline.time_5m': '5分钟',
  'kline.time_15m': '15分钟',
  'kline.time_30m': '30分钟',
  'kline.time_1H': '1小时',
  'kline.time_2H': '2小时',
  'kline.time_4H': '4小时',
  'kline.time_6H': '6小时',
  'kline.time_1D': '日线',
  'kline.time_1W': '周线',
  'kline.time_1M': '月线',
  'kline.tab_line': '走势图',
  'kline.tab_depth': '深度图',
  'kline.chartType_Bars': '美国线',
  'kline.chartType_Candles': 'K线图',
  'kline.chartType_Hollow_Candles': '空心K线图',
  'kline.chartType_Line': '线形图',
  'kline.chartType_Area': '面积图',
  'kline.chartType_Heikin_Ashi': '平均K线图',
  degate_account: 'DeGate账户',
  Trade: '交易',
  Order: '订单',
  Grid: '网格策略',
  Campaign: '活动',
  DCA: '定投',
  Advanced: '高级',
  Add: '划入',
  Add_Funds: '划入资金',
  eth_added_1: '1 ETH已划入',
  eth_sent_1: '1 ETH已发送',
  Send: '发送',
  Internal_Transfer: '内部转账',
  Miscellaneous: '其他',
  Bridge: '资产桥',
  Mining: '挖矿',
  Liquidity_Mining: '流动性挖矿',
  Analytics: '数据',
  Support: '帮助',
  Help: '帮助',
  Tips: '提示',
  Statistics: '业务统计',
  Coming_soon: '即将到来',
  Faucet: '领测试币',
  more: '更多',
  hide: '收起',
  change: '更换',
  'Wrong Network': '网络错误',
  avbl: '可用：',
  chain_1: 'Mainnet',
  chain_3: 'Ropsten',
  chain_4: 'Rinkeby',
  chain_5: 'Goerli',
  chain_42: 'Kovan',
  chain_42161: 'Arbitrum',
  chain_10: 'Optimism',
  insufficient_balance_AAA: '您钱包里的AAA余额不足。请检查后重试。',
  insufficient_balance: '余额不足',
  wallet_denied_sign: '你拒绝了消息签名。',
  common_err: '似乎出了点问题，请稍后重试',
  common_err_ledger_version:
    '发生错误。请确保您的Ledger Ethereum app已更新至1.9.10或更高版本，或稍后再试。',
  network_1: '以太坊主网',
  network_err: '网络异常，请稍后再试',
  rate_limit_err: '访问频率过高，请在1分钟后重试',
  error_InsufficientGasFunds: '您钱包内的Gas不足',
  notification_transaction_send: '已转账',
  view_on_etherscan: '在区块链浏览器查看',
  view_on_explorer: '查看地址',
  switch_network: '切换网络',
  switch_to_Arbitrum: '切换到Arbitrum网络以继续',
  switch_to_MAINNET_in_metamask: '请到Metamask切换至MAINNET',
  switch_to_MAINNET: '请切换至MAINNET',
  switch_network_in_walletconnect: '请到WalletConnect钱包切换网络',
  Retry: '重试',
  wallet_tips: '请到钱包内授权',
  wallet_ledger_tips: '请到Ledger硬件中授权',
  wallet_metamask_tips: '请到MetaMask授权',
  wallet_walletconnect_tips: '请到WalletConnect钱包授权',
  wallet_cancelled_tips: '您已取消签名',
  Close: '关闭',
  copied: '已复制',
  Details: '详情',
  view_details: '查看详情',
  Share: '分享',
  view_graph: '查看图示',
  Dismiss: '我再想想',
  Cancel: '取消',
  End: '关闭',
  End_grid: '关闭策略',
  Confirm: '确认',
  Cancel_all: '全部取消',
  cancel_all_tips: '是否要取消所有现货挂单',
  Submit: '提交',
  no_data: '没有数据',
  all_data_displayed: '已显示所有数据',
  no_data_within_90_days: '90天内无数据。',
  only_display_90_days: '仅显示最近90天数据',
  displayed_90_days: '已显示最近90天数据',
  only_data_beyond_90_days_trade:
    '90天之前的数据请点击「查看全部」后使用「导出数据」功能。',
  only_data_beyond_90_days_grid_detail: '暂不支持90天之前历史查询。',
  only_data_beyond_90_days_spot_history:
    '90天之前的数据请使用表格右上方「导出数据」功能。',
  View: '查看',
  service_unavailable_for_region_REGION: '该服务在REGION不可用',
  service_unavailable: '服务暂不可用',
  service_error: '请稍后重试',
  service_maintenance: '该功能维护中',
  connect_wallet: '连接钱包',
  switch_address: '切换地址',
  wallet_wc: '已连接WalletConnect',
  wallet_ledger: '已连接Ledger',
  register_dexAccount: '开通',
  deposit_ETH: '划入ETH',
  initialize: '初始化',
  initialization: '初始化',
  invalid_signature: '签名无效',
  possible_cause: '可能原因：',
  locale_time_error: '您的本地设备时间不准确。',
  authorization_mode: '授权模式',
  authorization_mode_standard: '免签名',
  authorization_mode_single_use: '单次签名',
  turn_on: '开启',
  turn_on_signature_free_mode: '开启免签名模式',
  signatre_free_mode: '免签名模式',
  turn_on_signature_free_mode_tips:
    '本模式下您可免签名下单。切换模式，请在交易按钮下方的“设置”中完成。',
  turn_on_signature_free_mode_tips_grid:
    '本模式下您可免签名创建网格策略。切换模式，请在交易按钮下方的“设置”中完成。',
  turn_on_signature_free_mode_tips_dca:
    '本模式下您可免签名创建定投计划。切换模式，请在交易按钮下方的“设置”中完成。',
  yes: '是',
  no: '否',
  free_mode_on: '免签名模式已开启',
  view_balance: '查看余额',
  delete_asset_key: '删除资产密钥',
  delete_asset_key_desc:
    '一旦您的浏览器中的资产密钥被删除，将会关闭免签名模式。',
  no_asset_key_tips: '您的浏览器中未找到资产密钥',
  turn_off_standard_mode: '并关闭免签名模式',
  reset_asset_key: '重置资产密钥',
  view_asset_key: '查看资产密钥',
  lock_success: '资产密钥已删除',
  reset: '重置资产私钥',
  delete: '删除',
  withdraw_ETH: '发送ETH',
  transfer_ETH: '内部转账ETH',
  history: '历史',
  view_history: '查看历史',
  internal_transfer: '内部转账',
  assets_record_link: '资产记录',
  other: '其他',
  login_success: '已连接至钱包',
  Account: '账户',
  Address: '地址',
  Disconnect: '断开连接',
  copy_address: '复制地址',
  copy_grid: '复制策略',
  Copy: '复制',
  btn_search: '搜索',
  btn_reset: '重置',
  btn_confirm: '我知道了',
  btn_max: '最大',
  btn_ok: '好的',
  spot_trade: '现货',
  grid_trade: '网格',
  err_balance_title: '下单失败',
  err_balance_content: '账户可用余额不足，请确认后重新创建',
  order_failed: '下单失败',
  insufficient_order_value: '订单价值不足',
  grid_failed: '网格策略创建失败',
  err_eth_gas: '以太坊网络严重拥堵',
  err_insufficient_balance_TOKEN1: 'TOKEN1余额不足',
  err_insufficient_balance_TOKEN1_TOKEN2: 'TOKEN1和TOKEN2余额不足',
  please_add_funds_before_ordering: '下单前请先向DeGate余额划入资金',
  err_balance_content_spot: '余额不足，下单失败',
  err_balance_content_grid: '余额不足，网格策略创建失败',
  trade_min_volume_tips_XXX: '最少为XXX',
  grid_min_volume_tips: '每格数量不满足最小下单量要求，请重新下单',
  trade_risk_orders_tips: '下单失败，当前挂单过多',
  gas_token_tips: '选择矿工费代币',
  add_favorite_tooltip: '加入自选',
  remove_favorite_tooltip: '移出自选',
  expire_tips_X: '订单将于X失效',
  today: '今天',
  now: '现在',
  time_D_day: 'D天',
  time_D_day_H_hour: 'D天H小时',
  time_H_hour_M_minute: 'H小时M分钟',
  time_M_minute_S_second: 'M分钟S秒',
  time_S_second: 'S秒',
  around: '约',
  time_now: '刚刚',
  time_before: '前',
  time_before_ago: '前',
  time_1_minute: 'M分钟',
  time_1_hour: '1小时',
  time_1_day: '1天',
  time_1_year: '1年',
  time_M_minutes: 'M分钟',
  time_M_m: 'M分钟',
  time_H_hours: 'H小时',
  time_H_h: 'H小时',
  time_D_days: 'D天',
  time_Y_years: 'Y年',
  time_Y_y: 'Y年',
  fee_change_tips: '价格已更新',
  no_pairs: '没有交易对',
  register_new_pair: '添加新交易对',
  register_pair: '添加交易对',
  add_pair: '添加交易对',
  tips_hide_forever: '下次不再显示',
  token: '币种',
  action: '操作',
  more_actions: '更多操作',
  gas_fee: '矿工费',
  'orders.detail_gas': '实际矿工费',
  trade_fee: '手续费',
  about_degate: '关于DeGate',
  metrics: '数据统计',
  fees: '费率',
  document: '文档',
  join_us: '加入我们',
  feedback: '反馈',
  email_optional: '电子邮件地址（可选）',
  Upload: '上传',
  feedback_upload_tip: '请输入反馈内容，可拖动文件添加附件',
  feedback_upload_tip_mobile: '请输入反馈内容',
  image_upload_tip: '松开后添加',
  feedback_success: '您的反馈振聋发聩！',
  feedback_success_2: '非常感谢',
  feedback_failed: '提交失败，请稍后重试',
  image_upload_rule_1: '仅支持PNG, JPG, JPEG格式的附件',
  image_upload_rule_2: '单个不超过20MB',
  image_upload_rule_2_3: '单个不超过20MB，最多5个',
  no_pair: '未找到交易对',
  no_token: '未找到此币种',
  choose_base_token: '选择币种',
  choose_quote_token: '选择货币',
  get_test_token: '领测试币',
  faucet: '测试币',
  expire_in: '有效期',
  expire_in_empty_err: '请设置有效期',
  go_back: '返回',
  max_XXX: '最大为XXX',
  min_XXX: '最小为XXX',
  fill_in: '填入',
  my_balance: '我的余额',
  deGate_insufficient_fees: 'DeGate余额不足以支付矿工费',
  wallet_balance: '钱包余额',
  your_wallet_balance: '我的钱包余额',
  degate_balance: 'DeGate余额',
  wallet_insufficient_fees: '钱包余额不足',
  wallet_insufficient_balance: '钱包余额不足',
  insuffficient_wallet_balance: '钱包余额不足',
  degate_insufficient_balance: '可用余额不足',
  open_discord: '去Discord社区',
  err_valid_until: '请调整当前设备本地时间至标准时间',
  tips_gas: '执行交易上链所需的矿工费将会从您的DeGate余额扣除',
  maker_free: '挂单免费',
  trading_fee_rate: '手续费率',
  Free: '免费',
  stop_service_1: '站点正在维护',
  stop_service_2: '预计恢复时间',
  stop_upgrade: '新版本测试网正在迁移中',
  stop_trading_1: '系统升级中',
  stop_trading_2: '交易功能暂停使用',
  sell: '卖出',
  buy: '买入',
  SELL: '卖出',
  BUY: '买入',
  Sell: '卖出',
  Buy: '买入',
  sell_order: '卖单',
  buy_order: '买单',
  edit: '修改',
  status_processing: '进行中',
  status_processed: '等待处理',
  status_pending: '等待入块',
  status_confirming: '确认中',
  status_success: '成功',
  status_completed: '已完成',
  status_failed: '失败',
  status_speeding_up: '加速中',
  status_canceling: '取消中',
  status_canceled: '已取消',
  in_progress: '进行中',
  limit_order: '限价',
  market_order: '市价',
  stop_limit_order: '止盈止损',
  balance: '余额',
  empty_connect: '请先连接钱包',
  empty_register: '请先完成初始化',
  empty_months3: '最近3个月无数据',
  show_months3: '仅展示3个月内的数据',
  view_all: '查看全部',
  D1: '1天',
  D5: '5天',
  M1: '1月',
  M3: '3月',
  M6: '6月',
  YTD: 'YTD',
  Y1: '1年',
  all: '全部',
  view_more: '查看更多',
  paste: '粘贴',
  clear: '清除',
  total: '总计',
  amount: '数量',
  order_amount: '订单数量',
  price: '价格',
  order_total: '订单金额',
  filledAmount: '成交数量',
  tradeFilledTotal: '成交金额',
  orderFilledTotal: '成交额',
  filledAmount_amount: '已成交/订单数量',
  profit: '收益',
  incompatible_token: '该代币的技术规格与DeGate协议不兼容。',
  next: '前往',
  token_not_verified: '未验证',
  token_not_verified_tips:
    '合约地址、图标和代币名未经验证。请检查合约地址是否来自官方渠道，以避免诈骗。',
  token_verified: '已验证',
  token_verified_tips: '合约地址、图标和代币名是互相匹配的。',
  arrival_time: '到账时间',
  deposit_tips_region:
    '请注意：您正在从REGION访问DeGate，资金划入后无法交易和内部转账。',
  complete_time: '完成时间',
  unable_to_initialize: '无法初始化',
  filter_base: '币种',
  filter_quote: '货币',
  filter_type: '类型',
  filter_role: '角色',
  option_maker: 'Maker',
  option_taker: 'Taker',
  start_data: '开始日期',
  end_data: '结束日期',
  added_to_favorites: '成功加入自选',
  removed_to_favorites: '移出自选成功',
  show_recents_50: '已显示最近50条数据',
  terms_of_service: '用户协议',
  tips_small_unfilled:
    '由于系统设计精度原因，极小量未成交部分已退回您的DeGate余额',
  notification: '通知',
  server_message_SystemRecovery:
    '系统故障恢复后，您的部分订单状态发生改变，请知悉',
  learn_more: '了解更多',
  connect_ledger: '连接Ledger',
  ledger_disconnect:
    "Failed to execute 'transferOut' on 'USBDevice': The device was disconnected.",
  gas_fee_expired: '矿工费已过期，请重新提交',
  scroll_down_to_refresh: '下拉刷新',
  release_to_refresh_immediately: '松开立即刷新',
  no_more: '已经全部加载完毕',
  loading: '正在加载...',
  force_withdrawing_token_tips:
    '正在处理您的强制提现请求，所以无法完成当前操作。',
  speed_up: '加速',
  transaction_submitted: '交易已提交',
  tx_speed_up: '加速交易',
  tx_cancel: '取消交易',
  none: '无',
  Language: '语言',
  page: '/页',
  go_to: '跳至',
  icon_indicators: '技术指标',
  icon_back: '回退',
  icon_forward: '前进',
  icon_full_screen: '全屏',
  icon_exit_full_screen: '退出全屏',
  icon_buy_sell_orders: '买卖盘',
  icon_buy_orders: '买盘',
  icon_sell_orders: '卖盘',
  icon_enable: '点击打开',
  icon_disable: '点击关闭',
  icon_copy: '复制地址',
  icon_view_explorer: '区块链浏览器查看',
  icon_display_by_profit: '按收益展示',
  icon_display_by_time: '按时间顺序展示',
  icon_switch: '切换',
  eth_code_tips: '以太坊原生代币，无合约地址',
  TBD: '待定',
  go_to_discord: '或者去Discord创建工单',
  release: '版本号：',
  security: '安全',
  colon: '：',
  zero_balance: '零余额',
  ledger_app_version_tips:
    '为了查看待签名消息，请升级您的Ledger Ethereum app至v1.9.19或更高',
  ledger_contract_data_tips:
    '请在Ethereum app设置中开启Blind Signing/Contract Data',
  input_auto_corrected_tooltips: '超过了最大位数限制，您的输入已被自动修改',
  maximum_decimal_reached: '超出最大小数位',
  verify_ownership: '验证身份',
  enable_trading: '开启交易',
  learn_more_about_signatures_link: '了解签名请求 >',
  learn_more_about_signatures: '了解签名请求',
  sign: '去签名',
  sign_step1: '请到钱包内签名',
  sign_step2: '完成第二次签名',
  not_now: '暂不',
  view_on_block_explorer: '区块链浏览器查看\t',
  view_in_history: '去历史记录查看',
  continue_to_place_order: '继续下单',
  Save: '保存',
  sign_to_view: '签名后查看',
  available_degate_balance: '可用DeGate余额',
  Back: '返回',
  token_has_not_listed: '该币种还未上架DeGate',
  list_now: '立即上币',
  spread_15: '价差 >15%',
  connected: '已连接',
  self_list_token: '自主上币',
  claim_REBASE: '领取REBASE',
  time: '时间',
  time_updated: '更新时间',
  show_in_X_m: '约X分钟后显示',
  max_gas: '最大矿工费',
  total_required: '共需',
  Required: '必填',
  available_balance: '可用余额',
  please_add_funds: '请先向DeGate余额划入资金',
  Side: '方向',
  pending: '待确认',
  active: '运行中',
  ended: '已关闭',
  name: '名称',
  yield: '分红',
  time_created: '创建时间',
  time_ended: '结束时间',
  frequency: '频率',
  chain_cancel: '链上取消',
  status: '状态',
  status_chainCancelProgressing: '正在链上取消',
  status_chainCancelCompleted: '已链上取消',
  filled_total: '已成交/总金额',
  start_time: '开始时间',
  end_time: '结束时间',
  Summary: '摘要',
  Orders: '订单',
  Tutorial: '教程',
  Earn: '赚币',
  top_winner_24h: '24小时冠军',
  ID: '序号',
  Select: '选择',
  Create: '创建',
  Review: '预览',
  Airdrop: '空投',
  Countdown: '首发',
  Day: '天',
  Hour: '小时',
  Minute: '分钟',
  Second: '秒',
  Days: '天',
  Hours: '小时',
  Minutes: '分钟',
  Seconds: '秒',
  Claim: '领取',
  Expired: '已过期',
  Claimed: '已领取',
  Welcome: '欢迎',
  gas_tips_for_amount_exceed_6_digits:
    '成交的数量超过6位数字限制，因此需支付额外费用',
  input_auto_corrected_minStep_tips: '您的输入已被自动修改，以符合最小精度',
  order_max_limit: '已超出最大限制',
  order_min_limit: '已超出最小限制',
  order_faild_min_limit: '下单失败：已超出最小限制',
  order_faild_max_limit: '下单失败：已超出最大限制',
  disconnect_m: '断开',
  'account.account_manage': '账户安全',
  'account.account_manage_more': '关于授权模式和资产密钥 >',
  'account.what_is_asset_key': '关于授权模式和资产密钥',
  'account.total_value': '总资产',
  'account.hide_small_balances': '隐藏小额资产',
  'account.add_to_metamask': '添加币种到钱包',
  'account.assets_balance_total': '全部',
  'account.assets_balance_available': '可用',
  'account.assets_market': '市值',
  'account.transfer_to_degate_balance': '划转至DeGate余额',
  'account.search_tokens': '搜索币种',
  'account.deposit_title':
    '充值资产会被存入您在DeGate的去中心化账户，完全由您掌控。',
  'account.deposit_tips': '划入的资金仍由您完全掌控',
  'account.deposit_confirm_btn': '划入资金',
  'account.deposit_approved_btn': '已授权',
  'account.deposit_1_ETH': '向DeGate余额划入1 ETH',
  'account.deposit_status_pending': '等待入块',
  'account.deposit_status_pay_pending': '待支付',
  'account.deposit_status_pay_waiting': '付费交易待打包',
  'account.deposit_status_pay_confirming': '付费入账确认中',
  'account.deposit_tips_block': '等待交易入块',
  'account.deposit_status_pay_btn': '去付费',
  'account.pay_deposit_warning': '划入资金可能需要支付额外的矿工费',
  'account.pay_deposit_warning_tips':
    '资金划入产生协议运行成本，这部分补贴当前已达上限，用户可能需要自行承担。',
  'account.deposit_pending_tips': '如果等待时间超过5分钟，请去钱包加速交易',
  'account.deposit_pending_tips_ledger': '如果等待时间超过5分钟，请加速交易',
  'account.deposit_contract_tips_over_AMOUNT': '金额超过AMOUNT美元需要高级方式',
  'account.deposit_contract_tips_only_all': '暂时仅支持高级资金划入方式',
  'account.suggest_100': '建议≥$100',
  'account.suggest_100_tips': '下限价单建议金额大于$100',
  'account.deposit_failed': '交易失败',
  'account.deposit_failed_tips': '划入资金的链上交易已失败',
  'account.payment_due': '等待付费入账',
  'account.payment_due_tips':
    '需要额外支付费用才能将本次划入资金计入您的DeGate余额',
  'account.register_token_code_placeholder': '输入合约地址',
  'account.register_token_code': '合约地址',
  'account.register_token_symbol': '代币',
  'account.register_token_check': '查看上币进度',
  'account.register_token_code_err_added': '正在上架该币种',
  'account.register_token_next_step': '下一步',
  'account.register_token_tips1': '上币无需审核，您可以在链上立即完成上币',
  'account.register_token_btn': '立即上币',
  'account.list_token': '上架',
  'account.withdraw_warning_XXX': '由于协议繁忙，发送资产现在大约需要XXX',
  'account.withdraw_status_pending': '处理中',
  'account.tansferred_1_ETH': '1 ETH 已转出',
  'account.transfer_status_sent': '已发送',
  'account.transfer_status_received': '已接收',
  'account.th_me': '我',
  'account.th_tx_hash': '交易号',
  'account.th_time': '时间',
  'account.locked_order': '限价挂单',
  Sending: '正在发送',
  'account.locked_claimable': '待领取',
  'account.locked_grid': '网格策略挂单',
  'account.personal_sign_reason': '可能原因',
  'account.personal_sign_reason1': '1. Metamask连接了硬件钱包',
  'account.personal_sign_reason2': '2. Metamask版本过低',
  'account.personal_sign_reason3': '3. 其他原因',
  'account.personal_sign_btn': '重新签名',
  'account.deposit_arrive_in_30s': '约30秒到账',
  'account.deposit_arrive_in_30s_s': '到账时间约30秒',
  'account.account_completed_time_XXX': '约XXX到账',
  'account.search_result_no_token': '找不到此资产',
  'account.search_result_invalid_code': '合约地址不存在',
  'account.search_result_not_listed': '此资产还未上线DeGate',
  'account.search_result_tips_register': '您可以输入合约地址立即完成上币',
  'account.search_result_not_find': '还是没找到？',
  'account.search_pair_tips3': '此资产还没有交易对',
  'account.search_pair_tips3_add': '请先添加',
  'account.register_token': '免审核上币',
  'account.search_again': '重新搜索\t',
  'account.deposit_type': '划入方式',
  'account.deposit_type_standard': '标准',
  'account.switch_account_tips': '已切换至',
  'account.switch_account_tips_register': '请先初始化账户',
  'account.initialize_success': '初始化成功',
  'account.approve': '授权',
  'account.reset_USDT': '重置USDT授权',
  'account.reset_USDT_tips': 'USDT授权额度不够时需要先重置授权。',
  'account.next_step': '下一步',
  'account.profit_total': '总收益',
  'account.profit_history': '收益历史',
  'account.tab_mining_rewards': '挖矿奖励',
  'account.yield_total': '总分红',
  'account.yield_24h': '24小时分红',
  'account.claimable': '可领取',
  'account.yield_history': '分红历史',
  'account.total_grid_profit': '网格总收益',
  'account.grid_strategies': '网格策略',
  'account.total_rewards': '挖矿总奖励',
  'account.rewards_24h': '24小时挖矿奖励',
  'account.rewards': '奖励',
  'menu.register_err':
    '您的地址没有任何区块链操作记录，请完成一笔链上操作后重试，例如：转入任意数量的资金。',
  'menu.reset_post_success_withOrders':
    '开始重置资产密钥，所有进行中订单和网格策略已被取消',
  'menu.reset_post_success': '开始重置资产密钥',
  'menu.reset_processing_title': '正在重置资产密钥',
  'menu.reset_processing_desc': '请等待完成后再操作',
  'trade.choose_token': '选择币种',
  'trade.token_info': '代币信息',
  'trade.token_address': '代币信息',
  'trade.price_range_24h': '24小时价格区间',
  'trade.vol_24h': '24小时量',
  'trade.item_price_TOKEN': '价格(TOKEN)',
  'trade.item_amount_TOKEN': '数量(TOKEN)',
  'trade.order_book_title': '订单簿',
  'trade.order_book_total': '合计',
  'trade.trade_history_title': '最新成交',
  'trade.trade_history_time': '时间',
  'trade.market_placeholder_price': '市价',
  'trade.what_is_stop_limit': '什么是止盈止损',
  'trade.what_is_stop_limit_link': '什么是止盈止损 >',
  'trade.placeholder_total': '成交额',
  'trade.more_settings': '设置',
  'trade.expire_in_tips': '订单到期后将被自动取消',
  'trade.period_day_s': '天',
  'trade.period_hour_s': '小时',
  'trade.period_minute_s': '分钟',
  'trade.period_err_input_tips': '请输入有效数字',
  'trade.post_only_label': 'Maker-Only',
  'trade.post_only_tips':
    'Maker-Only模式确保只以Maker订单进入订单簿。如果订单任何部分会以Taker订单成交，则整个订单会被退回。Maker-Only模式下免矿工费和手续费。',
  'trade.post_only_fail_title': '无法创建订单',
  'trade.post_only_fail_desc': '请调整价格或关闭Maker-Only',
  'trade.max_gas_fee_tips':
    '矿工费用于支付交易的上链结算。此费用由Taker支付，Maker免费。多余的费用会被退还。',
  'trade.auto': '自动',
  'trade.custom': '手动',
  'trade.enough_for_XX_trades': '足够成交 XX 笔',
  'trade.gas_fee_per_trade': '单次成交矿工费',
  'trade.gas_fee_per_trade_tips':
    'Taker按每笔成交支付矿工费，用以完成链上结算。矿工费随以太坊网络情况波动。',
  'trade.max_number_of_trades': '最大成交次数',
  'trade.btn_buy_ETH': '买入ETH',
  'trade.btn_sell_ETH': '卖出ETH',
  'trade.max_buy_fee_deducted_NUM': '已减去矿工费，最多买入NUM',
  'trade.notification_limit_order_title': '限价单已下单',
  'trade.notification_stop_limit_order_title': '止盈止损单已下单',
  'trade.err_price': '请输入价格',
  'trade.err_amount_total': '请输入数量或成交额',
  'trade.err_amount': '请输入数量',
  'trade.err_insufficientFee_title': '矿工费不足',
  'trade.err_insufficientFee_desc': '请检查最大矿工费设置和您的DeGate余额。',
  'trade.cancel_order_success': '订单已取消',
  'trade.pair_favorite': '自选',
  'trade.pair_search': '搜索币种、合约地址',
  'trade.pair_last_price': '最新价',
  'trade.pair_change': '涨跌',
  'trade.url_parse_err_title': '该交易对不存在',
  'trade.risk_tips': '风险提示',
  'trade.base_is_not_default_token_tips':
    '在交易前请通过官方渠道验证代币合约地址，以避免欺诈。',
  'trade.chain_cancel': '链上取消订单',
  'trade.chain_cancel_no_need_tips': '此订单无需链上取消',
  'trade.chain_cancel_success': '请求已发送',
  'trade.depth_empty': '暂无订单',
  'trade.depth_empty_asks': '没有卖单',
  'trade.depth_empty_bids': '没有买单',
  'trade.depth_empty_tips': '由于订单簿挂单不足，市价单下单失败',
  'trade.history_empty': '暂无成交',
  'trade.err_price_stable': '价格已失效，请重试',
  'trade.price_warning': '您输入的价格已偏离市场价，请确认后再下单',
  'trade.order_value_tips':
    '最小订单价值为<b>QUOTE_A</b>或<b>BASE_A</b>，相当于MINUSD美元。市价单可免于此限制。',
  'trade.order_value_tips_quote':
    '最小订单价值为<b>QUOTE_A</b>，相当于MINUSD美元。市价单可免于此限制。',
  'trade.order_value_tips_stable_quote':
    '最小订单价值为<b>QUOTE_A</b>。市价单可免于此限制。',
  'trade.system_limit': '已超出系统限制',
  'trade.stop_limit_untriggered_tips':
    '由于未达到触发价，此订单还没有提交至订单簿',
  'trade.stop_limit_triggered_tips_TIME': '此订单于TIME提交至订单簿',
  'trade.flow_of_funds': '资金流向',
  'trade.flow_of_funds_tip2':
    '下单成功。订单资金会计入您的DeGate余额，而不是您的钱包余额。',
  'orders.show_current_pair_orders': '仅显示本交易对',
  'orders.orderHistory': '历史订单',
  'orders.th_time': '时间',
  'orders.th_average_price': '平均价格',
  'orders.th_stop_price': '触发价',
  'orders.th_limit_price': '委托价',
  'orders.th_filled_price': '成交价格',
  'orders.th_filled_amount': '成交数量',
  'orders.th_filled_total': '成交额',
  'orders.th_trade_reconciliation': '对账修正',
  'orders.th_trade_reconciliation_tips':
    '由于DeGate撮合和链上结算采用了不同的计算模式，这两个计算结果之间可能存在细微的数值差异。 如果发生这种情况，系统将以链上数值为准来补上DeGate余额的不足。',
  'orders.hide_cancelled_expired_orders': '隐藏取消/过期',
  'orders.status_open': '进行中',
  'orders.status_pending': '待确认',
  'orders.status_completed': '已成交',
  'orders.status_completed_part': '部分成交',
  'orders.status_expired': '已过期',
  'orders.detail_price': '均价/价格',
  'orders.average_price': '均价',
  'orders.detail_type': '订单类型',
  'orders.detail_trade_fee': '手续费：',
  'orders.gas_preAuth': '最大矿工费：',
  'orders.fee_reconciliation': '对账修正：',
  'orders.gas_paid': '矿工费已支付：',
  'orders.gas': '矿工费：',
  'orders.trades_N': '成交(N)',
  'orders.detail_filled_total': '成交额',
  'orders.detail_filled_detail': '成交明细',
  'orders.detail_filled_time': '时间',
  'orders.order_maker_free': 'Maker方免费',
  'orders.openOrders_empty': '没有当前订单',
  'orders.export_orders_1_year': '导出最近1年订单数据',
  'orders.export_trades_1_year': '导出最近1年成交数据',
  'orders.export_data': '导出数据',
  'orders.export': '导出',
  'orders.export_processing': '正在处理，请耐心等候',
  'orders.export_tips_100_percent': '进度100%后会自动下载文件',
  'orders.sign_to_view_balance': '签名以查看余额',
  'orders.sign_to_view_history': '签名以查看历史',
  'orders.sign_to_view_security_options': '签名以查看安全选项',
  'gridTrade.automatic_strategy': '一键创建',
  'gridTrade.manual_strategy': '手动创建',
  'gridTrade.placeholder_amount': '请输入数量',
  'gridTrade.low_price': '最低价格',
  'gridTrade.high_price': '最高价格',
  'gridTrade.initial_investment': '投资额',
  'gridTrade.grid_levels_tips': '用于确定价格区间内的订单数量',
  'gridTrade.profit_per_grid': '每格收益',
  'gridTrade.profit_per_grid_tips':
    '这是网格策略盈利性的一个重要参数。每个网格的利润 = (较高价格 - 较低价格) / 较低价格。较高和较低价格指的是网格策略中两条相邻网格线的价格。',
  'gridTrade.min_grid_volume_XXX_ETH': '每格数量最少为XXX ETH',
  'gridTrade.min_grid_volume_err': '请增加投资额或减少网格数',
  'gridTrade.grid_no_depth_tips_BASE_QUOTE':
    '无法创建网格策略，因为此交易对挂单不够。',
  'gridTrade.grid_to_spot_trade': '去现货交易',
  'gridTrade.grid_level_over_err': '请减少网格数量',
  'gridTrade.grid_prices_err': '请扩大价格区间',
  'gridTrade.grid_create_err': '无法创建网格，请调整参数后重试',
  'gridTrade.tips_grid_profit': '收益直接计入DeGate可用余额',
  'gridTrade.tips_grid_balance_0_BASE':
    '市场价上涨导致网格策略下均为买单，因此BASE当前余额为0。',
  'gridTrade.tips_grid_balance_0_BASE_2':
    '市场价上涨导致网格策略下均为买单，而这些买单存在部分成交的情况，因此导致BASE当前余额不为0。',
  'gridTrade.tips_grid_balance_0_QUOTE':
    '市场价下跌导致网格策略下均为卖单，因此QUOTE当前余额为0。',
  'gridTrade.tips_grid_balance_0_QUOTE_2':
    '市场价下跌导致网格策略下均为卖单，而这些卖单存在部分成交的情况，因此导致QUOTE当前余额不为0。',
  'gridTrade.grid_param_err': '请完整输入网格策略参数',
  'gridTrade.tv_buy': '买单',
  'gridTrade.tv_sell': '卖单',
  'gridTrade.tv_waiting': '等待',
  'gridTrade.chain_cancel_no_need_tips': '此网格策略无需链上取消',
  'gridTrade.grid_over_max_number_err':
    '无法创建，您运行中的网格策略数量已达数量上限',
  'gridTrade.preview_orders_in_graph': '显示订单',
  'gridTrade.greate_news': '好消息：',
  'gridTrade.min_amount_required_XXX': '最少需要XXX',
  'gridTrade.highest_grid_apy': '最高网格收益率',
  'gridTrade.for_the_last_7_days': '基于过去7日',
  'gridTrade.min_investment': '最小投资额',
  'gridTrade.grid_need_XXX': '网格需要 $XXX',
  'gridTrade.mining_need_XXX': '挖矿需要 $XXX',
  'gridTrade.recommended_params_cannot_be_applied':
    '由于投资额不足，推荐参数无法适用。您可以在手动模式下进行调整。',
  'gridTrade.copy_params_to_manual': '把参数填入手动创建',
  'gridOrders.grid_recents': '我的最新成交',
  'gridOrders.th_created_time': '时间',
  'gridOrders.grid_profit': '网格收益',
  'gridOrders.grid_cancel': '关闭策略',
  open_orders: '当前订单',
  'gridOrders.tab_history_orders': '已完成订单',
  'gridOrders.tab_trade_history': '历史成交',
  'gridOrders.detail_current_balance': '当前余额',
  'gridOrders.detail_ending_balance': '结束余额',
  'gridOrders.detail_ending_balance_tips': '此网格策略关闭时的资产余额',
  'gridOrders.detail_in_order_funds': '挂单中的资金：',
  'gridOrders.detail_on_hold_funds': '待挂单的资金（来自已部分成交的订单）：',
  'gridOrders.detail_transactions': '订单完成总数',
  'gridOrders.detail_investment': '初始投资',
  'gridOrders.detail_running_time': '运行时长',
  'gridOrders.detail_prices': '价格区间',
  number_of_grids: '网格数',
  'gridOrders.detail_expire_time': '剩余有效期',
  'gridOrders.detail_expire_time_tooltip': '网格策略下所有订单会在此时间后过期',
  'gridOrders.detail_valid_period': '有效期设置',
  'gridOrders.open_orders_sell': '卖单',
  'gridOrders.open_orders_buy': '买单',
  'gridOrders.open_orders_index': '#',
  'gridOrders.open_orders_total': '金额',
  'gridOrders.history_orders_filled': '数量：',
  'gridOrders.history_orders_price': '价格：',
  'gridOrders.history_orders_time': '时间',
  'gridOrders.history_orders_filled_price': '成交均价',
  'gridOrders.history_orders_filled_amount': '成交数量',
  'gridOrders.history_orders_filled_total': '成交金额',
  'gridOrders.history_orders_profit_tips':
    '收益来自于低买高卖一次循环后的价格差。例如 4000 USDC价格买入1 ETH的网格订单成交后，若网格间距是50 USDC，系统将自动生成4050 USDC卖出1 ETH的订单，当此订单也成交后，您获得了50 USDC的收益。',
  'gridOrders.history_orders_buy_flip_order_tips_PRICE':
    '价格在PRICE的买单成交后将显示收益',
  'gridOrders.history_orders_sell_flip_order_tips_PRICE':
    '价格在PRICE的卖单成交后将显示收益',
  'gridOrders.m_history_orders_flip_order_tips_PRICE':
    '价格PRICE的订单完全成交后会在此显示',
  'gridOrders.grid_cancel_title': '关闭网格策略',
  'gridOrders.grid_cancel_content': '该策略下所有订单都会被立即取消',
  'gridOrders.grid_cancel_content2':
    '该网格策略正在挖矿。如果现在关闭，您将会放弃挖矿奖励，所有网格订单会立即被取消。',
  'gridOrders.copy_grid_title': '将复制下列网格策略参数',
  'gridOrders.copy_grid_btn': '复制到面板',
  'gridOrders.copy_grid_success': '网格策略已复制',
  'gridOrders.grid_init_funds_XXX': '初始投资价值: $XXX',
  'gridOrders.grid_init_funds_tips':
    '根据初始投入币种的初始价格计算而来，用于计算收益率。',
  'gridOrders.tab_m_trade': '网格',
  grid_apy: '网格收益率',
  grid_apy_tips: '仅通过网格交易的年化利润率。不包括浮动盈利。',
  'gridOrders.tab_mining_profit': '挖矿收益率',
  'gridOrders.tab_mining_profit_tips':
    '根据挖矿总收益、初始投入价值和挖矿时长计算得到的年化收益率',
  'gridOrders.mining_rewards': '奖励：',
  'gridOrders.open_orders_empty_tips': '正在加载数据，请稍候',
  'gridOrders.market_value': '市值：',
  'gridOrders.market_value_details': '明细',
  'gridOrders.fund_details': '资金明细',
  'gridOrders.m_in_order_funds': '挂单中的资金',
  'gridOrders.m_in_order_funds_tips': '该网格策略下所有挂单的资金总和',
  'gridOrders.m_on_hold_funds': '待挂单的资金',
  'gridOrders.m_on_hold_funds_tips': '来自部分成交的订单',
  'gridOrders.initial_value': '初始价值',
  'mining.my_title': '我的矿池',
  'mining.index_desc': '创建网格策略，赚网格和挖矿收益',
  'mining.apply': '项目申请',
  'mining.claimable_rewards_box': '可领取奖励',
  'mining.rewards_more': '及更多',
  'mining.tab_pools': '矿池',
  'mining.tab_my': '我的挖矿统计',
  'mining.pools_tab_live': '进行中',
  'mining.pools_tab_upcoming': '即将开始',
  'mining.pools_funds': '总锁定价值',
  'mining.pools_funds_tips': '满足最小订单价值$120的网格订单总价值',
  'mining.pools_mining_funds': '挖矿锁定价值',
  'mining.mining_apr': '年化收益率',
  'mining.mining_apr_tips': '根据挖矿奖励和挖矿锁定价值预估出的年化收益率',
  'mining.view_rule_link': '挖矿规则',
  'mining.pools_info_to_confirm': '待确定',
  'mining.pools_no_wait': '没有计划的矿池',
  'mining.my_mining_funds': '我的挖矿资金',
  'mining.my_mining_rewards': '我的挖矿奖励',
  'mining.my_th_profit_token_price': '最新价格',
  'mining.my_th_total_rewards': '累计奖励',
  'mining.my_th_24h_rewards': '24小时奖励',
  'mining.my_grids': '我的挖矿',
  'mining.only_show_mining_grids': '仅正在挖矿',
  'mining.my_th_mining_status': '挖矿状态',
  'mining.status_framing': '正在挖矿',
  'mining.status_over_price': '已超出价格区间',
  'mining.status_mining_over': '挖矿已结束',
  'mining.status_grid_closed': '策略已关闭',
  'mining.status_grid_expired': '策略已过期',
  'mining.empty_no_faring_grids': '当前没有挖矿的网格策略',
  'mining.go_mining_pool': '查看矿池',
  'mining.go_mining': '去挖矿',
  'mining.go_to_grid': '去网格策略',
  'mining.mining_help': '如何挖矿',
  'mining.mining_available': '满足',
  'mining.mining_available_tips': '满足订单价值要求',
  'mining.mining_unavailable': '不满足',
  'mining.mining_partially_available': '部分满足',
  'mining.mining_unavailable_tips': '未满足订单价值要求',
  'mining.mining_preview': '挖矿预览',
  'mining.mining_total_profit': '挖矿收益',
  'mining.mining_24h_profit': '24小时挖矿收益',
  'mining.profit_unable_display': '无法显示',
  'mining.mining_funds': '挖矿资金',
  'mining.mining_funds_tips':
    '在该交易对中，所有网格策略下满足挖矿订单价值要求的订单的资金总和',
  'mining.tab_mining_profit_details': '最近奖励明细',
  'mining.tab_mining_orders': '挖矿订单',
  'mining.th_rewards': '奖励',
  'mining.th_rewards_origin': '奖励来源',
  'mining.th_rewards_origin_tips':
    '该订单价格位于订单簿奖励价格范围内（最高买单价格*0.99 ~ 最低卖单价格*1.01），因此获得挖矿奖励。',
  'mining.th_rewards_origin_tips_stable':
    '该订单价格位于订单簿奖励价格范围内（最高买单价格 ~ 最低卖单价格），因此获得挖矿奖励。',
  'mining.th_time': '时间',
  'mining.plan_title': 'ETH/USDC 矿池详情',
  'mining.phase_cur': '当前阶段',
  'mining.phase_range_N_XX': '阶段N (XX)',
  'mining.phase_index_N': '阶段N',
  'mining.phase_reward': '每日奖励',
  'mining.phase_to_release': '等待公布',
  'mining.my_rewards': '我的奖励',
  'mining.claimable_rewards': '可领取',
  'mining.locked_rewards': '冻结',
  'mining.locker_rewards_tips': '网格策略运行满12小时后可领取挖矿奖励',
  'mining.claimed_success': '领取奖励成功',
  'mining.claimed_tips': '稍后您将通过内部转账收到款项',
  'mining.claimed_view_btn': '查看',
  'mining.mining_plan': '矿池计划',
  'mining.phase_unpublished': '待公布',
  'mining.all_pools': '全部矿池',
  'notification.limit_desc_SELL_BASE_QUOTE_AMOUNT_PRICE':
    '卖出 AMOUNT BASE @ PRICE QUOTE',
  'notification.limit_desc_BUY_BASE_QUOTE_AMOUNT_PRICE':
    '买入 AMOUNT BASE @ PRICE QUOTE',
  'notification.stop_limit_desc_SELL_BASE_AMOUNT': '卖出 AMOUNT BASE',
  'notification.stop_limit_desc_BUY_BASE_AMOUNT': '买入 AMOUNT BASE',
  'notification.cancel_grid_desc_PAIR_PRICES': 'PAIR：PRICES',
  'notification.cancel_market_desc_SELL_BASE_QUOTE_AMOUNT':
    '以QUOTE卖出AMOUNT BASE',
  'notification.cancel_market_desc_SELL_BASE_QUOTE_TOTAL':
    '以TOTAL QUOTE卖出BASE',
  'notification.cancel_market_desc_BUY_BASE_QUOTE_AMOUNT':
    '以QUOTE买入AMOUNT BASE',
  'notification.cancel_market_desc_BUY_BASE_QUOTE_TOTAL':
    '以TOTAL QUOTE买入BASE',
  'notification.cancel_limit': '限价订单已取消',
  'notification.cancel_stop_limit': '止盈止损订单已取消',
  'notification.cancel_market': '市价单已取消',
  'notification.cancel_grid': '网格策略已关闭',
  'notification.cancel_limit_expired': '限价单已过期',
  'notification.cancel_stop_limit_expired': '止盈止损订单已过期',
  'notification.cancel_grid_expired': '网格策略已过期',
  'notification.cancel_limit_order_for_gas_desc':
    '您订单的矿工费已用完。订单已部分成交，剩余部分被取消。',
  'notification.cancel_limit_order_for_gas_filled_amount': '已成交',
  'notification.cancel_limit_order_for_gas_amount': '订单数量',
  'notification.view_history_orders': '查看历史订单',
  'notification.cancel_market_for_depth_title': '订单部分成交并已取消',
  'notification.price_slippage_protection': '价格滑点保护',
  'notification.price_slippage_protection_desc':
    'DeGate市价单自动包括10%的价格滑点保护，以限制在市场波动大和流动性低的情况下的损失。若无需价格保护，请使用限价单。',
  'notification.cancel_market_for_depth_warning':
    'DeGate市价单引入了价格保护机制，使用户在价格波动剧烈和低流动性的市场中减少损失。如不想触发价格保护，请使用限价模式。',
  'notification.dca_plan_ended': '定投计划已关闭',
  'notification.cancel_dca_desc_PAIR': 'PAIR',
  'notification.trade_limit_partially': '限价单部分成交',
  'notification.trade_limit_filled': '限价单完全成交',
  'notification.trade_market_partially': '市价单部分成交',
  'notification.trade_market_filled': '市价单完全成交',
  'notification.trade_stop_limit_partially': '止盈止损部分成交',
  'notification.trade_stop_limit_filled': '止盈止损完全成交',
  'notification.mobile_trade_filled_AMOUNT_TOKEN':
    '订单完全成交，收到AMOUNT TOKEN',
  'notification.mobile_trade_partially_AMOUNT_TOKEN':
    '订单部分成交，收到AMOUNT TOKEN',
  'info.overview': '概况',
  'info.accounts': '总用户',
  'info.pairs': '交易对',
  'info.turnover': '累计成交额',
  'info.turnover_24': '24小时成交额',
  'info.dg_supply': 'DG流通量',
  'info.top_movers_no_increased': '24小时内无币种上涨',
  'info.top_movers_no_decreased': '24小时内无币种下跌',
  'info.top_pairs': '热门交易对',
  Pair: '交易对',
  'info.th_change': '24小时涨跌',
  'info.th_l_up_2': '+2%深度',
  'info.th_l_down_2': '-2%深度',
  'info.th_turnover_24': '24小时成交额',
  'info.tvl': '总锁定价值',
  'm.home': '首页',
  'm.grid': '网格',
  'm.browser_wallet': '手机钱包',
  'm.choose_pair': '选择交易对',
  'm.orderBook_default': '默认',
  'm.orderBook_bids': '仅买单',
  'm.orderBook_asks': '仅卖单',
  'm.decimals': '小数位',
  'm.lowest_price_24h': '24h最低',
  'm.highest_price_24h': '24h最高',
  'm.vol_24h': '24h量',
  'm.orderbook_buy': '买',
  'm.orderbook_sell': '卖',
  'm.go_to_trade': '去交易',
  'm.choose_token': '选择币种',
  'm.from_address': '付款地址',
  'm.to_address': '收款地址',
  'm.transfer_send': '转出',
  'm.transfer_receive': '收到',
  'm.my_grid': '我的网格策略',
  'm.grid_profit_24': '24小时收益',
  'm.grid_item_trades_24': '24小时成交',
  'm.grid_profit_total': '累计收益',
  'm.grid_over_prices': '超出价格区间',
  'm.create_grid': '创建网格策略',
  'm.grid_history': '历史记录',
  'm.grid_empty': '没有正在运行的网络策略',
  'm.grid_tutorial': '网格教程',
  'm.grid_params_to_manual': '把参数填入手动创建',
  'm.balance_err': '余额不足，当前可用：',
  'm.preview_grid': '预览订单',
  last_price: '最新价格',
  'm.grid_desc':
    '网格交易是一种交易策略，在设定的价格区间内自动地低买高卖产生盈利。',
  'm.view_tutorial': '查看教程',
  'm.grid_profit_tips_sell': '卖单完全成交后计算',
  'm.grid_profit_tips_buy': '买单完全成交后计算',
  'm.hot': '热门',
  'm.all': '全部',
  'm.vol_24': '24h成交量',
  'm.transfer_t1': '内部转账',
  'm.transfer_t2': ' ',
  'activity.th_date': '时间',
  'activity.th_type': '类别',
  'activity.th_fee': '费用',
  'activity.th_content': '内容',
  'activity.type_register_token': '上币',
  'activity.type_register_pair': '添加交易对',
  'activity.type_pay_deposit': '付费入账',
  'activity.type_reset_account': '重置资产私钥',
  on_chain_order_cancellation: '链上取消订单',
  'activity.count_N': '第N次',
  'activity.order_desc_SELL_AMOUNT_BASE_PRICE_QUOTE':
    'SELLAMOUNT BASE，价格PRICE QUOTE',
  'activity.order_market_desc_SELL_AMOUNT_BASE': 'SELLAMOUNT BASE',
  'activity.reset_status_restting': '正在重置',
  'activity.to_trade': '去交易',
  'dca.dca_plan': '定投计划',
  'dca.dca_explain': ' ',
  'dca.daily': '每天',
  'dca.weekly': '每周',
  'dca.custom': '自定义',
  'dca.every': '每',
  'dca.amount_per_order': '每笔订单金额',
  'dca.price_limit': '价格限制',
  'dca.maximum_price': '最高买入价格',
  'dca.minimum_price': '最低卖出价格',
  'dca.number_of_orders': '订单数',
  'dca.create_dca_plan': '创建定投计划',
  'dca.max_gas_fee_per_order': '单笔订单最大矿工费',
  'dca.maximum_plan_order_limit_reached': '已达到计划订单的最大数量限制',
  'dca.end_time_should_be_set_after_the_current_time':
    '结束时间应设定在当前时间之后',
  'dca.please_enter_amount_per_order': '请输入每笔订单金额',
  'dca.please_enter_maximum_price': '请输入最高买入价格',
  'dca.please_enter_minimum_price': '请输入最低卖出价格',
  'dca.order_placement_failed_open_order_limit_exceeded':
    '下单失败：进行中订单达到上限',
  'dca.total': '总金额',
  'dca.filled': '已成交',
  'dca.received': '已收到',
  'dca.time_to_end': '计划到期时间',
  'dca.cancel_on_chain': '链上取消',
  'dca.filled_amount': '已成交/数量',
  'dca.status_executed': '已执行',
  'dca.status_scheduled': '待执行',
  'dca.status_failed': '失败',
  'dca.order_cancled_by_user': '订单已取消，因为用户关闭了定投计划。',
  'dca.order_cancled_by_access': '订单已取消，因为您的DeGate访问受限。',
  'dca.order_cancled_by_gas': '下单失败：矿工费不足。',
  'dca.order_cancled_by_order_book': '下单失败：订单簿没有可匹配订单。',
  'dca.order_cancled_by_balance': '下单失败：DeGate余额不足。',
  'dca.order_cancled_by_min_value': '下单失败：未达到$100最小订单价值。',
  'dca.order_cancled_by_system_error': '由于系统故障，下单失败。',
  'dca.chain_cancel_no_need_tips': '此定投计划无需链上取消',
  'dca.end_dca_plan': '关闭定投计划',
  'dca.all_orders_in_this_dca_plan_will_be_canceled_immediately':
    '此定投计划中的所有订单将被立即取消',
  'dca.no_active_dca_plan': '无运行中的定投计划',
  'dca.time_scheduled': '计划时间',
  'campaign.event_period': '活动时间：',
  'campaign.grid2401_time':
    '2024年1月22日 20:00:00 - 2024年1月29日 20:00:00 (UTC+8)',
  'campaign.event_has_ended': '活动已结束',
  'campaign.current_apy': '当前年化收益率',
  'campaign.grid_strategy_income': '网格策略收益 + 奖池瓜分收益',
  'campaign.tvl_participating': '活动总锁定价值',
  'campaign.share_of_tvl': '我的份额',
  'campaign.my_profit': '我的收益',
  'campaign.grid_strategy_profit': '网格策略收益',
  'campaign.share_of_prize_pool': '奖池瓜分收益',
  'campaign.grid_strategy_profit_has_been_added_to_your_available_balance':
    '获得的网格策略收益已进入可用余额',
  'campaign.shared_income_from_usdc_prize_pool': 'USDC奖池瓜分收益',
  'campaign.is_black_tips': '你不具备瓜分奖池的资格',
  'campaign.calculating': '计算中',
  'campaign.claim_after_end': '奖励将在活动结束后开放领取',
  'campaign.how_to_participate': '如何参加',
  'campaign.rule': '创建网格策略分享奖池',
  'campaign.step1': '步骤1',
  'campaign.step2': '步骤2',
  'campaign.step3': '步骤3',
  'campaign.grid2401_step1': '准备ETH和USDC，可通过划入资金或通过交易获得。',
  'campaign.grid2401_step2_PAIR': '在PAIR交易对创建下列参数的网格策略',
  'campaign.grid2401_step2_desc1_pre': '价格区间: 待公布',
  'campaign.grid2401_step2_desc2_pre': '网格数: 待公布',
  'campaign.copy_strategy': '复制策略',
  'campaign.grid2401_step3':
    '本期活动结束后可在本活动页面Claim收益，请在该期活动结束后30天内领取。',
  'campaign.what_is_grid': '什么是网格策略',
  'campaign.notes': '参与须知',
  'campaign.notes_1_title': '资格:',
  'campaign.notes_1_desc':
    '创建的网格策略在创建时只有在价格区间和网格数与上述活动要求完全一致的情况下，才有资格获得奖池奖励。',
  'campaign.notes_2_title': '限制:',
  'campaign.notes_3_title': '领取:',
  'campaign.notes_3_desc':
    '奖励领取将在活动结束后开放，请在活动结束后30天内领取。',
  'campaign.faq': '常见问题',
  'campaign.grid2401_faq_1': '1. 奖励如何计算?',
  'campaign.grid2401_faq_2': '2. 我参与活动中需要咨询，如何能够获得帮助？',
  'campaign.grid2401_faq_3': '3. 我持有USDT, 我如何获得ETH和USDC？',
  'campaign.grid2401_faq_4': '4. 我通过网格策略完成的交易需要支付手续费么？',
  'campaign.grid2401_faq_4_res':
    'DeGate 中所有Maker订单均为免手续费，网格策略所产生的订单均为Maker订单，所以DeGate中开设网格策略是完全免费的。',
  'campaign.grid2401_faq_5': '5. 活动结束后我的网格还有收益么？',
  'campaign.grid2401_faq_5_res':
    '有，活动结束后，只要当时的价格还在你的网格策略区间内，该策略就会持续不断的产生收益。活动结束后你也可以对网格策略进行参数调整，创建更适合你自己喜好的策略持续获得收益。',
  'campaign.grid2401_faq_others': '其他活动细则:',
  'campaign.grid2401_faq_others_1':
    '1. 本活动仅支持每位用户使用单个钱包进行参与，若发现恶意刷取奖励的行为，DeGate有权取消参与者的获得的奖励。',
  'campaign.grid2401_faq_others_2':
    '2. 在活动还在正常进行的过程中，网格处在超出范围状态也会被计算权重。',
  'campaign.grid2401_faq_others_3':
    '3. DeGate保留在极端情况下提前结束活动的权利。',
  'campaign.grid2401_faq_others_4':
    '4. 活动结束后超过30天没有被领取的奖励会被回收。',
  'campaign.invest_max_5000': '最大投入 $5000',
  'campaign.invest_mininum': '最小投入',
  'airdrop.create_airdrop': '创建空投',
  'airdrop.important_note': '重要提示：任何人都可以无需审核地创建空投',
  'airdrop.my_airdrop': '我的空投',
  'airdrop.time_limited': '限时',
  'airdrop.no_airdrop': '当前没有可领取的空投',
  'airdrop.claim_airdrop': '领取空投',
  'airdrop.recipients_number': '地址总数',
  'airdrop.total_amount': '总金额',
  'airdrop.retrieve': '取回',
  'airdrop.unclaimed': '未领取',
  'airdrop.retrieve_successful': '取回成功',
  'airdrop.claim_successful': '领取成功',
  'airdrop.retrieve_unclaimed_airdrop': '取回未领取空投',
  'airdrop.airdrop_token': '空投币种',
  'airdrop.token_not_meet_criteria': '币种不符合空投的要求',
  'airdrop.airdrop_list': '空投列表',
  'airdrop.download_template': '下载模版',
  'airdrop.click_or_drag_upload_list': '点击或拖动上传列表',
  'airdrop.validation_passed': '已验证',
  'airdrop.must_earlier_than_end_time': '必须早于结束时间',
  'airdrop.cannot_more_than_2_years_from_now': '从现在起最多2年',
  'airdrop.cannot_parse_file': '无法解析文件，请使用列表模版。',
  'airdrop.format_requirement_not_met': '不符合格式要求',
  'airdrop.view_error_repost': '查看错误报告',
  'airdrop.error_report': '错误报告',
  'airdrop.line': '行数',
  'airdrop.reason': '原因',
  'airdrop.duplicated_address': '重复的地址',
  incorrect_address_format: '地址格式不正确',
  'airdrop.incorrect_amount_format': '数量格式不正确',
  'airdrop.airdrop_plan_created': '空投计划已创建',
  'airdrop.max_50000': '最多50000个地址',
  'airdrop.upload_file_rule': '仅支持CSV格式的附件。',
  'airdrop.to_check_airdrop_eligibility': '请连接钱包以查看空投',
  'airdrop.complete_initialization_to_claim_airdrops': '完成初始化以领取空投',
  'airdrop.complete_initialization_to_view_airdrops': '完成初始化以查看空投',
  'airdrop.you_are_eligible_for': '您可领取：',
  'airdrop.and_more': '以及更多',
  'airdrop.congratulations': '恭喜!',
  'airdrop.airdrop_fee': '空投费',
  'countdown.countdown_plan': '首发计划',
  'countdown.create_countdown_plan': '创建首发计划',
  'countdown.my_countdown_plan': '我的创建',
  'countdown.countdown_trading_pair': '倒计时交易对',
  'countdown.countdown_display': '显示倒计时',
  'countdown.token_not_meet_criteria': '币种不符合首发要求',
  'countdown.countdown_tips': '勾选的交易对会在交易页面显示倒计时',
  'countdown.max_30_days': '从现在起最多30天',
  'countdown.review_countdown_plan': '检查首发计划',
  'countdown.countdown_fee': '首发费',
  'countdown.countdown_plan_created': '首发计划已创建',
  'countdown.trading_will_start_in': '交易开始倒计时',
  'countdown.trading_will_start_at_YYYY': '交易将在YYYY后开放',
  'countdown.cannot_earlier_than_current_time': '不能早于当前时间',
  'dca.price_limit_buy_tips':
    '一旦开启，您的买单将只在等于或低于最高价时执行。本功能与零费用选项兼容。',
  'dca.price_limit_sell_tips':
    '一旦开启，您的卖单将只在等于或高于最低价时执行。本功能与零费用选项兼容。',
  'dca.zero_fee': '零费用',
  'dca.zero_fee_buy_tips':
    '开启「零费用」后，定投订单将作为Maker-Only的限价单处理。每个订单的买入价格将在下单后成为订单簿中的最高出价。请注意，您的订单可能不会立即成交，或可能根本无法成交。',
  'dca.zero_fee_sell_tips':
    '开启「零费用」后，定投订单将作为Maker-Only的限价单处理。每个订单的卖出价格将在下单后成为订单簿中的最低卖价。请注意，您的订单可能不会立即成交，或可能根本无法成交。',
  'dca.order_canceled_post_only_buy_failed':
    '由于订单簿缺乏买单，无法确定您订单的买入价格，导致下单失败。',
  'dca.order_canceled_post_only_sell_failed':
    '由于订单簿缺乏卖单，无法确定您订单的卖出价格，导致下单失败。',
  start_time_cannot_before_current_time: '开始时间不能早于当前时间',
  start_time_must_before_end_time: '开始时间必须早于结束时间',
  list_token: '上币',
  contract_address_does_not_exist: '合约地址不存在',
  token_listed: '此代币已完成上币',
  XXX_is_listed: '正在上币XXX',
  view_progress: '查看进度',
  pair_create_tips: '交易对可以在DeGate上即刻添加，无需任何人的批准。',
  base_token: '币种',
  quote_token: '货币',
  existing_pair: '已存在',
  trade_now: '立即交易',
  pair_XXX_added_successfully: 'XXX添加成功',
  qty_per_grid: '每格数量',
  grid_minimum_not_reached: '未达到最小值',
  total_profit: '总体收益',
  total_apy: '总体收益率',
  float_profit: '浮动盈利',
  grid_profit_24h: '24小时网格收益',
  pnl: '损益',
  eligibility: '资格条件',
  rewards: '奖励',
  view_mining_statistics: '查看挖矿统计',
  your_entry: '您的输入',
  refunded: '已返还',
  large_price_spread: '订单簿价差大',
  large_price_spread_tips:
    '订单簿显示最低卖价和最高买价之间的价差较大，存在亏损风险。建议采用双资产模式进行投资。',
  continue_anyway: '仍然继续',
  insufficient_order_book_liquidity_decrease_investment:
    '订单簿流动性不足，请减少投资额',
  initial_buy: '初始购买',
  closing_sell: '关闭卖出',
  No: '不',
  DCA_TRIGGER_FAIL_TIPS_PRICE_XXX:
    '执行定投订单时如果<b>$XXX</b>价格低于<b>$PRICE</b>，订单将会失败。',
  zero_fee: '零费用',
  minimum_order_value_is_VALUE: '最小订单价值为<b>$VALUE</b>。',
  Note: '提示',
  Continue: '继续',
  estimated_apy: '预估收益率',
  based_on_data_from_last_7_days: '根据过去7天数据',
  top_gainers_24h: '24小时涨幅',
  top_losers_24h: '24小时跌幅',
  listed_tokens: '上架币种',
  vol: '成交量',

  let_s_go: '出发',
  reject: '拒绝',
  maximum_N_due_to_price_ticks: '由于价格精度限制，最大值为N',
  Saved: '已保存',
  minimum_order_value_$100_$QUOTE: '最小订单价值为<b>$100 $QUOTE</b>',
  minimum_order_value_$AMOUNT_$QUOTE_$100:
    '最小订单价值为<b> $AMOUNT $QUOTE</>(~$$100)',
  no_restriction_with_market_order: '<b>市价单</b>没有该限制',
  go_to_market_order: '去下市价单',
  Mining_Eligibility: '挖矿资格',
  How_to_earn_mining_rewards: ' 如何获取挖矿奖励',
  Order_Value: '订单价值',
  'mining.mining_tips_BV_BASE_QV_QUOTE':
    '在策略创建时，网格订单至少为<b>BV BASE</b> 或者 <b>QV QUOTE</b>',
  'mining.mining_tips_QV_QUOTE': '在策略创建时，网格订单至少为<b>QV QUOTE</b>',
  Mining_Price_Range: '挖矿价格范围',
  'mining.status_over_price_tips':
    '网格订单价格必须在<b>挖矿价格范围之内</b>，即：订单簿最高买入价格*0.99 ～ 订单簿最低卖出价格*1.01。',
  'mining.status_over_price_tips_stable':
    '网格订单价格必须在<b>挖矿价格范围之内</b>，即：订单簿最高买入价格 ～ 订单簿最低卖出价格。',
  Eligible_for_Mining: '可以挖矿',
  Mining_Satus: '挖矿状态',
  Mining_Satus_Mining: '正在挖矿',
  Mining_Satus_Standby: '等待中',
  Mining_Satus_Ineligible: '不符合要求',
  mining_price_range: '挖矿奖励范围',
  rewards_tips_stable:
    '策略创建时满足挖矿订单价值的网格订单，如果其价格在挖矿价格范围之内可以获得挖矿奖励（最高买单价格 ~ 最低卖单价格）',
  rewards_tips:
    '策略创建时满足挖矿订单价值的网格订单，如果其价格在挖矿价格范围之内可以获得挖矿奖励（最高买单价格*0.99 ~ 最低卖单价格*1.01）',
  wrap: '跨链',
  Wrap: '跨链',
  websites_for_more_information: '获取更多信息：',
  official_site: '官方网站',
  wrap_site: '跨链网站',
  tips_third_party_site: '你即将离开DeGate并访问第三方站点：',
  wrap_unwrap: '跨链兑换',
};

export default zhCN;
