const zhTW = {
  language: 'zh-TW',
  'kline.time_Line': '分時',
  'kline.time_1m': '1分鐘',
  'kline.time_3m': '3分鐘',
  'kline.time_5m': '5分鐘',
  'kline.time_15m': '15分鐘',
  'kline.time_30m': '30分鐘',
  'kline.time_1H': '1小時',
  'kline.time_2H': '2小時',
  'kline.time_4H': '4小時',
  'kline.time_6H': '6小時',
  'kline.time_1D': '1天',
  'kline.time_1W': '週線',
  'kline.time_1M': '月線',
  'kline.tab_line': '圖表',
  'kline.tab_depth': '深度圖',
  'kline.chartType_Bars': '線',
  'kline.chartType_Candles': '蠟燭',
  'kline.chartType_Hollow_Candles': '空心蠟燭',
  'kline.chartType_Line': '線段',
  'kline.chartType_Area': '區域',
  'kline.chartType_Heikin_Ashi': '平均K線圖',
  degate_account: 'DeGate帳號',
  Trade: '交易',
  Order: '訂單',
  Grid: '網格策略',
  Campaign: '活動',
  DCA: '定投計劃',
  Advanced: '進階',
  Add: '添加',
  Add_Funds: '添加資金',
  eth_added_1: '已添加 1 ETH',
  eth_sent_1: '已發送 1 ETH',
  Send: '發送',
  Internal_Transfer: '內部轉帳',
  Miscellaneous: '其他',
  Bridge: '跨鏈',
  Mining: '挖礦',
  Liquidity_Mining: '流動性挖礦',
  Analytics: '分析',
  Support: '支援',
  Help: '幫助',
  Tips: '提示',
  Statistics: '統計數據',
  Coming_soon: '即將推出',
  Faucet: '水龍頭',
  more: '更多',
  hide: '隱藏',
  change: '調整',
  'Wrong Network': '錯誤網絡',
  avbl: '可用餘額',
  chain_1: '主網',
  chain_3: 'Ropsten（測試網）',
  chain_4: 'Rinkeby（測試網）',
  chain_5: 'Goerli（測試網）',
  chain_42: 'Kovan（測試網）',
  chain_42161: 'Arbitrum（二層網路）',
  chain_10: 'Optimism（二層網路）',
  insufficient_balance_AAA: '您的錢包裡沒有足夠的 AAA。 請確認餘額並重試。',
  insufficient_balance: '餘額不足',
  wallet_denied_sign: '簽名訊息被拒絕',
  common_err: '出了些問題。請稍後再試',
  common_err_ledger_version:
    '發生了錯誤。請確保您的 Ledger 以太坊應用程式是最新的（1.9.10 或更高版本），或者您可以稍後重試。',
  network_1: '以太坊(主網)',
  network_err: '不支援的網絡，請稍後再試',
  rate_limit_err: '訪問頻率過高，請一分鐘後重試。',
  error_InsufficientGasFunds: '錢包燃料費餘額不足',
  notification_transaction_send: '交易已發送',
  view_on_etherscan: '請在區塊鏈瀏覽器上查看',
  view_on_explorer: '查看錢包地址',
  switch_network: '切換網絡',
  switch_to_Arbitrum: '請切換至 Arbitrum 網絡以繼續',
  switch_to_MAINNET_in_metamask: '請在 MetaMask 切換為 MAINNET',
  switch_to_MAINNET: '請切換為 MAINNET',
  switch_network_in_walletconnect:
    '請前往您的錢包，並使用 WalletConnect 切換網絡',
  Retry: '請重試',
  wallet_tips: '請在瀏覽器錢包中批准',
  wallet_ledger_tips: '請在 Ledger 冷錢包中批准',
  wallet_metamask_tips: '請在 MetaMask 中批准',
  wallet_walletconnect_tips: '請前往您的錢包，並使用 WalletConnect 批准',
  wallet_cancelled_tips: '您已取消簽名',
  Close: '關閉',
  copied: '已複製',
  Details: '詳細資訊',
  view_details: '查看詳細資訊',
  Share: '分享',
  view_graph: '在圖表中查看',
  Dismiss: '關閉',
  Cancel: '取消',
  End: '關閉',
  End_grid: '關閉',
  Confirm: '確認',
  Cancel_all: '取消全部',
  cancel_all_tips: '取消全部掛單',
  Submit: '提交',
  no_data: '查無數據',
  all_data_displayed: '已经顯示所有數據',
  no_data_within_90_days: '過去90天內無數據',
  only_display_90_days: '僅顯示過去90天的數據',
  displayed_90_days: '顯示過去90天的數據',
  only_data_beyond_90_days_trade:
    '要訪問超過90天的數據，請選擇「查看全部」，然後選擇「導出數據」功能。',
  only_data_beyond_90_days_grid_detail: '目前不支援超過最近90天的數據查詢',
  only_data_beyond_90_days_spot_history:
    '要訪問超過90天的數據，請使用「導出數據」功能。',
  View: '查看',
  service_unavailable_for_region_REGION: '此服務在 REGION 不可用。',
  service_unavailable: '服務不可用',
  service_error: '請稍後再試',
  service_maintenance: '此服務正在進行維護',
  connect_wallet: '連接錢包',
  switch_address: '切換地址',
  wallet_wc: '已與 WalletConnect 連接',
  wallet_ledger: '已與 Ledger 冷錢包連接',
  register_dexAccount: '註冊',
  deposit_ETH: '添加 ETH',
  initialize: '初始化',
  initialization: '初始化',
  invalid_signature: '無效簽名',
  possible_cause: '可能的原因',
  locale_time_error: '您的本地設備時間不準確',
  authorization_mode: '授權模式',
  authorization_mode_standard: '免簽名',
  authorization_mode_single_use: '单次簽名',
  turn_on: '開啟',
  turn_on_signature_free_mode: '開啟免簽名模式',
  signatre_free_mode: '開啟免簽名模式',
  turn_on_signature_free_mode_tips:
    '在此模式下，您可以在不簽名的情況下下單。要切換模式，請至「交易按鈕」下方進行設定。',
  turn_on_signature_free_mode_tips_grid:
    '在此模式下，您可以在不簽名的情況下創建網格策略。要切換模式，請至「交易按鈕」下方進行設定',
  turn_on_signature_free_mode_tips_dca:
    '在此模式下，您可以在不簽名的情況下創建定投計劃。要切換模式，請至「交易按鈕」下方進行設定。',
  yes: '是',
  no: '否',
  free_mode_on: '免簽名模式已開啟',
  view_balance: '查看餘額',
  delete_asset_key: '刪除資產密鑰',
  delete_asset_key_desc: '一旦從瀏覽器中刪除資產密鑰，標準授權模式將被關閉。',
  no_asset_key_tips: '在您的瀏覽器中找不到任何資產密鑰',
  turn_off_standard_mode: '關閉免簽名模式',
  reset_asset_key: '重置資產密鑰',
  view_asset_key: '查看資產密鑰',
  lock_success: '資產密鑰已刪除',
  reset: '重置資產密鑰',
  delete: '刪除',
  withdraw_ETH: '發送 ETH',
  transfer_ETH: '內部轉帳 ETH',
  history: '歷史紀錄',
  view_history: '在歷史紀錄中查看',
  internal_transfer: '轉帳',
  assets_record_link: '歷史紀錄',
  other: '其他',
  login_success: '連接成功',
  Account: '帳戶',
  Address: '地址',
  Disconnect: '斷開連接',
  copy_address: '複製地址',
  copy_grid: '複製策略',
  Copy: '複製',
  btn_search: '搜尋',
  btn_reset: '重置',
  btn_confirm: '關閉',
  btn_max: '最大值',
  btn_ok: '確定',
  spot_trade: '現貨',
  grid_trade: '網格',
  err_balance_title: '下單失敗',
  err_balance_content: '可用餘額不足。請驗證後再試一次。',
  order_failed: '下單失敗',
  insufficient_order_value: '订單價值不足',
  grid_failed: '創建失敗',
  err_eth_gas: '以太坊網絡嚴重擁擠',
  err_insufficient_balance_TOKEN1: 'TOKEN1 餘額不足',
  err_insufficient_balance_TOKEN1_TOKEN2: 'TOKEN1 和 TOKEN2 餘額不足',
  please_add_funds_before_ordering: '在下單之前，請向 DeGate 餘額中添加資金',
  err_balance_content_spot: '由於餘額不足，無法下單',
  err_balance_content_grid: '由於餘額不足，無法創建網格策略',
  trade_min_volume_tips_XXX: '最小值 XXX',
  grid_min_volume_tips: '每筆訂單的數量不符合最低金額。請再試一次',
  trade_risk_orders_tips: '由於您有太多未完成訂單，無法下單',
  gas_token_tips: '選擇燃料費代幣',
  add_favorite_tooltip: '添加至收藏夾',
  remove_favorite_tooltip: '從收藏夾中移除',
  expire_tips_X: '此訂單將於X到期',
  today: '現在',
  now: '現在',
  time_D_day: 'D天',
  time_D_day_H_hour: 'D天 H小時',
  time_H_hour_M_minute: 'H小時 M分鐘',
  time_M_minute_S_second: 'M分鐘 S秒',
  time_S_second: 'S秒',
  around: '~',
  time_now: '現在',
  time_before: '之前',
  time_before_ago: '之前',
  time_1_minute: '1分鐘',
  time_1_hour: '1小時',
  time_1_day: '1天',
  time_1_year: '1年',
  time_M_minutes: 'M分鐘',
  time_M_m: 'M分鐘',
  time_H_hours: 'H小時',
  time_H_h: 'H小時',
  time_D_days: 'D天',
  time_Y_years: 'Y年',
  time_Y_y: 'Y年',
  fee_change_tips: '價格已更新',
  no_pairs: '未找到交易對',
  register_new_pair: '添加新交易對',
  register_pair: '添加交易對',
  add_pair: '添加交易對',
  tips_hide_forever: '不再顯示',
  token: '代幣',
  action: '操作',
  more_actions: '更多',
  gas_fee: '燃料費',
  'orders.detail_gas': '實際燃料費',
  trade_fee: '手續費',
  about_degate: '關於DeGate',
  metrics: '指標',
  fees: '費用',
  document: '文檔',
  join_us: '加入我們',
  feedback: '反饋',
  email_optional: '您的電子郵件地址(可選)',
  Upload: '上傳',
  feedback_upload_tip: '請分享您的反饋。拖動文件以附加',
  feedback_upload_tip_mobile: '請分享您的反饋',
  image_upload_tip: '釋放以添加',
  feedback_success: '我們聽到您的聲音',
  feedback_success_2: '謝謝您',
  feedback_failed: '提交失敗。請稍後再試',
  image_upload_rule_1: '僅支援PNG、JPG、JPEG',
  image_upload_rule_2: '每個文件的最大限制為20MB',
  image_upload_rule_2_3: '每個文件的最大限制為20MB，最多5个',
  no_pair: '未找到代幣對',
  no_token: '未找到代幣',
  choose_base_token: '選擇基準代幣',
  choose_quote_token: '選擇報價代幣',
  get_test_token: '獲取測試網代幣',
  faucet: '水龍頭',
  expire_in: '過期時間',
  expire_in_empty_err: '請輸入一個數字',
  go_back: '返回',
  max_XXX: '最大值 XXX',
  min_XXX: '最小值 XXX',
  fill_in: '填寫',
  my_balance: '我的餘額',
  deGate_insufficient_fees: 'DeGate餘額不足以支付燃料費',
  wallet_balance: '錢包餘額',
  your_wallet_balance: '您的錢包餘額',
  degate_balance: 'DeGate餘額',
  wallet_insufficient_fees: '錢包餘額不足',
  wallet_insufficient_balance: '餘額不足',
  insuffficient_wallet_balance: '錢包餘額不足',
  degate_insufficient_balance: '可用餘額不足',
  open_discord: '前往Discord社區',
  err_valid_until: '請在您的設備上將本地時間調整為標準時間',
  tips_gas: '用於執行此鏈上交易的燃料費將從您的 DeGate 餘額中扣除。',
  maker_free: '掛單免費',
  trading_fee_rate: '交易費率',
  Free: '免費',
  stop_service_1: '網站正在維護中',
  stop_service_2: '預計恢復時間',
  stop_upgrade: '測試網的新版本正在遷移',
  stop_trading_1: '系統升級',
  stop_trading_2: '交易暫停',
  sell: '賣',
  buy: '買',
  SELL: '賣',
  BUY: '買',
  Sell: '賣',
  Buy: '買',
  sell_order: '賣單',
  buy_order: '買單',
  edit: '編輯',
  status_processing: '處理中',
  status_processed: '待定',
  status_pending: '待定',
  status_confirming: '確認中',
  status_success: '成功',
  status_completed: '已完成',
  status_failed: '失敗',
  status_speeding_up: '加速中',
  status_canceling: '取消中',
  status_canceled: '已取消',
  in_progress: '進行中',
  limit_order: '限價',
  market_order: '市價',
  stop_limit_order: '限價止損',
  balance: '餘額',
  empty_connect: '請先連接錢包',
  empty_register: '請先初始化',
  empty_months3: '過去3個月無數據',
  show_months3: '僅顯示過去3個月內數據',
  view_all: '查看全部',
  D1: '1日',
  D5: '5日',
  M1: '1個月',
  M3: '3個月',
  M6: '6個月',
  YTD: '年初至今',
  Y1: '1年',
  all: '全部',
  view_more: '更多',
  paste: '貼上',
  clear: '清除',
  total: '總計',
  amount: '數量',
  order_amount: '訂單數量',
  price: '價格',
  order_total: '總計',
  filledAmount: '數量',
  tradeFilledTotal: '價值',
  orderFilledTotal: '總計',
  filledAmount_amount: '已成交/數量',
  profit: '利潤',
  incompatible_token: '此代幣的技術規格與 DeGate 協議不兼容。',
  next: '下一步',
  token_not_verified: '未驗證',
  token_not_verified_tips:
    '合約地址、圖標和符號未經驗證。請檢查合約地址以避免假代幣詐騙。',
  token_verified: '已驗證',
  token_verified_tips: '合約地址、圖標和符號相符。',
  arrival_time: '到達時間',
  deposit_tips_region: '請注意，您正在 REGION 中使用 DeGate。',
  complete_time: '完成時間',
  unable_to_initialize: '無法初始化',
  filter_base: '基準',
  filter_quote: '報價',
  filter_type: '類型',
  filter_role: '角色',
  option_maker: '掛單',
  option_taker: '吃單',
  start_data: '開始日期',
  end_data: '結束日期',
  added_to_favorites: '已添加到收藏夾',
  removed_to_favorites: '從收藏夾中刪除',
  show_recents_50: '已顯示最新的 50 條數據。',
  terms_of_service: '服務條款',
  tips_small_unfilled:
    '根據系統設計中指定的精度，部分未成交的訂單已退回到您的DeGate餘額。',
  notification: '通知',
  server_message_SystemRecovery: '請注意，系統恢復後，您的訂單狀態已更改。',
  learn_more: '了解更多',
  connect_ledger: '連接 Ledger 冷錢包',
  ledger_disconnect:
    "在 'USB 設備' 上執行 'transferOut' 失敗：設備已斷開連接。",
  gas_fee_expired: '燃料費已過期。請重新提交。',
  scroll_down_to_refresh: '向下滾動以刷新',
  release_to_refresh_immediately: '釋放以刷新',
  no_more: '沒有更多數據',
  loading: '正在加載...',
  force_withdrawing_token_tips: '正在處理您的強制提款請求，無法執行當前操作。',
  speed_up: '加速',
  transaction_submitted: '交易已提交',
  tx_speed_up: '加速交易',
  tx_cancel: '取消交易',
  none: '無',
  Language: '語言',
  page: '/頁',
  go_to: '前往',
  icon_indicators: '指標',
  icon_back: '返回',
  icon_forward: '前進',
  icon_full_screen: '全螢幕畫面',
  icon_exit_full_screen: '退出全螢幕畫面',
  icon_buy_sell_orders: '買賣訂單',
  icon_buy_orders: '買單',
  icon_sell_orders: '賣單',
  icon_enable: '點擊啟用',
  icon_disable: '點擊禁用',
  icon_copy: '複製地址',
  icon_view_explorer: '在區塊瀏覽器中查看',
  icon_display_by_profit: '按利潤顯示',
  icon_display_by_time: '按時間顯示',
  icon_switch: '切換',
  eth_code_tips: '以太坊的原生代幣。無代幣合約地址。',
  TBD: '待定',
  go_to_discord: '或加入 Discord 社群創建工單',
  release: '釋放：',
  security: '安全',
  colon: '：',
  zero_balance: '零餘額',
  ledger_app_version_tips:
    '請更新您的 Ledger 上的以太坊應用至 v1.10.0 或更新版本，以預覽要簽署的訊息。',
  ledger_contract_data_tips: '請在以太坊應用程式設置中啟用盲簽或合約數據。',
  input_auto_corrected_tooltips: '已超過最大位數，系統自動更正您的輸入。',
  maximum_decimal_reached: '已達到最大小數位數',
  verify_ownership: '驗證所有權',
  enable_trading: '啟用交易',
  learn_more_about_signatures_link: '了解更多關於簽名的資訊 >',
  learn_more_about_signatures: '了解更多關於簽名的資訊',
  sign: '簽名',
  sign_step1: '在您的錢包中完成',
  sign_step2: '完成第二次簽名',
  not_now: '不是現在',
  view_on_block_explorer: '在區塊鏈瀏覽器中查看',
  view_in_history: '在歷史紀錄中查看',
  continue_to_place_order: '繼續下單',
  Save: '保存',
  sign_to_view: '簽名以查看',
  available_degate_balance: '可用的DeGate餘額',
  Back: '返回',
  token_has_not_listed: '此代幣尚未在 DeGate 上架。',
  list_now: '立即上架',
  spread_15: '價差>15%',
  connected: '已連接',
  self_list_token: '即時上架',
  claim_REBASE: '領取REBASE',
  time: '時間',
  time_updated: '更新時間',
  show_in_X_m: '約 ~X 分鐘后顯示',
  max_gas: '最大燃料費',
  total_required: '總計所需',
  Required: '必需的',
  available_balance: '可用餘額',
  please_add_funds: '請將資金存入您的 DeGate 餘額。',
  Side: '方向',
  pending: '待處理',
  active: '進行中',
  ended: '已結束',
  name: '名稱',
  yield: '收益',
  time_created: '建立時間',
  time_ended: '結束時間',
  frequency: '頻率',
  chain_cancel: '在區塊鏈上取消',
  status: '狀態',
  status_chainCancelProgressing: '正在區塊鏈上取消',
  status_chainCancelCompleted: '已在區塊鏈上取消',
  filled_total: '已成交/總量',
  start_time: '開始時間',
  end_time: '結束時間',
  Summary: '總結',
  Orders: '訂單',
  Tutorial: '教程',
  Earn: '賺幣',
  top_winner_24h: '24小時冠軍',
  ID: '序號',
  Select: '選擇',
  Create: '創建',
  Review: '預覽',
  Airdrop: '空投',
  Countdown: '首發',
  Day: '天',
  Hour: '小時',
  Minute: '分鐘',
  Second: '秒',
  Days: '天',
  Hours: '小時',
  Minutes: '分鐘',
  Seconds: '秒',
  Claim: '領取',
  Expired: '已過期',
  Claimed: '已領取',
  Welcome: '歡迎',
  gas_tips_for_amount_exceed_6_digits:
    '因为金额的数字超过了六位数的限制，因此会额外收费',
  input_auto_corrected_minStep_tips: '自动调整你的输入到最低要求的精确度',
  order_max_limit: '超过最高限度',
  order_min_limit: '未达到最低限度',
  order_faild_min_limit: '下单失败：未达到最低限度',
  order_faild_max_limit: '下单失败：超过最高限度',
  disconnect_m: '斷開',
  'account.account_manage': '安全',
  'account.account_manage_more': '關於授權模式和資產密鑰 >',
  'account.what_is_asset_key': '關於授權模式和資產密鑰',
  'account.total_value': '總價值',
  'account.hide_small_balances': '隱藏小餘額',
  'account.add_to_metamask': '將代幣添加至錢包',
  'account.assets_balance_total': '總計',
  'account.assets_balance_available': '可用的',
  'account.assets_market': '價值',
  'account.transfer_to_degate_balance': '添加到 DeGate 餘額',
  'account.search_tokens': '搜尋代幣',
  'account.deposit_title':
    '資產將存入您的去中心化 DeGate 帳戶。您擁有這些資產完全的控制權。',
  'account.deposit_tips': '您擁有這些資金完全的控制權。',
  'account.deposit_confirm_btn': '添加',
  'account.deposit_approved_btn': '已批准',
  'account.deposit_1_ETH': '添加 1 ETH 到您的 DeGate 餘額',
  'account.deposit_status_pending': '待處理',
  'account.deposit_status_pay_pending': '應付款',
  'account.deposit_status_pay_waiting': '付款已廣播',
  'account.deposit_status_pay_confirming': '確認付款中',
  'account.deposit_tips_block': '交易等待區塊納入',
  'account.deposit_status_pay_btn': '支付',
  'account.pay_deposit_warning': '添加資金可能會產生額外的燃料費',
  'account.pay_deposit_warning_tips':
    '由於 DeGate 的補貼已用完，用戶可能需要承擔添加資金的成本。',
  'account.deposit_pending_tips':
    '如果等待時間超過 5 分鐘，請在您的錢包中加快交易速度。',
  'account.deposit_pending_tips_ledger':
    '如果等待時間超過 5 分鐘，請加快交易速度。',
  'account.deposit_contract_tips_over_AMOUNT':
    '對於超過 AMOUNT 美元的資金添加，僅支持高級方法的資金增加。',
  'account.deposit_contract_tips_only_all': '僅支持進階方法的資金添加',
  'account.suggest_100': '建議不小於 100 美元',
  'account.suggest_100_tips': '在訂單簿上列出的最低訂單價值為 100 美元。',
  'account.deposit_failed': '失敗',
  'account.deposit_failed_tips': '添加資金的鏈上交易失敗。',
  'account.payment_due': '應付款',
  'account.payment_due_tips': '需要額外的付款才能將資金存入您的 DeGate 餘額。',
  'account.register_token_code_placeholder': '輸入合約地址',
  'account.register_token_code': '合約地址',
  'account.register_token_symbol': '符號',
  'account.register_token_check': '檢查上架進度',
  'account.register_token_code_err_added': '此代幣正在上架',
  'account.register_token_next_step': '下一步',
  'account.register_token_tips1':
    '無需權限即可進行區塊鏈代幣上架。請立即上架您的代幣。',
  'account.register_token_btn': '上架代幣',
  'account.list_token': '上架代幣',
  'account.withdraw_warning_XXX':
    '由於需求增加，目前發送資金需要大約 ~XXX 的時間。',
  'account.withdraw_status_pending': '處理中',
  'account.tansferred_1_ETH': '已轉移 1 ETH',
  'account.transfer_status_sent': '已發送',
  'account.transfer_status_received': '已收到',
  'account.th_me': '我',
  'account.th_tx_hash': '交易哈希',
  'account.th_time': '時間',
  'account.locked_order': '限價訂單',
  Sending: '正在發送',
  'account.locked_claimable': '可領取',
  'account.locked_grid': '網格策略',
  'account.personal_sign_reason': '可能的原因',
  'account.personal_sign_reason1': '1. MetaMask 已連接到硬件錢包',
  'account.personal_sign_reason2': '2. MetaMask 版本過時',
  'account.personal_sign_reason3': '3. 其他',
  'account.personal_sign_btn': '重新簽名',
  'account.deposit_arrive_in_30s': '約 30 秒內到達',
  'account.deposit_arrive_in_30s_s': '約 30 秒',
  'account.account_completed_time_XXX': '約在 XXX 內完成',
  'account.search_result_no_token': '找不到代幣',
  'account.search_result_invalid_code': '無效的合約地址',
  'account.search_result_not_listed': '代幣目前未上架在 DeGate',
  'account.search_result_tips_register': '您可以輸入合約地址以完成代幣上架',
  'account.search_result_not_find': '仍然找不到？',
  'account.search_pair_tips3': '該資產沒有交易對',
  'account.search_pair_tips3_add': '請添加交易對',
  'account.register_token': '無需許可的上架代幣',
  'account.search_again': '重新搜索',
  'account.deposit_type': '方法',
  'account.deposit_type_standard': '標準',
  'account.switch_account_tips': '切換至',
  'account.switch_account_tips_register': '請先初始化',
  'account.initialize_success': '初始化成功',
  'account.approve': '批准',
  'account.reset_USDT': '重置 USDT 批准',
  'account.reset_USDT_tips': '當支出限額太低時，USDT 需要重置批准。',
  'account.next_step': '下一步',
  'account.profit_total': '總盈利',
  'account.profit_history': '盈利歷史',
  'account.tab_mining_rewards': '挖礦獎勵',
  'account.yield_total': '總收益',
  'account.yield_24h': '24小時收益',
  'account.claimable': '可領取',
  'account.yield_history': '收益歷史',
  'account.total_grid_profit': '總網格利潤',
  'account.grid_strategies': '網格策略',
  'account.total_rewards': '總獎勵',
  'account.rewards_24h': '24小時獎勵',
  'account.rewards': '獎勵',
  'menu.register_err':
    '您的地址沒有任何區塊鏈交易記錄。請完成一筆鏈上交易，然後重試。例如，將代幣轉移到您的錢包。',
  'menu.reset_post_success_withOrders':
    '已啟動資產密鑰重置。您所有的未完成訂單和網格策略已被取消。',
  'menu.reset_post_success': '已啟動資產密鑰重置。',
  'menu.reset_processing_title': '正在進行資產密鑰重置',
  'menu.reset_processing_desc': '請等待完成',
  'trade.choose_token': '選擇代幣',
  'trade.token_info': '代幣資訊',
  'trade.token_address': '代幣地址',
  'trade.price_range_24h': '24小時價格範圍',
  'trade.vol_24h': '24小時成交量',
  'trade.item_price_TOKEN': '價格 (TOKEN)',
  'trade.item_amount_TOKEN': '數量 (TOKEN)',
  'trade.order_book_title': '訂單簿',
  'trade.order_book_total': '總計',
  'trade.trade_history_title': '最新交易',
  'trade.trade_history_time': '時間',
  'trade.market_placeholder_price': '市場價格',
  'trade.what_is_stop_limit': '什麼是止損限價',
  'trade.what_is_stop_limit_link': '什麼是止損限價 >',
  'trade.placeholder_total': '總計',
  'trade.more_settings': '設置',
  'trade.expire_in_tips': '該訂單將在到期後自動取消。',
  'trade.period_day_s': '天',
  'trade.period_hour_s': '小時',
  'trade.period_minute_s': '分鐘',
  'trade.period_err_input_tips': '請輸入有效數字',
  'trade.post_only_label': '僅限掛單',
  'trade.post_only_tips':
    '僅限掛單模式確保僅掛單訂單進入訂單簿。如果訂單的任何部分可以作為吃單訂單成交，那麼整個訂單將被退回。掛單模式的訂單不會產生任何燃料費或交易費用。',
  'trade.post_only_fail_title': '無法創建訂單',
  'trade.post_only_fail_desc': '請調整價格或停用"僅限掛單模式"。',
  'trade.max_gas_fee_tips':
    '最大燃料費涵蓋了交易結算的鏈上成本，由吃單方支付並且掛單方免費。超出的費用將被退還。',
  'trade.auto': '自動',
  'trade.custom': '自定義',
  'trade.enough_for_XX_trades': '足夠進行 XX 筆交易',
  'trade.gas_fee_per_trade': '每筆交易的燃料費',
  'trade.gas_fee_per_trade_tips':
    '吃單方需支付每筆交易的燃料費用，以促進鏈上結算，費用根據以太坊網絡條件波動而變化。',
  'trade.max_number_of_trades': '最大交易次數',
  'trade.btn_buy_ETH': '購買 ETH',
  'trade.btn_sell_ETH': '出售 ETH',
  'trade.max_buy_fee_deducted_NUM': '已扣除燃料費。最大為 NUM。',
  'trade.notification_limit_order_title': '已下單限價單',
  'trade.notification_stop_limit_order_title': '已下單止損限價單',
  'trade.err_price': '請輸入價格',
  'trade.err_amount_total': '請輸入數量或總數',
  'trade.err_amount': '請輸入數量',
  'trade.err_insufficientFee_title': '燃料費不足',
  'trade.err_insufficientFee_desc':
    '請檢查您的最大燃料費設置和您的 DeGate 餘額。',
  'trade.cancel_order_success': '訂單已取消',
  'trade.pair_favorite': '收藏',
  'trade.pair_search': '搜尋代幣，合約地址',
  'trade.pair_last_price': '價格',
  'trade.pair_change': '變動',
  'trade.url_parse_err_title': '該交易對不存在。',
  'trade.risk_tips': '風險警告',
  'trade.base_is_not_default_token_tips':
    '在交易之前，請通過官方來源驗證代幣合約地址，以避免詐騙代幣。',
  'trade.chain_cancel': '在鏈上取消訂單',
  'trade.chain_cancel_no_need_tips': '此訂單無需在鏈上取消。',
  'trade.chain_cancel_success': '請求已發送',
  'trade.depth_empty': '暫時無訂單',
  'trade.depth_empty_asks': '無任何賣單',
  'trade.depth_empty_bids': '無任何買單',
  'trade.depth_empty_tips': '市價訂單因訂單簿中的開放訂單不足而失敗',
  'trade.history_empty': '尚無交易',
  'trade.err_price_stable': '價格無效。請重試。',
  'trade.price_warning': '您輸入的價格與市場價格不符，請在下單前確認。',
  'trade.order_value_tips':
    '最小訂單價值為 <b>QUOTE_A</b> 或 <b>BASE_A</b>，相當於 MINUSD 美元。使用市價訂單可繞過此限制。',
  'trade.order_value_tips_quote':
    '最小訂單價值為 <b>QUOTE_A</b>，相當於 MINUSD 美元。使用市價訂單可繞過此限制。',
  'trade.order_value_tips_stable_quote':
    '最小訂單價值為 <b>QUOTE_A</b>。使用市價訂單可繞過此限制。',
  'trade.system_limit': '已超過系統限額',
  'trade.stop_limit_untriggered_tips':
    '訂單尚未提交到訂單簿，因為未達到停止價格。',
  'trade.stop_limit_triggered_tips_TIME': '訂單已在 TIME 提交到訂單簿',
  'trade.flow_of_funds': '資金流向',
  'trade.flow_of_funds_tip2':
    '您已下單成功。訂單資金將進入您的 DeGate 餘額，而不是您的錢包餘額。',
  'orders.show_current_pair_orders': '隱藏其他交易對',
  'orders.orderHistory': '訂單歷史紀錄',
  'orders.th_time': '時間',
  'orders.th_average_price': '平均價格',
  'orders.th_stop_price': '停止價格',
  'orders.th_limit_price': '限價',
  'orders.th_filled_price': '價格',
  'orders.th_filled_amount': '已成交',
  'orders.th_filled_total': '總計',
  'orders.th_trade_reconciliation': '對帳',
  'orders.th_trade_reconciliation_tips':
    '請注意，由於 DeGate 上的撮合和鏈上結算所採用的計算模型不同，因此兩者的計算結果可能存在細微差異。 如果發生這種情況，系統將以鏈上價值為標準，並彌補 DeGate餘額的任何不足。',
  'orders.hide_cancelled_expired_orders': '隱藏已取消/已過期',
  'orders.status_open': '開放',
  'orders.status_pending': '待處理',
  'orders.status_completed': '已成交',
  'orders.status_completed_part': '部分成交',
  'orders.status_expired': '已過期',
  'orders.detail_price': '平均/價格',
  'orders.average_price': '平均價格',
  'orders.detail_type': '訂單類型',
  'orders.detail_trade_fee': '手續費：',
  'orders.gas_preAuth': '最大燃料費：',
  'orders.fee_reconciliation': '對帳：',
  'orders.gas_paid': '已支付燃料費：',
  'orders.gas': '燃料費：',
  'orders.trades_N': '交易次數（N）',
  'orders.detail_filled_total': '總計',
  'orders.detail_filled_detail': '交易詳情',
  'orders.detail_filled_time': '時間',
  'orders.order_maker_free': '掛單費用免費',
  'orders.openOrders_empty': '無未完成訂單',
  'orders.export_orders_1_year': '導出最近一年的訂單數據',
  'orders.export_trades_1_year': '導出最近一年的交易數據',
  'orders.export_data': '導出數據',
  'orders.export': '導出',
  'orders.export_processing': '處理中，請稍候。',
  'orders.export_tips_100_percent': '一旦進度達到 100％，文件將被下載',
  'orders.sign_to_view_balance': '請登錄以查看餘額',
  'orders.sign_to_view_history': '請登錄以查看歷史記錄',
  'orders.sign_to_view_security_options': '請登錄以查看安全選項',
  'gridTrade.automatic_strategy': '自動',
  'gridTrade.manual_strategy': '手動',
  'gridTrade.placeholder_amount': '輸入金額',
  'gridTrade.low_price': '下限',
  'gridTrade.high_price': '上限',
  'gridTrade.initial_investment': '初始分配',
  'gridTrade.grid_levels_tips': '用于确定價格範圍内订单的数量',
  'gridTrade.profit_per_grid': '每格利润',
  'gridTrade.profit_per_grid_tips':
    '網格策略盈利能力的重要參數。 每格利潤 =（較高價格 - 較低價格）/ 較低價格。 較高價格和較低價格指的是網格策略中兩個相鄰網格線的價格。',
  'gridTrade.min_grid_volume_XXX_ETH': '每格網格的金額：最小為 XXX ETH',
  'gridTrade.min_grid_volume_err': '請增加投資額度或減少網格數',
  'gridTrade.grid_no_depth_tips_BASE_QUOTE':
    '由於訂單簿中訂單不足，因此無法為此交易對創建網格策略。',
  'gridTrade.grid_to_spot_trade': '前往現貨交易',
  'gridTrade.grid_level_over_err': '請減少網格數量',
  'gridTrade.grid_prices_err': '請擴大價格範圍',
  'gridTrade.grid_create_err': '請調整參數，然後重試。 ',
  'gridTrade.tips_grid_profit': '利潤將直接記入您的 DeGate 餘額，並立即可用。 ',
  'gridTrade.tips_grid_balance_0_BASE':
    '市場價格上升導致此網格策略下的所有訂單均變為買單。因此，基礎資產的當前餘額現在為 0。',
  'gridTrade.tips_grid_balance_0_BASE_2':
    '市場價格上升導致此網格策略下的所有訂單均變為買單。 此外，其中一些訂單部分成交。 因此，基礎資產的當前餘額為 >0。',
  'gridTrade.tips_grid_balance_0_QUOTE':
    '市場價格下跌導致此網格策略下的所有訂單均變為賣單。 因此，報價資產的當前餘額現在為 0。',
  'gridTrade.tips_grid_balance_0_QUOTE_2':
    '市場價格下跌導致此網格策略下的所有訂單均變為賣單。 此外，其中一些訂單部分成交。 因此，報價資產的當前餘額為 >0。',
  'gridTrade.grid_param_err': '請輸入網格策略的參數',
  'gridTrade.tv_buy': '購買',
  'gridTrade.tv_sell': '出售',
  'gridTrade.tv_waiting': '等待中',
  'gridTrade.chain_cancel_no_need_tips': '此網格策略無需上鏈取消。',
  'gridTrade.grid_over_max_number_err':
    '已達到運行中網格策略的最大數量，無法創建新網格策略。',
  'gridTrade.preview_orders_in_graph': '顯示訂單',
  'gridTrade.greate_news': '好消息：',
  'gridTrade.min_amount_required_XXX': '最低需要 XXX',
  'gridTrade.highest_grid_apy': '最高網格年化利率',
  'gridTrade.for_the_last_7_days': '過去 7 天',
  'gridTrade.min_investment': '最低投資',
  'gridTrade.grid_need_XXX': '網格需 $XXX',
  'gridTrade.mining_need_XXX': '挖礦需 $XXX',
  'gridTrade.recommended_params_cannot_be_applied':
    '由於投資不足，無法應用推薦參數。您可以在手動模式下調整',
  'gridTrade.copy_params_to_manual': '複製參數到手動',
  'gridOrders.grid_recents': '我的最新交易',
  'gridOrders.th_created_time': '創建時間',
  'gridOrders.grid_profit': '網格利潤',
  'gridOrders.grid_cancel': '結束',
  open_orders: '未完成訂單',
  'gridOrders.tab_history_orders': '已成交訂單',
  'gridOrders.tab_trade_history': '交易歷史',
  'gridOrders.detail_current_balance': '當前餘額',
  'gridOrders.detail_ending_balance': '結束餘額',
  'gridOrders.detail_ending_balance_tips': '網格策略關閉時的資產餘額。',
  'gridOrders.detail_in_order_funds': '訂單資金：',
  'gridOrders.detail_on_hold_funds': '圈存資金（來自部分成交訂單）：',
  'gridOrders.detail_transactions': '已成交訂單數量',
  'gridOrders.detail_investment': '初始分配',
  'gridOrders.detail_running_time': '持續時間',
  'gridOrders.detail_prices': '價格區間',
  number_of_grids: '網格數量',
  'gridOrders.detail_expire_time': '到期時間',
  'gridOrders.detail_expire_time_tooltip': '此網格策略中的訂單將在到期時取消。',
  'gridOrders.detail_valid_period': '到期設定',
  'gridOrders.open_orders_sell': '賣出',
  'gridOrders.open_orders_buy': '買入',
  'gridOrders.open_orders_index': '#',
  'gridOrders.open_orders_total': '總計',
  'gridOrders.history_orders_filled': '已成交：',
  'gridOrders.history_orders_price': '價格：',
  'gridOrders.history_orders_time': '時間',
  'gridOrders.history_orders_filled_price': '平均價格',
  'gridOrders.history_orders_filled_amount': '已成交',
  'gridOrders.history_orders_filled_total': '總計',
  'gridOrders.history_orders_profit_tips':
    '利潤來自於低買高賣的一輪交易週期後的價格差異。 例如，在以4000 USDC的價格成交了購買1 ETH的網格訂單後，如果網格區間為50 USDC，則系統將自動以4050 USDC的價格下達一個新訂單，以出售1 ETH。 當該訂單被成交時，將獲得50 USDC的利潤。',
  'gridOrders.history_orders_buy_flip_order_tips_PRICE':
    '以PRICE價格完成買單後，利潤將會顯示。',
  'gridOrders.history_orders_sell_flip_order_tips_PRICE':
    '以PRICE價格完成賣單後，利潤將會顯示。',
  'gridOrders.m_history_orders_flip_order_tips_PRICE':
    '當以PRICE價格的訂單被成交時，訂單將出現在此。',
  'gridOrders.grid_cancel_title': '關閉網格策略',
  'gridOrders.grid_cancel_content': '此網格策略中的所有訂單將立即取消。',
  'gridOrders.grid_cancel_content2':
    '您正在使用此網格策略進行挖礦。 取消網格策略將放棄挖礦獎勵，並立即取消網格下的所有訂單。',
  'gridOrders.copy_grid_title': '以下網格策略參數將被複製',
  'gridOrders.copy_grid_btn': '複製到面板',
  'gridOrders.copy_grid_success': '網格策略已複製',
  'gridOrders.grid_init_funds_XXX': '初始配置金額：$XXX',
  'gridOrders.grid_init_funds_tips':
    '年化利率基於網格策略建立時的初始配置金額計算。',
  'gridOrders.tab_m_trade': '交易',
  grid_apy: '網格年化利率',
  grid_apy_tips: '僅限網格交易的年化收益率，不包括浮動利潤。',
  'gridOrders.tab_mining_profit': '挖礦年化利率',
  'gridOrders.tab_mining_profit_tips':
    '基於網格策略創建時部署的初始配置金額及其持續時間的年化利率。',
  'gridOrders.mining_rewards': '獎勵：',
  'gridOrders.open_orders_empty_tips': '請等待資料載入完成',
  'gridOrders.market_value': '市值：',
  'gridOrders.market_value_details': '詳情',
  'gridOrders.fund_details': '資金詳情',
  'gridOrders.m_in_order_funds': '訂單資金',
  'gridOrders.m_in_order_funds_tips': '此網格策略下所有未完成訂單的總資金。',
  'gridOrders.m_on_hold_funds': '圈存資金',
  'gridOrders.m_on_hold_funds_tips': '部分成交訂單結果。',
  'gridOrders.initial_value': '初始配置金額',
  'mining.my_title': '已參與流動池',
  'mining.index_desc': '建立網格策略。 透過網格交易和挖礦獲得收益。',
  'mining.apply': '新池申請',
  'mining.claimable_rewards_box': '可領取的獎勵',
  'mining.rewards_more': '以及更多',
  'mining.tab_pools': '挖礦池',
  'mining.tab_my': '我的獎勵統計',
  'mining.pools_tab_live': '上線',
  'mining.pools_tab_upcoming': '即將上線',
  'mining.pools_funds': '流動池資金',
  'mining.pools_funds_tips': '符合最低訂單金額120美元的網格訂單的總價值',
  'mining.pools_mining_funds': '挖礦資金',
  'mining.mining_apr': '流動池年化利率',
  'mining.mining_apr_tips': '根據每日獎勵和流動池資金計算的預估年化利率。',
  'mining.view_rule_link': '挖礦規則',
  'mining.pools_info_to_confirm': '待確定',
  'mining.pools_no_wait': '無可用的挖礦池',
  'mining.my_mining_funds': '我的挖礦資金',
  'mining.my_mining_rewards': '我的挖礦獎勵',
  'mining.my_th_profit_token_price': '最新價格',
  'mining.my_th_total_rewards': '歷史累積獎勵',
  'mining.my_th_24h_rewards': '24小時獎勵',
  'mining.my_grids': '我的挖礦',
  'mining.only_show_mining_grids': '僅顯示活躍',
  'mining.my_th_mining_status': '挖礦狀態',
  'mining.status_framing': '活躍',
  'mining.status_over_price': '超出價格範圍',
  'mining.status_mining_over': '挖礦已結束',
  'mining.status_grid_closed': '策略已取消',
  'mining.status_grid_expired': '策略已過期',
  'mining.empty_no_faring_grids': '沒有可挖掘的網格策略。',
  'mining.go_mining_pool': '前往挖礦池',
  'mining.go_mining': '開始挖礦',
  'mining.go_to_grid': '至網格策略',
  'mining.mining_help': '挖礦指南',
  'mining.mining_available': '符合條件',
  'mining.mining_available_tips': '訂單價值標準已滿足',
  'mining.mining_unavailable': '不符合條件',
  'mining.mining_partially_available': '部分符合條件',
  'mining.mining_unavailable_tips': '訂單價值標準未滿足',
  'mining.mining_preview': '挖礦預覽',
  'mining.mining_total_profit': '挖礦獎勵',
  'mining.mining_24h_profit': '24小時挖礦獎勵',
  'mining.profit_unable_display': 'N/A',
  'mining.mining_funds': '挖礦資金',
  'mining.mining_funds_tips':
    '此交易對的所有已符合挖礦訂單價值標準的網格策略的訂單總價值。',
  'mining.tab_mining_profit_details': '獎勵詳情',
  'mining.tab_mining_orders': '挖礦訂單',
  'mining.th_rewards': '獎勵',
  'mining.th_rewards_origin': '獎勵來源',
  'mining.th_rewards_origin_tips':
    '如果網格訂單價格落在訂單簿獎勵價格範圍內（最高買價 * 0.99 ~ 最低賣價 * 1.01），則會獲得挖礦獎勵。',
  'mining.th_rewards_origin_tips_stable':
    '如果網格訂單價格落在訂單簿獎勵價格範圍內（最高買價 ~ 最低賣價），則會獲得挖礦獎勵。',
  'mining.th_time': '時間',
  'mining.plan_title': 'ETH/USDC 池子詳情',
  'mining.phase_cur': '當前階段',
  'mining.phase_range_N_XX': '第 N 階段：XX',
  'mining.phase_index_N': '第 N 階段',
  'mining.phase_reward': '每日獎勵',
  'mining.phase_to_release': '待公佈',
  'mining.my_rewards': '我的獎勵',
  'mining.claimable_rewards': '可領取',
  'mining.locked_rewards': '不可領取',
  'mining.locker_rewards_tips': '此獎勵金額將在網格策略運行 12 小時後可領取。',
  'mining.claimed_success': '領取成功',
  'mining.claimed_tips': '獎勵將存入您的 DeGate 餘額中。',
  'mining.claimed_view_btn': '去查看',
  'mining.mining_plan': '挖礦計劃',
  'mining.phase_unpublished': '待公佈',
  'mining.all_pools': '所有池子',
  'notification.limit_desc_SELL_BASE_QUOTE_AMOUNT_PRICE':
    '以 PRICE QUOTE 賣出 AMOUNT BASE',
  'notification.limit_desc_BUY_BASE_QUOTE_AMOUNT_PRICE':
    '以 PRICE QUOTE 買進 AMOUNT BASE',
  'notification.stop_limit_desc_SELL_BASE_AMOUNT':
    '以 PRICE QUOTE 賣出 AMOUNT BASE',
  'notification.stop_limit_desc_BUY_BASE_AMOUNT':
    '以 PRICE QUOTE 買進 AMOUNT BASE',
  'notification.cancel_grid_desc_PAIR_PRICES': 'PAIR：PRICES',
  'notification.cancel_market_desc_SELL_BASE_QUOTE_AMOUNT':
    '以 QUOTE 買入 AMOUNT BASE',
  'notification.cancel_market_desc_SELL_BASE_QUOTE_TOTAL':
    '以 TOTAL QUOTE 賣出 BASE',
  'notification.cancel_market_desc_BUY_BASE_QUOTE_AMOUNT':
    '以 QUOTE 買入 AMOUNT BASE',
  'notification.cancel_market_desc_BUY_BASE_QUOTE_TOTAL':
    '以 TOTAL QUOTE 賣出 BASE',
  'notification.cancel_limit': '限價訂單已取消',
  'notification.cancel_stop_limit': '停損限價訂單已取消',
  'notification.cancel_market': '市價訂單已取消',
  'notification.cancel_grid': '網格策略已結束',
  'notification.cancel_limit_expired': '限價訂單已過期',
  'notification.cancel_stop_limit_expired': '停損限價單已過期',
  'notification.cancel_grid_expired': '網格策略已過期',
  'notification.cancel_limit_order_for_gas_desc':
    '您的訂單已經用完燃料費。 部分訂單成交，其餘訂單已被取消。',
  'notification.cancel_limit_order_for_gas_filled_amount': '已成交',
  'notification.cancel_limit_order_for_gas_amount': '數量',
  'notification.view_history_orders': '查看訂單歷史',
  'notification.cancel_market_for_depth_title': '訂單部分成交並取消',
  'notification.price_slippage_protection': '價格滑點保護',
  'notification.price_slippage_protection_desc':
    'DeGate 市價訂單自動包含 10% 的價格滑點保護，以限制在高波動性和低流動性期間的損失。 請使用限價訂單繞過此保護。',
  'notification.cancel_market_for_depth_warning':
    'DeGate 市價訂單引入了價格保護機制，使用戶能夠在市場情況具有高價格波動性和低流動性時減少損失。 如果您不想觸發價格保護機制，請使用限價訂單模式。',
  'notification.dca_plan_ended': '定投計劃已結束',
  'notification.cancel_dca_desc_PAIR': 'PAIR',
  'notification.trade_limit_partially': '限價訂單部分成交',
  'notification.trade_limit_filled': '限價訂單已成交',
  'notification.trade_market_partially': '市價訂單部分成交',
  'notification.trade_market_filled': '市價訂單已成交',
  'notification.trade_stop_limit_partially': '停損限價訂單部分成交',
  'notification.trade_stop_limit_filled': '停損限價訂單已成交',
  'notification.mobile_trade_filled_AMOUNT_TOKEN':
    '訂單已成交。 收到 AMOUNT TOKEN。',
  'notification.mobile_trade_partially_AMOUNT_TOKEN':
    '訂單部分成交。 收到 AMOUNT TOKEN。',
  'info.overview': '概覽',
  'info.accounts': '總用戶數',
  'info.pairs': '交易對',
  'info.turnover': '歷史交易量',
  'info.turnover_24': '24小時交易量',
  'info.dg_supply': 'DG流通供應量',
  'info.top_movers_no_increased': '24小時內沒有價格上漲的代幣。',
  'info.top_movers_no_decreased': '24小時內沒有價格下跌的代幣。',
  'info.top_pairs': '交易對前列',
  Pair: '交易對',
  'info.th_change': '24小時變動',
  'info.th_l_up_2': '+2% 深度',
  'info.th_l_down_2': '-2% 深度',
  'info.th_turnover_24': '24小時成交量',
  'info.tvl': '總鎖定價值',
  'm.home': '首頁',
  'm.grid': '網格',
  'm.browser_wallet': '瀏覽錢包',
  'm.choose_pair': '選擇交易對',
  'm.orderBook_default': '預設',
  'm.orderBook_bids': '買單',
  'm.orderBook_asks': '賣單',
  'm.decimals': '小數點',
  'm.lowest_price_24h': '24小時最低價',
  'm.highest_price_24h': '24小時最低價',
  'm.vol_24h': '24小時成交量',
  'm.orderbook_buy': '買入',
  'm.orderbook_sell': '賣出',
  'm.go_to_trade': '前往交易',
  'm.choose_token': '選擇代幣',
  'm.from_address': '發送地址',
  'm.to_address': '接收地址',
  'm.transfer_send': '傳送',
  'm.transfer_receive': '接收',
  'm.my_grid': '我的網格策略',
  'm.grid_profit_24': '24小時利潤',
  'm.grid_item_trades_24': '24小時交易',
  'm.grid_profit_total': '總利潤',
  'm.grid_over_prices': '超出價格範圍',
  'm.create_grid': '建立網格策略',
  'm.grid_history': '歷史記錄',
  'm.grid_empty': '沒有活躍的網格策略',
  'm.grid_tutorial': '網格教程',
  'm.grid_params_to_manual': '將參數複製到手動模式',
  'm.balance_err': '餘額不足。 可用餘額：',
  'm.preview_grid': '預覽訂單',
  last_price: '最新價格',
  'm.grid_desc':
    '網格交易是一種交易策略，它在定義的價格範圍內自動進行買入和賣出。',
  'm.view_tutorial': '查看教學',
  'm.grid_profit_tips_sell': '當此賣單完全成交時將進行計算。',
  'm.grid_profit_tips_buy': '當此買單完全成交時將進行計算。',
  'm.hot': '熱門',
  'm.all': '看全部',
  'm.vol_24': '24小時成交量',
  'm.transfer_t1': '內部',
  'm.transfer_t2': '轉帳',
  'activity.th_date': '時間',
  'activity.th_type': '類型',
  'activity.th_fee': '費用',
  'activity.th_content': '內容',
  'activity.type_register_token': '代幣上市',
  'activity.type_register_pair': '新增交易對',
  'activity.type_pay_deposit': '存款結算',
  'activity.type_reset_account': '重置資產密鑰',
  on_chain_order_cancellation: '鏈上訂單取消',
  'activity.count_N': '計數：N',
  'activity.order_desc_SELL_AMOUNT_BASE_PRICE_QUOTE':
    '以 PRICE QUOTE 價格賣出 AMOUNT BASE',
  'activity.order_market_desc_SELL_AMOUNT_BASE': '賣出 AMOUNT BASE',
  'activity.reset_status_restting': '重置中',
  'activity.to_trade': '交易',
  'dca.dca_plan': '定投計劃',
  'dca.dca_explain': '定投均價',
  'dca.daily': '每日',
  'dca.weekly': '每週',
  'dca.custom': '自訂',
  'dca.every': '每',
  'dca.amount_per_order': '每筆金額',
  'dca.price_limit': '價格限制',
  'dca.maximum_price': '最高價格',
  'dca.minimum_price': '最低價格',
  'dca.number_of_orders': '訂單數量',
  'dca.create_dca_plan': '建立定投計劃',
  'dca.max_gas_fee_per_order': '每筆最大燃料費',
  'dca.maximum_plan_order_limit_reached': '已達到計劃訂單的最大數量。',
  'dca.end_time_should_be_set_after_the_current_time':
    '結束時間應設定在目前時間之後',
  'dca.please_enter_amount_per_order': '請輸入每筆金額',
  'dca.please_enter_maximum_price': '請輸入最高價格',
  'dca.please_enter_minimum_price': '請輸入最低價格',
  'dca.order_placement_failed_open_order_limit_exceeded':
    '下單失敗：超出開放訂單限制。',
  'dca.total': '總計',
  'dca.filled': '已成交',
  'dca.received': '已接收',
  'dca.time_to_end': '剩餘時間',
  'dca.cancel_on_chain': '取消鏈上',
  'dca.filled_amount': '已成交/金額',
  'dca.status_executed': '已執行',
  'dca.status_scheduled': '已計劃',
  'dca.status_failed': '失敗',
  'dca.order_cancled_by_user': '由於用戶終止了定投計劃，訂單已取消。',
  'dca.order_cancled_by_access': '由於您對 DeGate 的存取受限，訂單已取消。',
  'dca.order_cancled_by_gas': '由於燃料費不足，下單失敗。',
  'dca.order_cancled_by_order_book': '由於訂單簿中沒有符合的訂單，下單失敗。',
  'dca.order_cancled_by_balance': '由於 DeGate 餘額不足，下單失敗。',
  'dca.order_cancled_by_min_value': '由於未達100美元的最低訂單價值，下單失敗。',
  'dca.order_cancled_by_system_error': '由於系統錯誤，下單失敗。',
  'dca.chain_cancel_no_need_tips': '此定投計畫不需要鏈上取消。',
  'dca.end_dca_plan': '結束定投計劃',
  'dca.all_orders_in_this_dca_plan_will_be_canceled_immediately':
    '此定投計畫中的所有訂單將立即取消。',
  'dca.no_active_dca_plan': '沒有活躍的定投計劃',
  'dca.time_scheduled': '計劃時間',
  'campaign.event_period': '活動週期：',
  'campaign.grid2401_time':
    '2024年1月22日，20:00:00 - 2024年1月29日，20:00:00 (UTC+8)',
  'campaign.event_has_ended': '活動已結束。',
  'campaign.current_apy': '當前年化利率（APY）',
  'campaign.grid_strategy_income': '網格策略收益 + 獎金池份額',
  'campaign.tvl_participating': '參與的總鎖倉價值',
  'campaign.share_of_tvl': '總鎖倉價值份額',
  'campaign.my_profit': '我的利潤',
  'campaign.grid_strategy_profit': '網格策略利潤',
  'campaign.share_of_prize_pool': '獎金池份額',
  'campaign.grid_strategy_profit_has_been_added_to_your_available_balance':
    '網格策略利潤已添加到您的可用餘額中。',
  'campaign.shared_income_from_usdc_prize_pool': '來自USDC獎池的共享收入',
  'campaign.is_black_tips': '您不符合獎金池分享資格。',
  'campaign.calculating': '計算中',
  'campaign.claim_after_end': '獎勵可於活動結束時領取',
  'campaign.how_to_participate': '如何參與',
  'campaign.rule': '建立網格策略並按比例分享獎金池。',
  'campaign.step1': '第1步',
  'campaign.step2': '第2步',
  'campaign.step3': '第3步',
  'campaign.grid2401_step1': '透過添加資金或交易準備好您的ETH和USDC',
  'campaign.grid2401_step2_PAIR': '為PAIR設定以下網格策略',
  'campaign.grid2401_step2_desc1_pre': '價格範圍：待公佈',
  'campaign.grid2401_step2_desc2_pre': '網格數量：待公佈',
  'campaign.copy_strategy': '複製策略',
  'campaign.grid2401_step3':
    '活動結束後，您可以在此活動頁面上領取您的收益。 請在活動結束後的30天內進行領取。',
  'campaign.what_is_grid': '什麼是網格策略',
  'campaign.notes': '加入前請注意',
  'campaign.notes_1_title': '資格：',
  'campaign.notes_1_desc':
    '只有當價格範圍和網格數量與創建時完全相同才符合網格策略的資格。',
  'campaign.notes_2_title': '限制：',
  'campaign.notes_3_title': '領取：',
  'campaign.notes_3_desc':
    '獎勵領取將在活動結束時可用，並在活動結束後的30天內有效。',
  'campaign.faq': '常見問題解答',
  'campaign.grid2401_faq_1': '1. 獎勵如何計算？',
  'campaign.grid2401_faq_2': '2. 如何取得此活動的協助？',
  'campaign.grid2401_faq_3': '3. 我持有USDT，如何取得ETH和USDC？',
  'campaign.grid2401_faq_4': '4. 透過網格策略完成的交易是否需要支付費用？',
  'campaign.grid2401_faq_4_res':
    '在DeGate中，所有掛單都是免費的。由網格策略產生的訂單都是掛單，因此在DeGate中設定網格策略是完全免費的。',
  'campaign.grid2401_faq_5': '5. 活動結束後，我的網格策略是否仍會產生效益？',
  'campaign.grid2401_faq_5_res':
    '是的，活動結束後，只要價格仍在您的網格策略範圍內，該策略就會繼續產生收益。活動結束後，您還可以調整網格策略的參數，以創建更適合自己偏好的策略 ，並繼續獲得收益。',
  'campaign.grid2401_faq_others': '其他活動細節',
  'campaign.grid2401_faq_others_1':
    '1. 每個使用者只能使用一個錢包。 如果偵測到惡意的獲取獎勵行為，DeGate 將保留取消參與者獎勵的權利。',
  'campaign.grid2401_faq_others_2':
    '2. 在活動期間，超出範圍的網格也將計入權重計算。',
  'campaign.grid2401_faq_others_3':
    '3. 在極端情況下，例如市場波動，DeGate 保留提前結束活動的權利。',
  'campaign.grid2401_faq_others_4': '4. 活動結束後未領取的獎勵將取消。',
  'campaign.invest_max_5000': '最高投資額為 5000 美元',
  'campaign.invest_mininum': '最低投資額',
  'airdrop.create_airdrop': '創建空投',
  'airdrop.important_note': '重要提示：任何人都可以無需審核地創建空投',
  'airdrop.my_airdrop': '我的空投',
  'airdrop.time_limited': '限時',
  'airdrop.no_airdrop': '目前沒有可領取的空投',
  'airdrop.claim_airdrop': '領取空投',
  'airdrop.recipients_number': '地址總數',
  'airdrop.total_amount': '總金額',
  'airdrop.retrieve': '取回',
  'airdrop.unclaimed': '未領取',
  'airdrop.retrieve_successful': '取回成功',
  'airdrop.claim_successful': '領取成功',
  'airdrop.retrieve_unclaimed_airdrop': '取回未領取空投',
  'airdrop.airdrop_token': '空投幣種',
  'airdrop.token_not_meet_criteria': '幣種不符合空投的要求',
  'airdrop.airdrop_list': '空投列表',
  'airdrop.download_template': '下載模板',
  'airdrop.click_or_drag_upload_list': '點擊或拖動上傳列表',
  'airdrop.validation_passed': '已驗證',
  'airdrop.must_earlier_than_end_time': '必須早於結束時間',
  'airdrop.cannot_more_than_2_years_from_now': '從現在起最多2年',
  'airdrop.cannot_parse_file': '無法解析文件，請使用列表模板。',
  'airdrop.format_requirement_not_met': '不符合格式要求',
  'airdrop.view_error_repost': '查看錯誤報告',
  'airdrop.error_report': '錯誤報告',
  'airdrop.line': '行數',
  'airdrop.reason': '原因',
  'airdrop.duplicated_address': '重複的地址',
  incorrect_address_format: '地址格式不正確',
  'airdrop.incorrect_amount_format': '數量格式不正確',
  'airdrop.airdrop_plan_created': '空投計劃已創建',
  'airdrop.max_50000': '最多50000個地址',
  'airdrop.upload_file_rule': '僅支持CSV格式的附件。',
  'airdrop.to_check_airdrop_eligibility': '請連接錢包以查看空投',
  'airdrop.complete_initialization_to_claim_airdrops': '完成初始化以領取空投',
  'airdrop.complete_initialization_to_view_airdrops': '完成初始化以查看空投',
  'airdrop.you_are_eligible_for': '您可領取：',
  'airdrop.and_more': '以及更多',
  'airdrop.congratulations': '恭喜!',
  'airdrop.airdrop_fee': '空投費',
  'countdown.countdown_plan': '首發計劃',
  'countdown.create_countdown_plan': '創建首發計劃',
  'countdown.my_countdown_plan': '我的創建',
  'countdown.countdown_trading_pair': '倒計時交易對',
  'countdown.countdown_display': '顯示倒計時',
  'countdown.token_not_meet_criteria': '幣種不符合首發要求',
  'countdown.countdown_tips': '勾選的交易對會在交易頁面顯示倒計時',
  'countdown.max_30_days': '從現在起最多30天',
  'countdown.review_countdown_plan': '檢查首發計劃',
  'countdown.countdown_fee': '首發費',
  'countdown.countdown_plan_created': '首發計劃已創建',
  'countdown.trading_will_start_in': '交易開始倒計時',
  'countdown.trading_will_start_at_YYYY': '交易將在YYYY後開放',
  'countdown.cannot_earlier_than_current_time': '不能早於當前時間',
  'dca.price_limit_buy_tips':
    '啟用後，您的買單僅在等於或低於最高價格時執行。此功能與零費用功能相容。',
  'dca.price_limit_sell_tips':
    '啟用後，您的賣單僅在等於或高於最低價格時執行。此功能與零費用功能相容。',
  'dca.zero_fee': '零費用',
  'dca.zero_fee_buy_tips':
    '啟用「零費用」後，定投訂單將僅限掛單。每個買入價格將設在下單後的訂單簿中最高的出價。請注意，您的訂單可能不會立即或根本不會成交。',
  'dca.zero_fee_sell_tips':
    '啟用「零費用」後，定投訂單將僅限掛單。每個賣出價格將設在下單後的訂單簿中最低的要價。請注意，您的訂單可能不會立即或根本不會成交。',
  'dca.order_canceled_post_only_buy_failed':
    '因訂單簿缺乏買單，無法確定您訂單的買價而下單失敗。',
  'dca.order_canceled_post_only_sell_failed':
    '因訂單簿缺乏賣單，無法確定您訂單的賣價而下單失敗。',
  start_time_cannot_before_current_time: '開始時間不能早於目前時間',
  start_time_must_before_end_time: '開始時間必須早於結束時間',
  list_token: '上幣',
  contract_address_does_not_exist: '合約地址不存在',
  token_listed: '此代幣已上架',
  XXX_is_listed: '正在上幣XXX',
  view_progress: '查看進度',
  pair_create_tips: '交易對可以在DeGate上立即添加，無需任何人批准。',
  base_token: '基礎代幣',
  quote_token: '報價代幣',
  existing_pair: '交易對已存在',
  trade_now: '立即交易',
  pair_XXX_added_successfully: 'XXX添加成功',
  qty_per_grid: '每個網格的數量',
  grid_minimum_not_reached: '未達到最小值',
  total_profit: '總收益',
  total_apy: '總收益率',
  float_profit: '浮動盈利',
  grid_profit_24h: '24小時網格利潤',
  pnl: '损益',
  eligibility: '合格條件',
  rewards: '獎勵',
  view_mining_statistics: '查看挖礦數據',
  your_entry: '您的輸入',
  refunded: '已返還',
  large_price_spread: '訂單簿價差大',
  large_price_spread_tips:
    '訂單簿顯示最低賣出和最高買入價格之間存在較大差距，存在損失風險。 建議使用雙資產模式進行投資。',
  continue_anyway: '仍然繼續',
  insufficient_order_book_liquidity_decrease_investment:
    '訂單簿流動性不足。 減少投資額。',
  initial_buy: '初始購買',
  closing_sell: '關倉賣出',
  No: '否',
  DCA_TRIGGER_FAIL_TIPS_PRICE_XXX:
    '如果在執行時<b>$XXX的價格低於$PRICE</b>，定投訂單將失敗。',
  zero_fee: '零費用',
  minimum_order_value_is_VALUE: '最小訂單價值為<b>$VALUE</b>。',
  Note: '提示',
  Continue: '繼續',
  estimated_apy: '預估年化收益率',
  based_on_data_from_last_7_days: '基於過去7天的數據',
  top_gainers_24h: '24小时涨幅榜',
  top_losers_24h: '24小时跌幅榜',
  listed_tokens: '已上架币种',
  vol: '成交量',

  let_s_go: '前往',
  reject: '拒絕',
  maximum_N_due_to_price_ticks: '由於價格精度限制，最大值為N',
  Saved: '已保存',
  minimum_order_value_$100_$QUOTE: '最小訂單價值為<b>$100 $QUOTE</b>',
  minimum_order_value_$AMOUNT_$QUOTE_$100: '最小訂單價值為<b>$AMOUNT $QUOTE</b>(约 $100)',
  no_restriction_with_market_order: '<b>市價單</b>無該限制',
  go_to_market_order: '前往市價單',
  Mining_Eligibility: '挖礦資格',
  How_to_earn_mining_rewards: '如何賺取挖礦獎勵',
  Order_Value: '訂單價值',
  'mining.mining_tips_BV_BASE_QV_QUOTE': '在策略創建時，網格訂單必須至少為<b>BV BASE</b>或<b>QV QUOTE</b>',
  'mining.mining_tips_QV_QUOTE': '在策略創建時，網格訂單必須至少為<b>QV QUOTE</b>',
  Mining_Price_Range: '挖礦價格範圍',
  'mining.status_over_price_tips': '網格訂單價格必須在<b>挖礦價格範圍之內</b>，即：訂單簿最高買入價格*0.99 ～ 訂單簿最低賣出價格*1.01。',
  'mining.status_over_price_tips_stable': '網格訂單價格必須在<b>挖礦價格範圍之內</b>，即：訂單簿最高買入價格 ～ 訂單簿最低賣出價格。',
  Eligible_for_Mining: '符合挖礦條件',
  Mining_Satus: '挖礦狀態',
  Mining_Satus_Mining: '挖礦中',
  Mining_Satus_Standby: '等待中',
  Mining_Satus_Ineligible: '不符合要求',
  mining_price_range: '挖礦獎勵範圍',
  rewards_tips_stable: '策略創建時滿足挖礦訂單價值的網格訂單，如果其價格在挖礦價格範圍之內可以獲得挖礦獎勵（最高買單價格 ~ 最低賣單價格）',
  rewards_tips: '策略創建時滿足挖礦訂單價值的網格訂單，如果其價格在挖礦價格範圍之內可以獲得挖礦獎勵（最高買單價格*0.99 ~ 最低賣單價格*1.01）',
  wrap: '跨鏈',
  Wrap: '跨鏈',
  websites_for_more_information: '更多資訊請訪問以下網站',
  official_site: '官方網站',
  wrap_site: '跨鏈網站',
  tips_third_party_site: '您即將離開DeGate並進入第三方網站：',
  wrap_unwrap: '跨鏈兌換',
};
export default zhTW;
