const en = {
  language: 'en-US',
  choose_token: 'Choose Token',
  recipient: 'Recipient',
  recent: 'Recent',
  price: 'Price',
  amount: 'Amount',
  available: 'Available',
  gas_fee: 'Gas Fee',
  Send: 'Send',
  Send_ETH: 'Send ETH',
  Internal_Transfer: 'Internal Transfer',
  transfer_tips:
    'Transfer token to another address within the DeGate Protocol.',
  transfer_ETH: 'Internal Transfer ETH',
  btn_max: 'Max',
  degate_insufficient_balance: 'Insufficient balance',
  max_digits_exceeded: 'Max digits exceeded',
  wallet_insufficient_fees: 'Insufficient balance in wallet',
  deGate_insufficient_fees: 'Insufficient DeGate Balance to pay for Gas Fee',
  token_search_placeholder: 'Search token, contract address',
  token: 'Token',
  degate_balance: 'DeGate Balance',
  tips_gas:
    'The gas fee for executing this on-chain transaction will be deducted directly from your DeGate balance.',
  tips_gas2:
    'Gas Fee covers on-chain costs for trade settlements. Excess fees are refunded.',
  Close: 'Close',
  Help: 'Help',
  no_token: 'Token Not Found',
  chain_1: 'Mainnet',
  chain_3: 'Ropsten',
  chain_4: 'Rinkeby',
  chain_5: 'Goerli',
  chain_42: 'Kovan',
  chain_42161: 'Arbitrum',
  chain_10: 'Optimism',
  Cancel: 'Cancel',
  go_back: 'Go Back',
  Back: 'Back',
  copied: 'Copied',
  Confirm: 'Confirm',
  Create: 'Create',
  Abort: 'Abort',
  btn_confirm: 'Close',
  btn_got_it: 'Got it',
  wallet_cancelled_tips: 'You canceled the signature',
  connect_ledger: 'Connect Ledger',
  ledger_disconnect:
    "Failed to execute 'transferOut' on 'USBDevice': The device was disconnected.",
  wallet_tips: 'Please approve in browser wallet',
  wallet_ledger_tips: 'Please approve in Ledger hardware',
  wallet_metamask_tips: 'Please approve in MetaMask',
  wallet_walletconnect_tips:
    'Please go to your wallet to approve with WalletConnect',
  view_asset_key: 'View Asset Key',
  export_key_warning:
    'A leak of the Asset Key can result in asset loss. Please ensure its safekeeping.',
  export_key_confirm_btn: 'Continue to View',
  btn_buy_ETH: 'Buy ETH',
  btn_sell_ETH: 'Sell ETH',
  around: '～ ',
  need_help: 'Help',
  time_now: 'now',
  time_1_minute: '1 minute',
  time_1_hour: '1 hour',
  time_1_day: '1 day',
  time_1_year: '1 year',
  time_M_minutes: 'M minutes',
  time_M_m: 'Mm',
  time_H_hours: 'H hours',
  time_H_h: 'Hh',
  time_D_days: 'D days',
  time_D_d: 'Dd',
  time_Y_years: 'Y years',
  time_Y_y: 'Yy',
  personal_sign_reason: 'Possible Reasons',
  personal_sign_reason1: '1. MetaMask is connected to hardware wallet',
  personal_sign_reason2: '2. MetaMask version is outdated',
  personal_sign_reason3: '3. Others',
  personal_sign_btn: 'Sign Again',
  switch_wallet: 'Switch Account',
  switch_walletConnect_tips1:
    'If you wish to switch to another account in the same wallet software, please perform it directly from the wallet and cancel this request.',
  switch_walletConnect_tips2:
    'If you wish to use WalletConnect through a different wallet software, the system will disconnect from the existing connection first.',
  switch_walletConnect_continue: 'Disconnect and Continue',
  switch_metamask_tips: 'Please go to MetaMask to switch account.',
  switch_browser_wallet_tips: 'Please switch account in browser wallet.',
  period_expired: 'Expired',
  period_D_day_H_hour: 'Dd Hh',
  period_H_hour_M_minute: 'Hh Mm',
  login_success: 'Connect Success',
  advanced: 'Advanced',
  edit: 'Edit',
  save: 'Save',
  speed_up: 'Speed Up',
  continue: 'Continue',
  Submit: 'Submit',
  icon_copy: 'Copy address',
  icon_view_explorer: 'View on block explorer',
  upcoming_lock_tips:
    'Due to a period of inactivity, the Signature-free mode will be turned off for your security.',
  auto_locked_tips:
    'For your security, the Signature-free mode has been turned off after 15 minutes of inactivity.',
  keep: 'Keep',
  turn_off_now: 'Turn off Now',
  turn_on: 'Turn on',
  turn_on_signature_free_mode: 'Turn on Signature-free mode',
  turn_on_signature_free_mode_success: 'Signature-free Mode On',
  max_XXX: 'Max XXX',
  min_XXX: 'Min XXX',
  common_err: 'Something went wrong. Please try again later.',
  input_auto_corrected_tips:
    'Auto corrected your input after exceeding the maximum number of digits',
  maximum_decimal_reached: 'Maximum decimal places reached',
  verify_ownership: 'Verify Ownership',
  execute: 'Execute',
  sign_step1: 'Complete in Your Wallet',
  sign_step2: 'Complete 2nd Signature',
  sign_step3: 'Complete 3nd Signature',
  place_order: 'Place Order',
  create_spot_order: 'Place Order',
  create_grid_strategy: 'Create Grid Strategy',
  create_DCA_plan: 'Create DCA Plan',
  cancel_order: 'Cancel Order',
  end_grid_strategy: 'End Grid Strategy',
  end_DCA: 'End DCA Plan',
  Seconds: 'Seconds',
  complete_in_seconds: 'Complete in seconds',
  complete_in: 'Complete in ',
  me: 'me',
  eth_code_tips: 'Native token of Ethereum. No token contract address.',
  total: 'Total',
  order_amount: 'Order Amount',
  operation_has_expired: 'Operation has expired',
  Approve: 'Approve',
  tips_hide_forever: 'Don’t show again',
  Tips: 'Tip',
  Note: 'Note',
  Summary: 'Summary',
  Orders: 'Orders',
  Side: 'Side',
  Sell: 'Sell',
  Buy: 'Buy',
  now: 'Now',
  order_type: 'Order Type',
  limit_order: 'Limit',
  market_order: 'Market',
  required: 'Required',
  check_address_format: 'Check address format',
  start_time: 'Start Time',
  end_time: 'End Time',
  None: 'None',
  time_out: 'Time out. Please retry.',
  deposit_ETH: 'Add ETH',
  'grid.confirm_grid': 'Confirm Grid Strategy',
  'grid.initial_investment': 'Investment',
  'grid.price_range': 'Price Range',
  'grid.grid_level': 'Number of Grids',
  'grid.grid_volume': 'Qty per Grid',
  'grid.profit_per_grid': 'Profit per Grid',
  'grid.expired_in': 'Expire in',
  'grid.replace_modal_title': 'Grid Strategy Updated',
  'grid.replace_modal_content':
    'Due to recent changes in the order book, the original grid strategy has been updated as follows.',
  'grid.replace_modal_pre': 'Before',
  'grid.replace_modal_next': 'After',
  'grid.replace_modal_err':
    'Insufficient balance to create the grid strategy. Please return to edit the grid parameters.',
  'ledger.connect_rule_1': '1. Connect Ledger to your device',
  'ledger.connect_rule_2': '2. Unlock in Ledger',
  'ledger.connect_rule_3': '3. Open Ethereum app in Ledger',
  'ledger.connect_rule_4':
    '4. Make sure Blind Signing/Contract Data and Browser Support are enabled',
  'ledger.unable_to_approve': 'Unable to Approve',
  'ledger.webusb_1tab_tips_desc_1':
    'This browser only supports a single "browser tab" for Ledger approval. Unable to approve as another tab is utilizing this feature.',
  'ledger.webusb_1tab_tips_desc_2':
    'Please try replugging the Ledger to restart the operation.',
  'ledger.locked_tips':
    'Please unlock Ledger, open the Ethereum app, and approve.',
  'ledger.account_not_match':
    'Wrong Ledger wallet detected. Please connect to the correct Ledger.',
  'ledger.ledger_choose_address': 'Choose an Address',
  'ledger.address': 'Address',
  'ledger.connect': 'Connect',
  'ledger.un_supported_title':
    'Ledger wallet connection not supported by current Browser',
  'ledger.un_supported_desc': 'Recommend using Chrome and Edge browsers.',
  'ledger.confirm_gas_fee': 'Confirm Gas Fee',
  'ledger.confirm_gas_fee_desc':
    'You are about to initiate a transaction on Ethereum, please confirm:',
  'ledger.max_gas_fee': 'Max Gas Fee',
  'ledger.edit_gas_fee': 'Edit Gas Fee',
  'ledger.max_fee': 'Gas Price (Gwei)',
  'ledger.max_base_fee': 'Max Base Fee (Gwei)',
  'ledger.max_base_fee_tips':
    'When your transaction gets included in the block, any difference between your max base fee and the actual base fee will be refunded.',
  'ledger.priority_fee': 'Priority Fee (Gwei)',
  'ledger.priority_fee_tips':
    'Priority fee (aka “miner tip”) goes directly to miners and incentivizes them to prioritize your transaction.',
  'ledger.gas_limit': 'Gas Limit:',
  'ledger.tx_speed_up_title': 'Speed Up Transaction',
  'ledger.tx_speed_up_desc':
    'You are about to speed up a transaction on Ethereum, please confirm:',
  'ledger.tx_cancel_title': 'Cancel Transaction',
  'ledger.tx_cancel_desc':
    'You are about to cancel a transaction on Ethereum, please confirm:',
  'ledger.fee_minimum_xxx': 'Cannot be less than XXX',
  'ledger.ledger_app_version_tips':
    "Update your Ledger's Ethereum app to version 1.9.19 or higher to preview the message before signing.",
  'operations.register_pair': 'Add Trading Pair',
  'operations.chain_cancel': 'Cancel Order On-Chain',
  'operations.chain_cancel_title':
    'This order cancellation request will be posted on-chain to guarantee the cancellation of the order.',
  'operations.chain_cancel_confirm': 'Confirm Cancel',
  'operations.chain_cancel_confirm_tips':
    'On-chain cancellation will incur a gas fee. Do you wish to proceed?',
  'operations.chain_cancel_grid_text_N':
    '<b>N orders</b> in this grid strategy will be submitted for on-chain cancellation.',
  'operations.chain_cancel_grid_gas_AMOUNT_ETH':
    'Please confirm again the on-chain cancellation gas fee of <b>AMOUNT ETH</b>.',
  'operations.claim_title': 'Claim Rewards',
  'operations.claim_desc':
    'Rewards will be credited to your DeGate balance via Internal Transfer, with gas fees deducted directly from the reward amount.',
  'operations.claim_desc_others':
    'This claim will be credited to your DeGate Balance through an internal transfer.',
  'operations.claim_rewards': 'Available Rewards',
  'operations.claim_err_amount': 'Insufficient amount available for claim',
  'operations.claim': 'Claim',
  'operations.Claimable': 'Claimable',
  'operations.Unclaimed': 'Unclaimed',
  'operations.claim_mining_rewards': 'Claim Mining Rewards',
  'operations.claim_rewards_desc':
    'Rewards will be sent to your account after deduction of gas fees',
  'operations.pay_deposit': 'Settlement',
  'operations.pay_deposit_title': 'Pending Payment',
  'operations.pay_deposit_desc_XXX_ETH':
    'You have a pending fund addition of XXX ETH.',
  'operations.pay_deposit_select_account': 'Pay From',
  Wallet_Balance: 'Wallet Balance',
  'operations.pay_deposit_tips_XXX_ETH': 'Pay XXX ETH',
  'operations.reset_account': 'Reset Asset Key',
  'operations.reset_desc':
    "The Asset Key resides in your browser cache. If your local environment's security is in question, please reset asset key.",
  'operations.reset_warning':
    'All operations, such as trading, sending, or internal transferring, are suspended during the reset.',
  'operations.reset_estimated_time': 'Estimated Time',
  'operations.reset_order_tips':
    'Once the reset is initiated, all open orders and grid strategies will be canceled.',
  'operations.reset_order_tips_btn2': 'Cancel',
  'operations.claim_dg_rewards': 'Claim DG Rewards',
  'operations.claim_REBASE': 'Claim REBASE',
  'operations.claim_REBASE_desc':
    'REBASE will be sent to your DeGate Balance via internal transfer.',
  'operations.claim_REBASE_tips':
    'Unclaimed REBASE is factored into the yield calculation.',
  'operations.view_yield_history': 'View Yield History',
  'operations.cancel_orders_on_chain': 'Cancel Orders On-chain',
  'operations.chain_cancel_dca_text_N':
    '<b>N orders</b> in this DCA plan will be submitted for on-chain cancellation.',
  'operations.confirm_cancel_gas_AMOUNT_ETH':
    'Please double confirm the on-chain cancellation gas fee of <b>AMOUNT ETH</b>.',
  'trade.confirm_order': 'Confirm Order',
  'trade.stop_limit_order': 'Stop Limit',
  'trade.stop_limit_order_sell_desc_STOPPRICE_QUOTE_PRICE_BASEAMOUNT_BASE':
    'stop_limit_order_sell_desc_STOPPRICE_QUOTE_PRICE_BASEAMOUNT_BASE',
  'trade.stop_price': 'Stop Price',
  'trade.limit_price': 'Limit Price',
  'trade.market_price': 'Market Price',
  'trade.total': 'Total',
  'trade.pay': 'Pay',
  'trade.receive': 'Receive',
  'trade.hide_pair_confirm': "Don't show again for this pair",
  'trade.pay_the_following_amount_to_place_order':
    'Pay the following amount to place order:',
  'trade.flow_of_funds': 'flow of funds',
  'trade.flow_of_funds_tip2':
    'Your order has been placed. Order funds will go to your DeGate Balance, instead of your wallet balance.',
  'trade.pay_to_place_order': 'Pay to Place Order',
  'trade.pay_xxx_USDC_to_place_order': 'Pay xxx USDC to Place Order',
  'trade.deposit_type': 'Method',
  'trade.deposit_type_standard': 'Standard',
  'transfer.transfer_1_eth_ACCOUNT': 'Transfer 1 ETH to ',
  'transfer.internal_transfer_address_new_tips':
    'This address has no prior DeGate history. Transferring to this address will require additional gas fees.',
  'transfer.address_placeholder': 'Enter address',
  'transfer.to_new_account_tips':
    'This address has no prior DeGate history. As the first asset receipt initiates additional on-chain data usage, performing this internal transfer will incur extra gas fees.',
  'transfer.confirm_internal_transfer': 'Confirm Internal Transfer',
  'transfer.internal_transfer_address_oneself_tips':
    'Internal transfer to yourself is not supported.',
  'transfer.transfer_max_err_XXX_USDT':
    'Internal transfer is limited to XXX USDT per transfer',
  'transfer.before': 'Before',
  'transfer.after': 'After',
  'transfer.recipient_cex_warning':
    'Warning: Please do not transfer to Centralized Exchange. You will lose the funds.',
  'withdraw.withdraw_max_tips': 'System limit exceeded',
  'withdraw.address_placeholder': 'Enter Ethereum address',
  'dca.confirm_dca_plan': 'Confirm DCA Plan',
  'dca.number_of_orders': 'Number of Orders',
  'dca.amount_per_order': 'Amount per Order',
  'dca.time_scheduled': 'Time Scheduled',
  'dca.creating_the_plan': 'Creating the Plan...',
  'dca.maximum_price': 'Maximum Price',
  'dca.minimum_price': 'Minimum Price',
  'dca.do_not_close': 'Do NOT close or refresh this page.',
  'dca.frequency': 'Frequency',
  total_amount: 'Total Amount',
  'dca.daily': 'Daily',
  'dca.weekly': 'Weekly',
  'dca.every': 'Every ',
  'airdrop.review_airdrop': 'Review Airdrop',
  'airdrop.create_airdrop': 'Create Airdrop',
  'airdrop.recipients_number': 'No. of Recipients',
  'airdrop.airdrop_fee': 'Airdrop Fee',
  'airdrop.pay_airdrop_fee': 'Pay Airdrop Fee',
  'airdrop.send_airdrop_token': 'Send Airdrop Token',
  'airdrop.claim_airdrop': 'Claim Airdrop',
  'airdrop.retrieve': 'Retrieve',
  'countdown.create_countdown_plan': 'Create Countdown Plan',
  'countdown.countdown_display': 'Countdown Display',
  'countdown.max_30_days': 'Cannot be more than 30 days from now',
  'countdown.review_countdown_plan': 'Review Countdown Plan',
  'countdown.countdown_fee': 'Countdown Fee',
  grid_slippage_over_2_tips_SLIPPAGE_QUOTE_BASE:
    'The system will initially exchange a portion of QUOTE for BASE using a market order, with an estimated slippage of SLIPPAGE.',
  grid_slippage_over_5_tips_SLIPPAGE_QUOTE_BASE:
    'The system will initially exchange a portion of QUOTE for BASE using a market order, with an estimated slippage of SLIPPAGE. Investing with Dual Asset mode is recommended.',
  connected: 'Connected',
  browser_wallet: 'Browser Wallet',
  Convert_to_YYY: 'Convert to YYY',
  sell_XXX_to_YYY: 'Do you want to sell your XXX into YYY at market price?',
  you_sell: 'You sell',
  you_receive: 'You receive',
  est_slippage: 'Est. Slippage',
  No: 'No',
  closing_sell: 'Closing Sell',
  connect_wallet: 'Connect Wallet',
  Add: 'Add',
};
export default en;
