const zh = {
  language: 'zh-CN',
  choose_token: '选择币种',
  recipient: '接收方',
  recent: '最近使用',
  price: '价格',
  amount: '数量',
  available: '可用',
  gas_fee: '矿工费',
  Send: '发送',
  Send_ETH: '发送ETH',
  Internal_Transfer: '内部转账',
  transfer_tips: '在DeGate协议内将代币转账到其他地址',
  transfer_ETH: '内部转账ETH',
  btn_max: '最大',
  degate_insufficient_balance: '余额不足',
  max_digits_exceeded: '超出最大位数',
  wallet_insufficient_fees: '钱包余额不足',
  deGate_insufficient_fees: 'DeGate余额不足以支付矿工费',
  token_search_placeholder: '搜索币种、合约地址',
  token: '币种',
  degate_balance: 'DeGate余额',
  tips_gas: '执行交易上链所需的矿工费将会从您的DeGate余额扣除',
  tips_gas2: '矿工费用于支付交易的上链结算。多余的费用会被退还。',
  Close: '关闭',
  Help: '帮助',
  no_token: '未找到此币种',
  chain_1: 'Mainnet',
  chain_3: 'Ropsten',
  chain_4: 'Rinkeby',
  chain_5: 'Goerli',
  chain_42: 'Kovan',
  chain_42161: 'Arbitrum',
  chain_10: 'Optimism',
  Cancel: '取消',
  go_back: '返回',
  Back: '返回',
  copied: '已复制',
  Confirm: '确认',
  Create: '创建',
  Abort: '放弃',
  btn_confirm: '我知道了',
  btn_got_it: '我知道了',
  wallet_cancelled_tips: '您已取消签名',
  connect_ledger: '连接Ledger',
  ledger_disconnect:
    "Failed to execute 'transferOut' on 'USBDevice': The device was disconnected.",
  wallet_tips: '请到钱包内授权',
  wallet_ledger_tips: '请到Ledger硬件中授权',
  wallet_metamask_tips: '请到MetaMask授权',
  wallet_walletconnect_tips: '请到WalletConnect钱包授权',
  view_asset_key: '查看资产密钥',
  export_key_warning: '泄露资产密钥将导致资产丢失，请务必妥善保管',
  export_key_confirm_btn: '继续查看',
  btn_buy_ETH: '买入ETH',
  btn_sell_ETH: '卖出ETH',
  around: '约',
  need_help: '帮助',
  time_now: '刚刚',
  time_1_minute: 'M分钟',
  time_1_hour: '1小时',
  time_1_day: '1天',
  time_1_year: '1年',
  time_M_minutes: 'M分钟',
  time_M_m: 'M分钟',
  time_H_hours: 'H小时',
  time_H_h: 'H小时',
  time_D_days: 'D天',
  time_D_d: 'D天',
  time_Y_years: 'Y年',
  time_Y_y: 'Y年',
  personal_sign_reason: '可能原因',
  personal_sign_reason1: '1. Metamask连接了硬件钱包',
  personal_sign_reason2: '2. Metamask版本过低',
  personal_sign_reason3: '3. 其他原因',
  personal_sign_btn: '重新签名',
  switch_wallet: '切换账户',
  switch_walletConnect_tips1:
    '如果您想切换到当前钱包软件里的其他账户，请取消并到钱包内直接操作。',
  switch_walletConnect_tips2:
    '如果您想要更换到其他钱包软件来使用WalletConnect，系统会先断开当前钱包连接。',
  switch_walletConnect_continue: '断开连接并继续',
  switch_metamask_tips: '请在Metamask切换账户',
  switch_browser_wallet_tips: '请在手机钱包切换账户',
  period_expired: '已过期',
  period_D_day_H_hour: 'D天H小时',
  period_H_hour_M_minute: 'H小时M分钟',
  login_success: '已连接至钱包',
  advanced: '高级',
  edit: '编辑',
  save: '保存',
  speed_up: '加速',
  continue: '继续',
  Submit: '提交',
  icon_copy: '复制地址',
  icon_view_explorer: '区块链浏览器查看',
  upcoming_lock_tips: '您似乎离开了一会。为确保安全，即将关闭免签名模式。',
  auto_locked_tips: '您已离开超过15分钟，为确保安全，已为您关闭免签名模式。',
  keep: '保留',
  turn_off_now: '立即关闭',
  turn_on: '开启',
  turn_on_signature_free_mode: '开启免签名模式',
  turn_on_signature_free_mode_success: '免签名模式已开启',
  max_XXX: '最大为XXX',
  min_XXX: '最小为XXX',
  common_err: '似乎出了点问题，请稍后重试',
  input_auto_corrected_tips: '超过了最大位数限制，您的输入已被自动修改',
  maximum_decimal_reached: '超出最大小数位',
  verify_ownership: '验证身份',
  execute: '执行',
  sign_step1: '请到钱包内签名',
  sign_step2: '完成第二次签名',
  sign_step3: '完成第三次签名',
  place_order: '确认下单',
  create_spot_order: '创建订单',
  create_grid_strategy: '创建网格策略',
  create_DCA_plan: '创建定投计划',
  cancel_order: '取消订单',
  end_grid_strategy: '关闭网格策略',
  end_DCA: '关闭定投计划',
  Seconds: '立即',
  complete_in_seconds: '立即完成',
  complete_in: '到账时间',
  me: '我',
  eth_code_tips: '以太坊原生代币，无合约地址',
  total: '总计',
  order_amount: '订单数量',
  operation_has_expired: '操作已过期',
  Approve: '授权',
  tips_hide_forever: '下次不再显示',
  Tips: '提示',
  Note: '提示',
  Summary: '摘要',
  Orders: '订单',
  Side: '方向',
  Sell: '卖出',
  Buy: '买入',
  now: '现在',
  order_type: '订单类型',
  limit_order: '限价',
  market_order: '市价',
  required: '必填',
  check_address_format: '请检查地址格式',
  start_time: '开始时间',
  end_time: '结束时间',
  None: '无',
  time_out: '超时请重试',
  deposit_ETH: '划入ETH',
  'grid.confirm_grid': '确认网格策略',
  'grid.initial_investment': '初始投入',
  'grid.price_range': '价格区间',
  'grid.grid_level': '网格数',
  'grid.grid_volume': '每格数量',
  'grid.profit_per_grid': '每格收益',
  'grid.expired_in': '有效期',
  'grid.replace_modal_title': '网格策略已更新',
  'grid.replace_modal_content':
    '由于订单簿发生变化，原始的网格策略已按照以下方式进行更新。',
  'grid.replace_modal_pre': '更新前',
  'grid.replace_modal_next': '更新后',
  'grid.replace_modal_err': '余额不足，无法创建网格策略，请返回修改',
  'ledger.connect_rule_1': '1. 将Ledger接入当前设备',
  'ledger.connect_rule_2': '2. 在Ledger内解锁',
  'ledger.connect_rule_3': '3. 在Ledger内打开Ethereum app',
  'ledger.connect_rule_4':
    '4. 确认已开启Blind Signing/Contract Data和Browser Support功能',
  'ledger.unable_to_approve': '无法完成授权',
  'ledger.webusb_1tab_tips_desc_1':
    '您正使用的浏览器仅支持单个“浏览器标签页”进行Ledger授权，其他标签页已占用该功能，因此无法完成授权。',
  'ledger.webusb_1tab_tips_desc_2': '请尝试拔出Ledger后插回，并重新发起操作。',
  'ledger.locked_tips': '请解锁Ledger，打开Ethereum app并完成授权',
  'ledger.account_not_match': '检查到错误的Ledger钱包，请连接至正确的Ledger',
  'ledger.ledger_choose_address': '选择地址',
  'ledger.address': '地址',
  'ledger.connect': '连接',
  'ledger.un_supported_title': '当前浏览器不支持Ledger连接',
  'ledger.un_supported_desc': '推荐使用Chrome, Edge浏览器',
  'ledger.confirm_gas_fee': '确认矿工费',
  'ledger.confirm_gas_fee_desc': '您即将在以太坊上发起交易，请确认：',
  'ledger.max_gas_fee': '最大矿工费',
  'ledger.edit_gas_fee': '编辑矿工费',
  'ledger.max_fee': '矿工费 (Gwei)',
  'ledger.max_base_fee': 'Max Base Fee (Gwei)',
  'ledger.max_base_fee_tips':
    '交易入块后，max base fee与实际base fee的差值将会退还。',
  'ledger.priority_fee': 'Priority Fee (Gwei)',
  'ledger.priority_fee_tips':
    'Priority fee（又名“矿工小费”）直接支付给矿工，并激励他们优先考虑打包您的交易。',
  'ledger.gas_limit': 'Gas Limit:',
  'ledger.tx_speed_up_title': '加速交易',
  'ledger.tx_speed_up_desc': '您即将在以太坊上加速交易，请确认：',
  'ledger.tx_cancel_title': '取消交易',
  'ledger.tx_cancel_desc': '您即将在以太坊上取消交易，请确认：',
  'ledger.fee_minimum_xxx': '不能少于XXX',
  'ledger.ledger_app_version_tips':
    '为了查看待签名消息，请升级您的Ledger Ethereum app至v1.9.19或更高',
  'operations.register_pair': '添加交易对',
  'operations.chain_cancel': '链上取消订单',
  'operations.chain_cancel_title': '取消订单请求将会被发到链上以确保取消成功。',
  'operations.chain_cancel_confirm': '确认取消',
  'operations.chain_cancel_confirm_tips': '链上取消需支付矿工费，是否继续？',
  'operations.chain_cancel_grid_text_N':
    '此网格策略中的<b>N个订单</b>的取消请求将被提交到链上',
  'operations.chain_cancel_grid_gas_AMOUNT_ETH':
    '请再次确认链上取消的矿工费为 <b>AMOUNT ETH</b>',
  'operations.claim_title': '领取奖励',
  'operations.claim_desc':
    '奖励将以内部转账计入您的DeGate余额。矿工费直接从奖励数量中扣除。',
  'operations.claim_desc_others': '挖矿奖励将通过内部转账发送到您的DeGate余额',
  'operations.claim_rewards': '可领取奖励',
  'operations.claim_err_amount': '可领取数量不足',
  'operations.claim': '领取',
  'operations.Claimable': '待领取',
  'operations.Unclaimed': '未领取',
  'operations.claim_mining_rewards': '领取挖矿奖励',
  'operations.claim_rewards_desc':
    '挖矿奖励将在扣除矿工费后通过内部转账发送到您的账户',
  'operations.pay_deposit': '付费入账',
  'operations.pay_deposit_title': '待支付',
  'operations.pay_deposit_desc_XXX_ETH': '您有XXX ETH待入账',
  'operations.pay_deposit_select_account': '支付方式',
  Wallet_Balance: '钱包余额',
  'operations.pay_deposit_tips_XXX_ETH': '支付 XXX ETH',
  'operations.reset_account': '重置资产密钥',
  'operations.reset_desc':
    '资产密钥存储在您本地浏览器缓存。如果怀疑本地环境有安全风险，请重置资产密钥。',
  'operations.reset_warning':
    '请注意：重置时，一切与资产相关的操作都将暂停使用，例如交易、发送资产、内部转账等。',
  'operations.reset_estimated_time': '预估时间',
  'operations.reset_order_tips':
    '一旦发起重置，所有进行中的订单会被<b>立即撤销</b>，请确认',
  'operations.reset_order_tips_btn2': '我再想想',
  'operations.claim_dg_rewards': '领取DG奖励',
  'operations.claim_REBASE': '领取REBASE',
  'operations.claim_REBASE_desc': 'REBASE将通过内部转账发到您的DeGate余额',
  'operations.claim_REBASE_tips': '未领取的REBASE也计入收益计算',
  'operations.view_yield_history': '查看分红历史',
  'operations.cancel_orders_on_chain': '链上取消订单',
  'operations.chain_cancel_dca_text_N':
    '此定投计划中的<b>N个订单</b>的取消请求将被提交到链上。',
  'operations.confirm_cancel_gas_AMOUNT_ETH':
    '请再次确认链上取消的矿工费为<b>AMOUNT ETH</b>。',
  'trade.confirm_order': '确认订单',
  'trade.stop_limit_order': '止盈止损',
  'trade.stop_limit_order_sell_desc_STOPPRICE_QUOTE_PRICE_BASEAMOUNT_BASE':
    'stop_limit_order_sell_desc_STOPPRICE_QUOTE_PRICE_BASEAMOUNT_BASE',
  'trade.stop_price': '触发价',
  'trade.limit_price': '委托价',
  'trade.market_price': '市价',
  'trade.total': '成交额',
  'trade.pay': '支付',
  'trade.receive': '获得',
  'trade.hide_pair_confirm': '本交易对不再显示',
  'trade.pay_the_following_amount_to_place_order': '支付以下金额以完成下单：',
  'trade.flow_of_funds': '资金流向',
  'trade.flow_of_funds_tip2':
    '下单成功。订单资金会计入您的DeGate余额，而不是您的钱包余额。',
  'trade.pay_to_place_order': '支付以完成下单',
  'trade.pay_xxx_USDC_to_place_order': '支付xxx USDC以完成下单',
  'trade.deposit_type': '划入方式',
  'trade.deposit_type_standard': '标准',
  'transfer.transfer_1_eth_ACCOUNT': '转账1 ETH到',
  'transfer.internal_transfer_address_new_tips':
    '该地址无DeGate使用记录，转账需支付更多矿工费',
  'transfer.address_placeholder': '请输入地址',
  'transfer.to_new_account_tips':
    '该地址无DeGate使用记录，收到的首笔资产将触发额外的链上数据使用，因此这笔转账需支付更多矿工费。',
  'transfer.confirm_internal_transfer': '确认内部转账',
  'transfer.internal_transfer_address_oneself_tips': '不支持内部转账给自己',
  'transfer.transfer_max_err_XXX_USDT': '内部转账一次最多XXX USDT',
  'transfer.before': '修改前',
  'transfer.after': '修改后',
  'transfer.recipient_cex_warning':
    '警告：请勿转账到中心化交易所，您会损失资产。',
  'withdraw.withdraw_max_tips': '已超出系统限制',
  'withdraw.address_placeholder': '请输入以太坊地址',
  'dca.confirm_dca_plan': '确认定投计划',
  'dca.number_of_orders': '订单数',
  'dca.amount_per_order': '每笔订单金额',
  'dca.time_scheduled': '计划时间',
  'dca.creating_the_plan': '正在创建计划...',
  'dca.maximum_price': '最高买入价格',
  'dca.minimum_price': '最低卖出价格',
  'dca.do_not_close': '请不要关闭或刷新当前页面',
  'dca.frequency': '频率',
  total_amount: '总金额',
  'dca.daily': '每天',
  'dca.weekly': '每周',
  'dca.every': '每',
  'airdrop.review_airdrop': '预览空投',
  'airdrop.create_airdrop': '创建空投',
  'airdrop.recipients_number': '地址总数',
  'airdrop.airdrop_fee': '空投费',
  'airdrop.pay_airdrop_fee': '支付空投费',
  'airdrop.send_airdrop_token': '发送空投代币',
  'airdrop.claim_airdrop': '领取空投',
  'airdrop.retrieve': '取回',
  'countdown.create_countdown_plan': '创建首发计划',
  'countdown.countdown_display': '显示倒计时',
  'countdown.max_30_days': '从现在起最多30天',
  'countdown.review_countdown_plan': '检查首发计划',
  'countdown.countdown_fee': '首发费',
  grid_slippage_over_2_tips_SLIPPAGE_QUOTE_BASE:
    '系统将通过市价单将一部分QUOTE兑换为BASE，预计滑点为 SLIPPAGE。',
  grid_slippage_over_5_tips_SLIPPAGE_QUOTE_BASE:
    '系统将通过市价单将一部分QUOTE兑换为BASE，预计滑点为 SLIPPAGE。建议采用双资产模式进行投资。',
  connected: '已连接',
  browser_wallet: '手机钱包',
  Convert_to_YYY: '兑换成YYY',
  sell_XXX_to_YYY: '您是否想将XXX以市价卖成YYY？',
  you_sell: '卖出',
  you_receive: '收到',
  est_slippage: '预计滑点',
  No: '不',
  closing_sell: '关闭卖出',
  connect_wallet: '连接钱包',
  Add: '添加',
};
export default zh;
